### ISSUE TITLE
choose trial will be broken when click table pagination

### ISSUE THREAD

**Issue by Lijiaoa** [microsoft/nni#2899] opened 2020-09-16 07:23 UTC
**Environment**:
- NNI version:
- NNI mode (local|remote|pai):
- Client OS:
- Server OS (for remote mode only):
- Python version:
- PyTorch/TensorFlow version:
- Is conda/virtualenv/venv used?:
- Is running in Docker?:

**Log message**:
 - nnimanager.log: 
 - dispatcher.log:
 - nnictl stdout and stderr:
 

**What issue meet, what's expected?**:
bug: 只能选择当页的trial来比较。
expected: compare trials 功能不会被表格分页影响。
**How to reproduce it?**: 

**Additional information**:

**Comment by ultmaster** [comment] 2020-09-18 03:03
This issue might be fixed in #2900. We can also make it "by design".

**Comment by kvartet** [comment] 2021-02-01 14:37
closed as it had been merged.

**Closed by kvartet** 2021-02-01 14:37 UTC
Labels: nnidev
