### ISSUE TITLE
The operation "kill the trial" in the Web UI is not safe 

### ISSUE THREAD

**Issue by kepsail** [microsoft/nni#1765] opened 2019-11-21 08:32 UTC
The  Web UI is not authorized. Other users in the same LAN who can access the WebUI could kill one trial.

**Comment by kepsail** [comment] 2019-11-21 08:33
I think the 'kill' button can be removed from the WebUI.

**Comment by liuzhe-lz** [comment] 2019-11-21 10:59
Duplicate of #1542

**Closed** 2019-11-21 12:09 UTC
