### ISSUE TITLE
Could not visualize the enas MicroNetwork

### ISSUE THREAD

**Issue by ylzf0000** [microsoft/nni#3082] opened 2020-11-11 10:12 UTC
**Environment**: 
- NNI version:1.9
- NNI mode (local|remote|pai): local
- Client OS: Win10 and Ubuntu16.04
- Python version: python3.7.9
- PyTorch/TensorFlow version: PyTorch 1.4
- Is conda/virtualenv/venv used?: conda is used
- Is running in Docker?: no

**Log message**:
 - nnictl stdout and stderr: 
Files already downloaded and verified
Files already downloaded and verified
[11/11/2020, 06:00:25 PM] INFO (nni.nas.pytorch.trainer) Creating graph json, writing to logs\1605088815.3299448. Visualization enabled.
D:\Github\nni\examples\nas\enas\micro.py:118: TracerWarning: Converting a tensor to a Python index might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  nodes_used_mask[:mask.size(0)] |= mask.to(node_out.device)
D:\ProgramData\Anaconda3\envs\nas37\lib\site-packages\torch\tensor.py:461: RuntimeWarning: Iterating over a tensor might cause the trace to be incorrect. Passing a tensor of different shape won't change the number of iterations executed (and might lead to errors or silently give incorrect results).
  'incorrect results).', category=RuntimeWarning)
D:\Github\nni\examples\nas\enas\micro.py:121: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  unused_nodes = torch.cat([out for used, out in zip(nodes_used_mask, prev_nodes_out) if not used], 1)
Traceback (most recent call last):
  File "D:\ProgramData\Anaconda3\envs\nas37\lib\site-packages\torch\jit\__init__.py", line 639, in run_mod_and_filter_tensor_outputs
    outs = wrap_retval(mod(*_clone_inputs(inputs)))
RuntimeError: nSubTensors_ > 1 INTERNAL ASSERT FAILED at C:\w\1\s\tmp_conda_3.7_100118\conda\conda-bld\pytorch_1579082551706\work\torch/csrc/jit/fuser/partition_desc.h:24, please report a bug to PyTorch. 
The above operation failed in interpreter.
Traceback (most recent call last):

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:/Github/nni/examples/nas/enas/search.py", line 60, in <module>
    trainer.enable_visualization()
  File "D:\ProgramData\Anaconda3\envs\nas37\lib\site-packages\nni\nas\pytorch\trainer.py", line 189, in enable_visualization
    json.dump(self.mutator.graph(sample), f)
  File "D:\ProgramData\Anaconda3\envs\nas37\lib\site-packages\nni\nas\pytorch\mutator.py", line 115, in graph
    graph_def, _ = build_graph(self.model, inputs, verbose=False)
  File "D:\ProgramData\Anaconda3\envs\nas37\lib\site-packages\nni\_graph_utils.py", line 27, in build_graph
    g = TorchProtoGraph(model, dummy_input, verbose)
  File "D:\ProgramData\Anaconda3\envs\nas37\lib\site-packages\nni\_graph_utils.py", line 86, in __init__
    super().__init__(model, dummy_input)
  File "D:\ProgramData\Anaconda3\envs\nas37\lib\site-packages\nni\_graph_utils.py", line 65, in __init__
    self._trace(model, dummy_input)
  File "D:\ProgramData\Anaconda3\envs\nas37\lib\site-packages\nni\_graph_utils.py", line 72, in _trace
    self.trace = torch.jit.trace(model, dummy_input)
  File "D:\ProgramData\Anaconda3\envs\nas37\lib\site-packages\torch\jit\__init__.py", line 882, in trace
    check_tolerance, _force_outplace, _module_class)
  File "D:\ProgramData\Anaconda3\envs\nas37\lib\site-packages\torch\jit\__init__.py", line 1044, in trace_module
    check_tolerance, _force_outplace, True, _module_class)
  File "D:\ProgramData\Anaconda3\envs\nas37\lib\site-packages\torch\autograd\grad_mode.py", line 49, in decorate_no_grad
    return func(*args, **kwargs)
  File "D:\ProgramData\Anaconda3\envs\nas37\lib\site-packages\torch\jit\__init__.py", line 677, in _check_trace
    traced_outs = run_mod_and_filter_tensor_outputs(traced_func, inputs, 'trace')
  File "D:\ProgramData\Anaconda3\envs\nas37\lib\site-packages\torch\jit\__init__.py", line 645, in run_mod_and_filter_tensor_outputs
    ' with test inputs.\nException:\n' + indent(str(e)))
torch.jit.TracingCheckError: Tracing failed sanity checks!
Encountered an exception while running the trace with test inputs.
Exception:
	nSubTensors_ > 1 INTERNAL ASSERT FAILED at C:\w\1\s\tmp_conda_3.7_100118\conda\conda-bld\pytorch_1579082551706\work\torch/csrc/jit/fuser/partition_desc.h:24, please report a bug to PyTorch. 
	The above operation failed in interpreter.
	Traceback (most recent call last):

Process finished with exit code 1

**What issue meet, what's expected?**: I want to visualize the enas MicroNetwork.

**How to reproduce it?**: 
cd examples/nas/enas
python3 search.py --search-for micro --visualization

**Additional information**:
Though MicroNetwork could not be visualized, MacroNetwork could. Just use  
python3 search.py --search-for macro --visualization

**Comment by kvartet** [comment] 2020-12-07 04:04
I'm closing this issue because it is a duplicate of #3083. I think #3083 can help you solve your doubts.

**Closed by kvartet** 2020-12-07 04:04 UTC
Labels: NAS visualization, customer raised, support
