### ISSUE TITLE
Training extremely slow with Azure Machine Learning

### ISSUE THREAD

**Issue by yangmingwanli** [microsoft/nni#3518] opened 2021-04-08 07:39 UTC
**Environment**:
- NNI version: 2.0
- NNI mode (local|remote|pai): remote
- Client OS: Windows 10
- Server OS (for remote mode only): Linux
- Python version: 3.6.12
- PyTorch/TensorFlow version:  PyTorch1.7.1
- Is conda/virtualenv/venv used?: conda
- Is running in Docker?: No

**Log message**:
 - nnimanager.log: 
 [2021-04-07 15:24:48] INFO [ 'Datastore initialization done' ]
[2021-04-07 15:24:48] INFO [ 'RestServer start' ]
[2021-04-07 15:24:48] INFO [ 'RestServer base port is 8086' ]
[2021-04-07 15:24:48] INFO [ 'Rest server listening on: http://0.0.0.0:8086' ]
[2021-04-07 15:24:51] INFO [ 'NNIManager setClusterMetadata, key: aml_config, value: {"subscriptionId":"xxxxxxxxxxxx","resourceGroup":"xxxxxxxxxxxxxxx","workspaceName":"xxxxxxxxxxxxxx","computeTarget":"xxxxxxxxxxxxxxxx"}' ]
[2021-04-07 15:24:53] INFO [ 'NNIManager setClusterMetadata, key: nni_manager_ip, value: {"nniManagerIp":"10.194.188.18"}' ]
[2021-04-07 15:24:55] INFO [ 'NNIManager setClusterMetadata, key: trial_config, value: {"command":"python3 mnist.py","codeDir":"C:\\\\Users\\\\yanmi\\\\nni\\\\examples\\\\trials\\\\mnist-pytorch\\\\.","image":"msranni/nni"}' ]
[2021-04-07 15:24:57] INFO [ 'Starting experiment: fy8bAx3K' ]
[2021-04-07 15:24:57] INFO [ 'Change NNIManager status from: INITIALIZED to: RUNNING' ]
[2021-04-07 15:24:57] INFO [ 'Add event listeners' ]
[2021-04-07 15:24:57] INFO [ 'TrialDispatcher: started channel: AMLCommandChannel' ]
[2021-04-07 15:24:57] INFO [ 'TrialDispatcher: copying code and settings.' ]
[2021-04-07 15:25:06] INFO [ 'NNIManager received command from dispatcher: ID, ' ]
[2021-04-07 15:25:06] INFO [ 'NNIManager received command from dispatcher: TR, {"parameter_id": 0, "parameter_source": "algorithm", "parameters": {"batch_size": 128, "hidden_size": 128, "lr": 0.1, "momentum": 0.754420685055723}, "parameter_index": 0}' ]
[2021-04-07 15:25:07] INFO [ 'Initialize environments total number: 0' ]
[2021-04-07 15:25:07] INFO [ 'TrialDispatcher: run loop started.' ]
[2021-04-07 15:25:11] INFO [ 'submitTrialJob: form: {"sequenceId":0,"hyperParameters":{"value":"{\\"parameter_id\\": 0, \\"parameter_source\\": \\"algorithm\\", \\"parameters\\": {\\"batch_size\\": 128, \\"hidden_size\\": 128, \\"lr\\": 0.1, \\"momentum\\": 0.754420685055723}, \\"parameter_index\\": 0}","index":0}}' ]
[2021-04-07 15:25:12] INFO [ 'Assign environment service aml to environment XlEgg' ]
[2021-04-07 15:25:24] INFO [ 'requested environment nni_exp_fy8bAx3K_1617834318_1a1683cd and job id is nni_exp_fy8bAx3K_env_XlEgg.' ]
[2021-04-07 15:25:24] INFO [ 'requested new environment, live trials: 1, live environments: 0, neededEnvironmentCount: 1, requestedCount: 1' ]
[2021-04-07 15:25:42] INFO [ 'EnvironmentInformation: nni_exp_fy8bAx3K_env_XlEgg change status from UNKNOWN to WAITING.' ]
[2021-04-07 15:28:27] INFO [ 'EnvironmentInformation: nni_exp_fy8bAx3K_env_XlEgg change status from WAITING to RUNNING.' ]
[2021-04-07 15:29:35] INFO [ 'TrialDispatcher: env nni_exp_fy8bAx3K_1617834318_1a1683cd received initialized message and runner is ready, env status: RUNNING.' ]
[2021-04-07 15:29:35] INFO [ 'assigning environment nni_exp_fy8bAx3K_1617834318_1a1683cd to trial KH7Ph.' ]
[2021-04-07 15:29:36] INFO [ 'Trial job KH7Ph status changed from WAITING to RUNNING' ]
[2021-04-07 15:34:06] INFO [ 'Trial job KH7Ph status changed from RUNNING to SUCCEEDED' ]
[2021-04-07 15:34:06] INFO [ 'NNIManager received command from dispatcher: TR, {"parameter_id": 1, "parameter_source": "algorithm", "parameters": {"batch_size": 128, "hidden_size": 128, "lr": 0.001, "momentum": 0.48989819362825704}, "parameter_index": 0}' ]
[2021-04-07 15:34:11] INFO [ 'submitTrialJob: form: {"sequenceId":1,"hyperParameters":{"value":"{\\"parameter_id\\": 1, \\"parameter_source\\": \\"algorithm\\", \\"parameters\\": {\\"batch_size\\": 128, \\"hidden_size\\": 128, \\"lr\\": 0.001, \\"momentum\\": 0.48989819362825704}, \\"parameter_index\\": 0}","index":0}}' ]
[2021-04-07 15:34:12] INFO [ 'assigning environment nni_exp_fy8bAx3K_1617834318_1a1683cd to trial Uh6jK.' ]
[2021-04-07 15:34:16] INFO [ 'Trial job Uh6jK status changed from WAITING to RUNNING' ]
[2021-04-07 15:37:26] INFO [ 'Trial job Uh6jK status changed from RUNNING to SUCCEEDED' ]
[2021-04-07 15:37:26] INFO [ 'NNIManager received command from dispatcher: TR, {"parameter_id": 2, "parameter_source": "algorithm", "parameters": {"batch_size": 16, "hidden_size": 256, "lr": 0.01, "momentum": 0.7009004965885264}, "parameter_index": 0}' ]
[2021-04-07 15:37:31] INFO [ 'submitTrialJob: form: {"sequenceId":2,"hyperParameters":{"value":"{\\"parameter_id\\": 2, \\"parameter_source\\": \\"algorithm\\", \\"parameters\\": {\\"batch_size\\": 16, \\"hidden_size\\": 256, \\"lr\\": 0.01, \\"momentum\\": 0.7009004965885264}, \\"parameter_index\\": 0}","index":0}}' ]
[2021-04-07 15:37:32] INFO [ 'assigning environment nni_exp_fy8bAx3K_1617834318_1a1683cd to trial JqjWi.' ]
[2021-04-07 15:37:36] INFO [ 'Trial job JqjWi status changed from WAITING to RUNNING' ]
[2021-04-07 15:41:26] INFO [ 'Trial job JqjWi status changed from RUNNING to SUCCEEDED' ]
[2021-04-07 15:41:26] INFO [ 'NNIManager received command from dispatcher: TR, {"parameter_id": 3, "parameter_source": "algorithm", "parameters": {"batch_size": 32, "hidden_size": 512, "lr": 0.1, "momentum": 0.6258856288476062}, "parameter_index": 0}' ]
[2021-04-07 15:41:31] INFO [ 'submitTrialJob: form: {"sequenceId":3,"hyperParameters":{"value":"{\\"parameter_id\\": 3, \\"parameter_source\\": \\"algorithm\\", \\"parameters\\": {\\"batch_size\\": 32, \\"hidden_size\\": 512, \\"lr\\": 0.1, \\"momentum\\": 0.6258856288476062}, \\"parameter_index\\": 0}","index":0}}' ]
[2021-04-07 15:41:32] INFO [ 'assigning environment nni_exp_fy8bAx3K_1617834318_1a1683cd to trial ijhph.' ]
[2021-04-07 15:41:36] INFO [ 'Trial job ijhph status changed from WAITING to RUNNING' ]
[2021-04-07 15:46:31] INFO [ 'Trial job ijhph status changed from RUNNING to SUCCEEDED' ]
[2021-04-07 15:46:31] INFO [ 'NNIManager received command from dispatcher: TR, {"parameter_id": 4, "parameter_source": "algorithm", "parameters": {"batch_size": 128, "hidden_size": 1024, "lr": 0.1, "momentum": 0.30905289366545063}, "parameter_index": 0}' ]
[2021-04-07 15:46:36] INFO [ 'submitTrialJob: form: {"sequenceId":4,"hyperParameters":{"value":"{\\"parameter_id\\": 4, \\"parameter_source\\": \\"algorithm\\", \\"parameters\\": {\\"batch_size\\": 128, \\"hidden_size\\": 1024, \\"lr\\": 0.1, \\"momentum\\": 0.30905289366545063}, \\"parameter_index\\": 0}","index":0}}' ]
[2021-04-07 15:46:38] INFO [ 'assigning environment nni_exp_fy8bAx3K_1617834318_1a1683cd to trial bElKu.' ]
[2021-04-07 15:46:41] INFO [ 'Trial job bElKu status changed from WAITING to RUNNING' ]
[2021-04-07 15:52:06] INFO [ 'Trial job bElKu status changed from RUNNING to SUCCEEDED' ]
[2021-04-07 15:52:06] INFO [ 'NNIManager received command from dispatcher: TR, {"parameter_id": 5, "parameter_source": "algorithm", "parameters": {"batch_size": 128, "hidden_size": 1024, "lr": 0.0001, "momentum": 0.0003307910747289977}, "parameter_index": 0}' ]
[2021-04-07 15:52:11] INFO [ 'submitTrialJob: form: {"sequenceId":5,"hyperParameters":{"value":"{\\"parameter_id\\": 5, \\"parameter_source\\": \\"algorithm\\", \\"parameters\\": {\\"batch_size\\": 128, \\"hidden_size\\": 1024, \\"lr\\": 0.0001, \\"momentum\\": 0.0003307910747289977}, \\"parameter_index\\": 0}","index":0}}' ]
[2021-04-07 15:52:12] INFO [ 'assigning environment nni_exp_fy8bAx3K_1617834318_1a1683cd to trial upDtw.' ]
[2021-04-07 15:52:16] INFO [ 'Trial job upDtw status changed from WAITING to RUNNING' ]
[2021-04-07 15:56:07] INFO [ 'Trial job upDtw status changed from RUNNING to SUCCEEDED' ]
[2021-04-07 15:56:07] INFO [ 'NNIManager received command from dispatcher: TR, {"parameter_id": 6, "parameter_source": "algorithm", "parameters": {"batch_size": 64, "hidden_size": 128, "lr": 0.01, "momentum": 0.876381947693324}, "parameter_index": 0}' ]
[2021-04-07 15:56:12] INFO [ 'submitTrialJob: form: {"sequenceId":6,"hyperParameters":{"value":"{\\"parameter_id\\": 6, \\"parameter_source\\": \\"algorithm\\", \\"parameters\\": {\\"batch_size\\": 64, \\"hidden_size\\": 128, \\"lr\\": 0.01, \\"momentum\\": 0.876381947693324}, \\"parameter_index\\": 0}","index":0}}' ]
[2021-04-07 15:56:12] INFO [ 'assigning environment nni_exp_fy8bAx3K_1617834318_1a1683cd to trial Zgo5Q.' ]
[2021-04-07 15:56:17] INFO [ 'Trial job Zgo5Q status changed from WAITING to RUNNING' ]
[2021-04-07 15:59:32] INFO [ 'Trial job Zgo5Q status changed from RUNNING to SUCCEEDED' ]
[2021-04-07 15:59:32] INFO [ 'NNIManager received command from dispatcher: TR, {"parameter_id": 7, "parameter_source": "algorithm", "parameters": {"batch_size": 128, "hidden_size": 512, "lr": 0.1, "momentum": 0.2948365715286464}, "parameter_index": 0}' ]
[2021-04-07 15:59:37] INFO [ 'submitTrialJob: form: {"sequenceId":7,"hyperParameters":{"value":"{\\"parameter_id\\": 7, \\"parameter_source\\": \\"algorithm\\", \\"parameters\\": {\\"batch_size\\": 128, \\"hidden_size\\": 512, \\"lr\\": 0.1, \\"momentum\\": 0.2948365715286464}, \\"parameter_index\\": 0}","index":0}}' ]
[2021-04-07 15:59:38] INFO [ 'assigning environment nni_exp_fy8bAx3K_1617834318_1a1683cd to trial T92cL.' ]
[2021-04-07 15:59:42] INFO [ 'Trial job T92cL status changed from WAITING to RUNNING' ]
[2021-04-07 16:02:49] INFO [ 'Trial job T92cL status changed from RUNNING to SUCCEEDED' ]
[2021-04-07 16:02:49] INFO [ 'NNIManager received command from dispatcher: TR, {"parameter_id": 8, "parameter_source": "algorithm", "parameters": {"batch_size": 16, "hidden_size": 128, "lr": 0.001, "momentum": 0.5108633717497612}, "parameter_index": 0}' ]
[2021-04-07 16:02:54] INFO [ 'submitTrialJob: form: {"sequenceId":8,"hyperParameters":{"value":"{\\"parameter_id\\": 8, \\"parameter_source\\": \\"algorithm\\", \\"parameters\\": {\\"batch_size\\": 16, \\"hidden_size\\": 128, \\"lr\\": 0.001, \\"momentum\\": 0.5108633717497612}, \\"parameter_index\\": 0}","index":0}}' ]
[2021-04-07 16:02:54] INFO [ 'assigning environment nni_exp_fy8bAx3K_1617834318_1a1683cd to trial RoHBk.' ]
[2021-04-07 16:02:59] INFO [ 'Trial job RoHBk status changed from WAITING to RUNNING' ]
[2021-04-07 16:06:58] INFO [ 'Trial job RoHBk status changed from RUNNING to SUCCEEDED' ]
[2021-04-07 16:06:58] INFO [ 'NNIManager received command from dispatcher: TR, {"parameter_id": 9, "parameter_source": "algorithm", "parameters": {"batch_size": 32, "hidden_size": 1024, "lr": 0.1, "momentum": 0.1371728116640185}, "parameter_index": 0}' ]
[2021-04-07 16:07:03] INFO [ 'submitTrialJob: form: {"sequenceId":9,"hyperParameters":{"value":"{\\"parameter_id\\": 9, \\"parameter_source\\": \\"algorithm\\", \\"parameters\\": {\\"batch_size\\": 32, \\"hidden_size\\": 1024, \\"lr\\": 0.1, \\"momentum\\": 0.1371728116640185}, \\"parameter_index\\": 0}","index":0}}' ]
[2021-04-07 16:07:06] INFO [ 'assigning environment nni_exp_fy8bAx3K_1617834318_1a1683cd to trial UURlR.' ]
[2021-04-07 16:07:08] INFO [ 'Trial job UURlR status changed from WAITING to RUNNING' ]
[2021-04-07 16:07:08] INFO [ 'Change NNIManager status from: RUNNING to: NO_MORE_TRIAL' ]
[2021-04-07 16:10:36] INFO [ 'Trial job UURlR status changed from RUNNING to SUCCEEDED' ]
[2021-04-07 16:10:36] INFO [ 'Change NNIManager status from: NO_MORE_TRIAL to: DONE' ]
[2021-04-07 16:10:36] INFO [ 'NNIManager received command from dispatcher: TR, {"parameter_id": 10, "parameter_source": "algorithm", "parameters": {"batch_size": 16, "hidden_size": 128, "lr": 0.01, "momentum": 0.5296207133227185}, "parameter_index": 0}' ]
[2021-04-07 16:10:36] INFO [ 'Experiment done.' ]
[2021-04-07 16:20:40] INFO [ 'EnvironmentInformation: nni_exp_fy8bAx3K_env_XlEgg change status from RUNNING to UNKNOWN.' ]
[2021-04-07 16:21:10] INFO [ 'EnvironmentInformation: nni_exp_fy8bAx3K_env_XlEgg change status from UNKNOWN to SUCCEEDED.' ]

 - dispatcher.log:
 [2021-04-07 15:24:58] INFO (nni.runtime.msg_dispatcher_base/MainThread) Dispatcher started
[2021-04-07 15:25:06] INFO (hyperopt.tpe/Thread-1) tpe_transform took 0.001968 seconds
[2021-04-07 15:25:06] INFO (hyperopt.tpe/Thread-1) TPE using 0 trials
[2021-04-07 15:34:06] INFO (hyperopt.tpe/Thread-1) tpe_transform took 0.000997 seconds
[2021-04-07 15:34:06] INFO (hyperopt.tpe/Thread-1) TPE using 1/1 trials with best loss -98.950000
[2021-04-07 15:37:26] INFO (hyperopt.tpe/Thread-1) tpe_transform took 0.001003 seconds
[2021-04-07 15:37:26] INFO (hyperopt.tpe/Thread-1) TPE using 2/2 trials with best loss -98.950000
[2021-04-07 15:41:26] INFO (hyperopt.tpe/Thread-1) tpe_transform took 0.001019 seconds
[2021-04-07 15:41:26] INFO (hyperopt.tpe/Thread-1) TPE using 3/3 trials with best loss -99.220000
[2021-04-07 15:46:31] INFO (hyperopt.tpe/Thread-1) tpe_transform took 0.001025 seconds
[2021-04-07 15:46:31] INFO (hyperopt.tpe/Thread-1) TPE using 4/4 trials with best loss -99.220000
[2021-04-07 15:52:06] INFO (hyperopt.tpe/Thread-1) tpe_transform took 0.000998 seconds
[2021-04-07 15:52:06] INFO (hyperopt.tpe/Thread-1) TPE using 5/5 trials with best loss -99.300000
[2021-04-07 15:56:07] INFO (hyperopt.tpe/Thread-1) tpe_transform took 0.000969 seconds
[2021-04-07 15:56:07] INFO (hyperopt.tpe/Thread-1) TPE using 6/6 trials with best loss -99.300000
[2021-04-07 15:59:32] INFO (hyperopt.tpe/Thread-1) tpe_transform took 0.001000 seconds
[2021-04-07 15:59:32] INFO (hyperopt.tpe/Thread-1) TPE using 7/7 trials with best loss -99.300000
[2021-04-07 16:02:49] INFO (hyperopt.tpe/Thread-1) tpe_transform took 0.001994 seconds
[2021-04-07 16:02:49] INFO (hyperopt.tpe/Thread-1) TPE using 8/8 trials with best loss -99.300000
[2021-04-07 16:06:58] INFO (hyperopt.tpe/Thread-1) tpe_transform took 0.000997 seconds
[2021-04-07 16:06:58] INFO (hyperopt.tpe/Thread-1) TPE using 9/9 trials with best loss -99.300000
[2021-04-07 16:10:36] INFO (hyperopt.tpe/Thread-1) tpe_transform took 0.000997 seconds
[2021-04-07 16:10:36] INFO (hyperopt.tpe/Thread-1) TPE using 10/10 trials with best loss -99.340000

 - nnictl stdout and stderr:

-----------------------------------------------------------------------
                Experiment start time 2021-04-07 15:24:42
-----------------------------------------------------------------------

-----------------------------------------------------------------------
                Experiment start time 2021-04-07 15:24:42
-----------------------------------------------------------------------
(node:16168) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 message listeners added. Use emitter.setMaxListeners() to increase limit
(node:16168) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit
(node:16168) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 close listeners added. Use emitter.setMaxListeners() to increase limit

**What issue meet, what's expected?**:
The mnist_pytorch example training with Azure ML is unreasonably slow, each trial take about 3 to 5 mins. The entire experiment took nearly 50 mins. I was expecting it to be much faster given that it's using STANDARD_NC6 with GPU - 1 x NVIDIA Tesla K80.

**How to reproduce it?**: 
Follow this doc https://nni.readthedocs.io/en/latest/TrainingService/AMLMode.html

**Additional information**:
Tried adding gpuNum: 1 and useActiveGpu: true in config file, only made it even slower with trials spending more time in waiting status, also instead of doing all 10 trials in 1 run, each trial take 1 run.

**Comment by SparkSnail** [comment] 2021-04-09 09:33
@yangmingwanli Each run only start one trial job, and then start new run?

**Comment by yangmingwanli** [comment] 2021-04-09 16:29
@SparkSnail After adding adding gpuNum: 1 and useActiveGpu: true, yes each run only start one trial job, and then start new run.
Without making these changes, it will finish all trials in one run, just very slowly.

**Comment by SparkSnail** [comment] 2021-04-12 02:37
I reproduced this issue, and this seems to be a bug, will fix it ASAP.

**Comment by yangmingwanli** [comment] 2021-04-19 17:18
@SparkSnail , does it look like going to be a hard to fix bug? Is there any workaround before fix is released? Thanks!

**Comment by SparkSnail** [comment] 2021-04-21 02:17
Have you tried setting gpuNum:0, and resubmit the job?

**Comment by yangmingwanli** [comment] 2021-04-21 06:07
Just tried that, after setting gpuNum:0, training is still extremely slow, didn't start new run for new trial, but failed after two trials due to "Converting circular structure to JSON" error.

**Comment by kvartet** [comment] 2021-06-10 13:29
@SparkSnail is it a bug that needs to be fixed? 

> "Converting circular structure to JSON" error.
    this error had been fixed in NNI v2.3.

**Closed** 2022-09-07 02:29 UTC
Labels: bug, customer raised, support, Training Service
