### ISSUE TITLE
 Run an experiment at local met problem！

### ISSUE THREAD

**Issue by wenku1992abc** [Microsoft/nni#80] opened 2018-09-15 09:19 UTC
According to GetStarted.md ,as follws,

Install NNI through source code

git clone -b v0.1 https://github.com/Microsoft/nni.git
cd nni
chmod +x install.sh
source install.sh

 I had sucessfully installed NNI ,But when I  run an experiment at local ,do such commad: nnictl create --config ~/nni/examples/trials/mnist-annotation/config.yml ,It shows an error,as follws,

Info: Checking experiment...
Info: Starting restful server...
Info: Checking restful server...
Error: Restful server start failed!

Could you help me?

**Comment by QuanluZhang** [comment] 2018-09-15 14:26
1. Please make sure that port 51188 is not occupied by other processes. 
2. Then please run 'nnictl log stderr' to see the error message. 
3. You can also use 'ps aux | grep node' to check is there any running rest server process.

**Comment by wenku1992abc** [comment] 2018-09-17 02:04
1.Check port 51188 is not occupied:

2. Run 'nnictl log stderr' ,It shows,as follws:
(node:18566) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
/home/user/.local/bin/nnimanager: line 3: 18566 Terminated              /home/user/.local/nni/node/bin/node main.js $@
(node:31077) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
/home/user/.local/bin/nnimanager: line 3: 31077 Terminated              /home/user/.local/nni/node/bin/node main.js $@
(node:40883) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
/home/user/.local/bin/nnimanager: line 3: 40883 Terminated              /home/user/.local/nni/node/bin/node main.js $@
(node:870) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
/home/user/.local/bin/nnimanager: line 3:   870 Terminated              /home/user/.local/nni/node/bin/node main.js $@
(node:31529) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
/home/user/.local/bin/nnimanager: line 3: 31529 Terminated              /home/user/.local/nni/node/bin/node main.js $@

3.Run 'ps aux | grep node',It shows,as follws:
user  35104  0.0  0.0  14536  1020 pts/26   S+   09:52   0:00 grep --color=auto node

**Comment by QuanluZhang** [comment] 2018-09-17 03:31
Those lines are only warning (we will fix this warning later).
Could you run:
`nnictl stop`
then, `nnictl create --config ~/nni/examples/trials/mnist-annotation/config.yml`.

If there is still error, please post the content of the following three files:
~/nni/nnictl/log/stderr
~/nni/nnictl/log/stdout
~/nni/experiments/<experiment id>/log/nnimanager.log
Thanks.

**Comment by wenku1992abc** [comment] 2018-09-17 03:42
@QuanluZhang Hi,QuanluZhang.Thanks your reply

- Run 'nnictl stop',it shows,as follows:
Info: Stoping experiment...
Info: Experiment is not running...

Then run 'nnictl create --config ~/nni/examples/trials/mnist-annotation/config.yml.',it shows same error as before

- Post the content of the following three files

1.The content of ~/nni/nnictl/log/stderr ,as follows:
(node:18566) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
/home/user/.local/bin/nnimanager: line 3: 18566 Terminated              /home/user/.local/nni/node/bin/node main.js $@
(node:31077) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
/home/user/.local/bin/nnimanager: line 3: 31077 Terminated              /home/user/.local/nni/node/bin/node main.js $@
(node:40883) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
/home/user/.local/bin/nnimanager: line 3: 40883 Terminated              /home/user/.local/nni/node/bin/node main.js $@
(node:870) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
/home/user/.local/bin/nnimanager: line 3:   870 Terminated              /home/user/.local/nni/node/bin/node main.js $@
(node:31529) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
/home/user/.local/bin/nnimanager: line 3: 31529 Terminated              /home/user/.local/nni/node/bin/node main.js $@
(node:3118) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
/home/user/.local/bin/nnimanager: line 3:  3118 Terminated              /home/user/.local/nni/node/bin/node main.js $@
(node:26800) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
/home/user/.local/bin/nnimanager: line 3: 26800 Terminated              /home/user/.local/nni/node/bin/node main.js $@
(node:12632) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
/home/user/.local/bin/nnimanager: line 3: 12632 Terminated              /home/user/.local/nni/node/bin/node main.js $@

2.The content of ~/nni/nnictl/log/stdout is empty!

3.It doesnot  has ~/nni/experiments//log/nnimanager.log file!

**Comment by yds05** [comment] 2018-09-17 05:06
Hi, @wenku1992abc, thanks for reporting the issue and providing the logs. 

Could you please help confirm if the log you pasted from your ~/nni/experiments//log/nnimanager.log is a complete log? 

A normal log contents in ~/nni/experiments//log/nnimanager.log is something like:
[2018-09-17T03:36:53.950Z] INFO Rest server listening on: http://0.0.0.0:51188
[2018-09-17T03:36:56.773Z] INFO GET: /check-status: body:
{}
[2018-09-17T03:37:03.802Z] INFO GET: /trial-jobs: body:
{}
[2018-09-17T03:37:03.919Z] INFO PUT: /experiment/cluster-metadata: body:
{
    "machine_list": [
        {
....................................................
....................................................

if the log from ~/nni/experiments//log/nnimanager.log  is a complete one, could you also check if port 51188 is opened on your machine's firewall? 

If still have issue, feel free to let us know. Thanks.

**Comment by wenku1992abc** [comment] 2018-09-17 05:33
@yds05 My pleasure!
1.Yes, I checked it again! I am sure log from ~/nni/experiments//log/nnimanager.log is a complete one!

2.According to command 'rpm -qa|grep iptables' in linux, I checked if my machine installed firewall or not.The results is that it has no firewall

**Comment by wenku1992abc** [comment] 2018-09-17 05:55
@QuanluZhang @yds05 May be my problem is the same as this issue,https://github.com/Microsoft/nni/issues/85#issuecomment-421894167
my python is  also installed with anaconda

**Comment by yds05** [comment] 2018-09-17 06:28
@wenku1992abc  Yes, probably it's related to that issue caused by python installed via anaconda. We will fully test nni on anaconda python soon, and let you know if we have any conclusion/solution. Thanks!

**Comment by scarlett2018** [comment] 2018-11-14 03:12
@wenku1992abc  - had you verified whether the resolution works for you? the support had been released in Sept 28.

**Comment by scarlett2018** [comment] 2018-11-14 03:12
I'm closing the item as the fix had been released, @wenku1992abc  please feel free to reopen the issue if it still not work for you, thanks a lot.

**Closed by scarlett2018** 2018-11-14 03:12 UTC

**Comment by wenku1992abc** [comment] 2018-11-30 07:35
~/nni/experiments//log/nnimanager.log :

[2018-11-30T07:10:12.983Z] INFO Rest server listening on: http://0.0.0.0:8085
[2018-11-30T07:10:12.970Z] INFO RestServer start
[2018-11-30T07:10:12.978Z] INFO RestServer base port is 8085
[2018-11-30T07:10:27.643Z] INFO Experiment done, cleaning up...
