### ISSUE TITLE
TypeError: forward() takes 2 positional arguments but 5 were given  在使用m_speedup.speedup_model()模型加速时

### ISSUE THREAD

**Issue by mengxiangqiqin** [microsoft/nni#4505] opened 2022-01-24 13:39 UTC
## NNI 学生项目问题概述 / General Question of Student Program

**请简要概述您的问题 / 观点 :**
**Short summary about the question / idea :**

**请提供 NNI 环境信息 :**
**nni Environment :**
- nni version:
- nni mode(local|pai|remote):
- OS:
- python version:
- is conda or virtualenv used?:
- is running in docker?:

## 其他建议 / Other Advice

**是否需要更新文档（是 / 否）:**
**Need to update document ( yes / no ) :**

**其他分享内容 :**
**Anything else we need to know :**

**Log message / 日志信息 :**
 - [nnimanager.log and dispatcher.log](https://github.com/microsoft/nni/blob/master/docs/en_US/Tutorial/HowToDebug.md#experiment-root-directory) : 

 - [nnictl stdout and stderr](https://github.com/microsoft/nni/blob/master/docs/en_US/Tutorial/Nnictl.md#nnictl%20log%20stdout) :

**Comment by littlelittlehorse** [comment] 2022-01-26 05:38
Hi @mengxiangqiqin:
Thank you for your question.
Can you submit the complete code? I will try to reproduce and solve

**Comment by scarlett2018** [comment] 2022-03-18 09:02
> Hi @mengxiangqiqin: Thank you for your question. Can you submit the complete code? I will try to reproduce and solve.

@mengxiangqiqin - we can not help to narrow down the root cause till you provide more context. Please help to answer the above questions, thanks.

**Comment by scarlett2018** [comment] 2022-04-06 03:29
Closing the issue as overdue as it has no responds for a while, feel free to reopen if you are still seeing the problem on your side.

**Closed by scarlett2018** 2022-04-06 03:29 UTC
Labels: waiting customer confirm, support, close-as-overdue
