### ISSUE TITLE
ModelSpeedup: Error when using own model

### ISSUE THREAD

**Issue by zjh908491372** [microsoft/nni#5005] opened 2022-07-20 03:12 UTC
**Environment**:
- NNI version:2.8
- Python version:3.7
- PyTorch/TensorFlow version:1.11.0
- Is conda/virtualenv/venv used?:yes
- Is running in Docker?:no

**Configuration**:
 - Experiment config (remember to remove secrets!):
 - Search space:

**Log message**:
error path:
  pruner.py
    ModelSpeedup(model, dummy_input, masks).speedup_model()

  compressor.py:
    self.infer_modules_masks()
    self.update_direct_sparsity(curnode)
    state_dict=copy.deepcopy(module.state_dict()), batch_dim=self.batch_dim)

  infer_mask.py:
    self.output = self.module(*dummy_input)

  torch/nn/modules/module.py:
    return forward_call(*input, **kwargs)

error message
  TypeError: forward() missing 1 required positional argument: 'input'
 

How to solve this error?

**Comment by Louis-J** [comment] 2022-07-25 11:36
Need more information. Please provide specific code that reproduces the problem.

**Comment by zjh908491372** [comment] 2022-07-26 03:19
> Need more information. Please provide specific code that reproduces the problem.

Using the "norm_pruning_torch.py" of the example, switch to my own pretrained model and dataloader, and the "ModelSpeedup.speedup_model()" function reports an error when running. Remove "ModelSpeedup.speedup_model()" and the whole code can run and print "FLOPs"
train and test input dimensions [8*batch, 3, 224, 224]

Code:
if __name__ == '__main__':
    parser = argparse.ArgumentParser(description='PyTorch Example for model comporession')
    parser.add_argument('--pruner', type=str, default='l1norm',
                        choices=['l1norm', 'l2norm'],
                        help='pruner to use')
    parser.add_argument('--pretrain-epochs', type=int, default=20,
                        help='number of epochs to pretrain the model')
    parser.add_argument('--fine-tune-epochs', type=int, default=20,
                        help='number of epochs to fine tune the model')
    args = parser.parse_args()

    print('\n' + '=' * 50 + ' START TO TRAIN THE MODEL ' + '=' * 50)
    
    ##load pretrained model
    model = ;
    pre_flops, pre_params, _ = count_flops_params(model, torch.randn([8, 3, 224, 224]).to(device))
    g_epoch = 0

    # Start to prune and speedup
    print('\n' + '=' * 50 + ' START TO PRUNE THE BEST ACCURACY PRETRAINED MODEL ' + '=' * 50)
    config_list = [{
        'sparsity': 0.5,
        'op_types': ['Conv2d']
    }]
    if 'l1' in args.pruner:
        pruner = L1NormPruner(model, config_list)
    else:
        pruner = L2NormPruner(model, config_list)
    _, masks = pruner.compress()
    pruner.show_pruned_weights()
    pruner._unwrap_model()
    ModelSpeedup(model, dummy_input=torch.rand([8, 3, 224, 224]).to(device), masks_file=masks).speedup_model()
    print('\n' + '=' * 50 + ' EVALUATE THE MODEL AFTER SPEEDUP ' + '=' * 50)
    evaluator(model)

    # Optimizer used in the pruner might be patched, so recommend to new an optimizer for fine-tuning stage.
    print('\n' + '=' * 50 + ' START TO FINE TUNE THE MODEL ' + '=' * 50)
    optimizer, scheduler = optimizer_scheduler_generator(model, _lr=0.01, total_epoch=args.fine_tune_epochs)

    best_acc = 0.0
    for i in range(args.fine_tune_epochs):
        trainer(model, optimizer, criterion)
        scheduler.step()
        best_acc = max(evaluator(model), best_acc)
    flops, params, results = count_flops_params(model, torch.randn([8, 3, 224, 224]).to(device))
    print(f'Pretrained model FLOPs {pre_flops/1e6:.2f} M, #Params: {pre_params/1e6:.2f}M')
    print(f'Finetuned model FLOPs {flops/1e6:.2f} M, #Params: {params/1e6:.2f}M, Accuracy: {best_acc: .2f}%')

**Comment by zjh908491372** [comment] 2022-07-26 08:36
> Need more information. Please provide specific code that reproduces the problem.

There is no error when using the quick start of the official documentation

**Comment by zjh908491372** [comment] 2022-07-28 08:59
> Need more information. Please provide specific code that reproduces the problem.

QAT_torch_quantizer.py can be run normally with the same model and datasets, but norm_pruning_torch.py can't be run normally with the same model and datasets.

Traceback (most recent call last):
  File "nni_pruner.py", line 271, in <module>
    ModelSpeedup(model, dummy_input, masks).speedup_model()
  File "nni/compression/pytorch/speedup/compressor.py", line 536, in speedup_model
    self.infer_modules_masks()
  File "nni/compression/pytorch/speedup/compressor.py", line 371, in infer_modules_masks
    self.update_direct_sparsity(curnode)
  File "nni/compression/pytorch/speedup/compressor.py", line 240, in update_direct_sparsity
    state_dict=copy.deepcopy(module.state_dict()), batch_dim=self.batch_dim)
  File "nni/compression/pytorch/speedup/infer_mask.py", line 80, in __init__
    self.output = self.module(*dummy_input)
  File "torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
TypeError: forward() missing 1 required positional argument: 'input'

**Comment by zjh908491372** [comment] 2022-07-28 08:59
> Need more information. Please provide specific code that reproduces the problem.

QAT_torch_quantizer.py can be run normally with the same model and datasets, but norm_pruning_torch.py can't be run normally with the same model and datasets.

Traceback (most recent call last):
  File "nni_pruner.py", line 271, in <module>
    ModelSpeedup(model, dummy_input, masks).speedup_model()
  File "nni/compression/pytorch/speedup/compressor.py", line 536, in speedup_model
    self.infer_modules_masks()
  File "nni/compression/pytorch/speedup/compressor.py", line 371, in infer_modules_masks
    self.update_direct_sparsity(curnode)
  File "nni/compression/pytorch/speedup/compressor.py", line 240, in update_direct_sparsity
    state_dict=copy.deepcopy(module.state_dict()), batch_dim=self.batch_dim)
  File "nni/compression/pytorch/speedup/infer_mask.py", line 80, in __init__
    self.output = self.module(*dummy_input)
  File "torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
TypeError: forward() missing 1 required positional argument: 'input'

**Comment by Louis-J** [comment] 2022-09-09 06:53
Sorry for not replying these days. I think the problem is caused by a specific operator in pytorch, but it's lack of information to find the specific operator. Now in 2.9 version we changed the progress, and i think the problem may be fixed. Have you tried the latest version?

**Comment by zjh908491372** [comment] 2022-09-13 12:04
After updating version 2.9, the problem is solved.

/***
WARNING: throw some args away when calling the function "view"
***/

I don't know if this warning will affect the results. I haven't tested it yet.

**Comment by Louis-J** [comment] 2022-09-15 13:30
In most scenarios this warning will not affect the results. We will refactor the code then the warning would not occur.

If you have no other problems, I'll close this issue.

**Comment by zjh908491372** [comment] 2022-09-16 01:09
> In most scenarios this warning will not affect the results. We will refactor the code then the warning would not occur.
> 
> If you have no other problems, I'll close this issue.

ok

**Closed** 2022-09-26 09:10 UTC
