### ISSUE TITLE
Trial number start counting from zero after resuming the experiment

### ISSUE THREAD

**Issue by colorjam** [microsoft/nni#2564] opened 2020-06-16 11:23 UTC
**Environment**:
- NNI version: 1.6
- NNI mode (local|remote|pai): remote

![image](https://user-images.githubusercontent.com/23700012/84767924-df8b6100-b005-11ea-8969-188869989958.png)

**Comment by ultmaster** [comment] 2020-07-13 13:21
duplicate of #2560

**Closed by ultmaster** 2020-07-13 13:21 UTC
Labels: nnidev
