### ISSUE TITLE
Dispatcher error: read ECONNRESET

### ISSUE THREAD

**Issue by LilySys** [microsoft/nni#2056] opened 2020-02-14 01:41 UTC
nni version: latest
nni mode local
OS: ubuntu16.04 64bit
python version:3.6
is conda or virtualenv used?: yes
is running in docker?:no

when i run "nnictl create --config nni/examples/trials/mnist-tfv1/config.yml", i got following error:
![20200214093201](https://user-images.githubusercontent.com/30501264/74493465-2c064900-4f0d-11ea-935c-e0ca25c90532.png)

and i search for the logs, i see the message below:
[2/13/2020, 5:12:58 PM] INFO [ 'Datastore initialization done' ]
[2/13/2020, 5:12:58 PM] INFO [ 'RestServer start' ]
[2/13/2020, 5:12:58 PM] INFO [ 'Construct local machine training service.' ]
[2/13/2020, 5:12:58 PM] INFO [ 'RestServer base port is 8080' ]
[2/13/2020, 5:12:58 PM] INFO [ 'Rest server listening on: http://0.0.0.0:8080' ]
[2/13/2020, 5:13:00 PM] INFO [ 'NNIManager setClusterMetadata, key: trial_config, value: {"command":"python3 mnist.py","codeDir":"/home/aaa/.autoML_project/nni/examples/trials/mnist-tfv1/.","gpuNum":0}' ]
[2/13/2020, 5:13:00 PM] INFO [ 'required GPU number is 0' ]
[2/13/2020, 5:13:00 PM] INFO [ 'Starting experiment: SmbFtlQx' ]
[2/13/2020, 5:13:00 PM] INFO [ 'Change NNIManager status from: INITIALIZED to: RUNNING' ]
[2/13/2020, 5:13:00 PM] INFO [ 'Add event listeners' ]
[2/13/2020, 5:13:00 PM] INFO [ 'Run local machine training service.' ]
[2/13/2020, 5:13:00 PM] ERROR [ 'Dispatcher error: read ECONNRESET' ]
[2/13/2020, 5:13:00 PM] ERROR [ 'Error: Dispatcher stream error, tuner may have crashed.\n    at EventEmitter.dispatcher.onError (/home/aaa/anaconda3/nni/core/nnimanager.js:505:32)\n    at EventEmitter.emit (events.js:182:13)\n    at Socket.IpcInterface.outgoingStream.on (/home/aaa/anaconda3/nni/core/ipcInterface.js:42:72)\n    at Socket.emit (events.js:182:13)\n    at emitErrorNT (internal/streams/destroy.js:82:8)\n    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)\n    at process._tickCallback (internal/process/next_tick.js:63:19)' ]
[2/13/2020, 5:13:00 PM] INFO [ 'Change NNIManager status from: RUNNING to: ERROR' ]

**Comment by chicm-ms** [comment] 2020-02-14 12:07
Hi @LilySys , Would you please paste the dispatcher.log

**Comment by LilySys** [comment] 2020-02-17 05:26
thank you very much. i solved the problem，but i have a another problem，when i run the minist experiment, the trail is very slow, is this normal?
![20200217115221](https://user-images.githubusercontent.com/30501264/74625952-0a18fa80-5189-11ea-9fd7-eac09b7d088f.png)
![20200217115251](https://user-images.githubusercontent.com/30501264/74625963-100edb80-5189-11ea-9be7-b3051d58b13c.png)

**Comment by chicm-ms** [comment] 2020-02-27 06:38
No, it is not normal, it should be done in a few minutes.  Please paste the content log files if the problem still exists:  nnimanager.log,  dispatcher.log and log files of running trials.

**Comment by caotianwei** [comment] 2020-08-02 16:17
> thank you very much. i solved the problem，but i have a another problem，when i run the minist experiment, the trail is very slow, is this normal?
> ![20200217115221](https://user-images.githubusercontent.com/30501264/74625952-0a18fa80-5189-11ea-9fd7-eac09b7d088f.png)
> ![20200217115251](https://user-images.githubusercontent.com/30501264/74625963-100edb80-5189-11ea-9be7-b3051d58b13c.png)

How did you solve this problem? I met the same one.

**Comment by dsindex** [comment] 2020-11-03 05:51
i also have the same problem;;

```
$ nnictl create --config nni_config.yml --port 9599 --foreground
INFO:  expand searchSpacePath: ./nni_search_space.json to /data/private/iclassifier/./nni_search_space.json
INFO:  expand codeDir: . to /data/private/iclassifier/.
INFO:  Starting restful server...
INFO:  Successfully started Restful server!
INFO:  Setting local config...
INFO:  Successfully set local config!
INFO:  Starting experiment...
INFO:  Successfully started experiment!
------------------------------------------------------------------------------------
The experiment id is cxL0sFai
The Web UI urls are: http://127.0.0.1:9599   http://9.1.40.130:9599
------------------------------------------------------------------------------------

You can use these commands to get more information about the experiment
------------------------------------------------------------------------------------
         commands                       description
1. nnictl experiment show        show the information of experiments
2. nnictl trial ls               list all of trial jobs
3. nnictl top                    monitor the status of running experiments
4. nnictl log stderr             show stderr log content
5. nnictl log stdout             show stdout log content
6. nnictl stop                   stop an experiment
7. nnictl trial kill             kill a trial job by id
8. nnictl --help                 get help information about nnictl
------------------------------------------------------------------------------------
Command reference document https://nni.readthedocs.io/en/latest/Tutorial/Nnictl.html
------------------------------------------------------------------------------------

[11/3/2020, 2:46:43 PM] INFO [ 'Datastore initialization done' ]

[11/3/2020, 2:46:43 PM] INFO [ 'RestServer start' ]

[11/3/2020, 2:46:43 PM] INFO [ 'Construct local machine training service.' ]

[11/3/2020, 2:46:43 PM] INFO [ 'RestServer base port is 9599' ]

[11/3/2020, 2:46:43 PM] INFO [ 'Rest server listening on: http://0.0.0.0:9599' ]

[11/3/2020, 2:46:43 PM] INFO [ 'NNIManager setClusterMetadata, key: trial_config, value: {"command":"python train.py --config=configs/config-densenet-cnn.json --data_dir=data/clova_sentiments_morph --use_transformers_optimizer --warmup_epoch=0 --weight_decay=0.0 --epoch=18 --hp_search_nni --patience=4","codeDir":"/data/private/iclassifier/.","gpuNum":1}' ]

[11/3/2020, 2:46:43 PM] INFO [ 'required GPU number is 1' ]

[11/3/2020, 2:46:43 PM] INFO [ 'Starting experiment: cxL0sFai' ]

[11/3/2020, 2:46:43 PM] INFO [ 'Change NNIManager status from: INITIALIZED to: RUNNING' ]

[11/3/2020, 2:46:43 PM] INFO [ 'Add event listeners' ]

[11/3/2020, 2:46:43 PM] INFO [ 'Run local machine training service.' ]

[11/3/2020, 2:46:44 PM] ERROR [ 'Dispatcher error: read ECONNRESET' ]

[11/3/2020, 2:46:44 PM] ERROR [ 'Error: Dispatcher stream error, tuner may have crashed.\n    at EventEmitter.dispatcher.onError (/usr/local/nni/core/nnimanager.js:512:32)\n    at EventEmitter.emit (events.js:198:13)\n    at Socket.IpcInterface.outgoingStream.on (/usr/local/nni/core/ipcInterface.js:41:72)\n    at Socket.emit (events.js:198:13)\n    at emitErrorNT (internal/streams/destroy.js:91:8)\n    at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)\n    at process._tickCallback (internal/process/next_tick.js:63:19)' ]

[11/3/2020, 2:46:44 PM] INFO [ 'Change NNIManager status from: RUNNING to: ERROR' ]
```

dispatcher.log
```
<!doctype html><html lang="en"><head><meta charset="utf-8"/><link rel="shortcut icon" href="/icon.png"/><meta name="viewport" content="width=device-width,initial-scale=1"/><meta name="theme-color" content="#000000"/><link rel="manifest" href="/manifest.json"/><title>Neural Network Intelligence</title><link href="/static/css/3.cd69d823.chunk.css" rel="stylesheet"><link href="/static/css/main.0660afb8.chunk.css" rel="stylesheet"></head><body><noscript>You need to enable JavaScript to run this app.</noscript><div id="root"></div><script>!function(c){function e(e){for(var t,r,n=e[0],o=e[1],a=e[2],u=0,i=[];u<n.length;u++)r=n[u],d[r]&&i.push(d[r][0]),d[r]=0;for(t in o)Object.prototype.hasOwnProperty.call(o,t)&&(c[t]=o[t]);for(h&&h(e);i.length;)i.shift()();return f.push.apply(f,a||[]),l()}function l(){for(var e,t=0;t<f.length;t++){for(var r=f[t],n=!0,o=1;o<r.length;o++){var a=r[o];0!==d[a]&&(n=!1)}n&&(f.splice(t--,1),e=p(p.s=r[0]))}return e}var r={},s={2:0},d={2:0},f=[];function p(e){if(r[e])return r[e].exports;var t=r[e]={i:e,l:!1,exports:{}};return c[e].call(t.exports,t,t.exports,p),t.l=!0,t.exports}p.e=function(f){var e=[];s[f]?e.push(s[f]):0!==s[f]&&{4:1,5:1,6:1}[f]&&e.push(s[f]=new Promise(function(e,n){for(var t="static/css/"+({}[f]||f)+"."+{0:"31d6cfe0",4:"5c750b80",5:"ab143417",6:"e8de4b18",7:"31d6cfe0"}[f]+".chunk.css",o=p.p+t,r=document.getElementsByTagName("link"),a=0;a<r.length;a++){var u=(c=r[a]).getAttribute("data-href")||c.getAttribute("href");if("stylesheet"===c.rel&&(u===t||u===o))return e()}var i=document.getElementsByTagName("style");for(a=0;a<i.length;a++){var c;if((u=(c=i[a]).getAttribute("data-href"))===t||u===o)return e()}var l=document.createElement("link");l.rel="stylesheet",l.type="text/css",l.onload=e,l.onerror=function(e){var t=e&&e.target&&e.target.src||o,r=new Error("Loading CSS chunk "+f+" failed.\n("+t+")");r.request=t,delete s[f],l.parentNode.removeChild(l),n(r)},l.href=o,document.getElementsByTagName("head")[0].appendChild(l)}).then(function(){s[f]=0}));var r=d[f];if(0!==r)if(r)e.push(r[2]);else{var t=new Promise(function(e,t){r=d[f]=[e,t]});e.push(r[2]=t);var n,a=document.createElement("script");a.charset="utf-8",a.timeout=120,p.nc&&a.setAttribute("nonce",p.nc),a.src=p.p+"static/js/"+({}[f]||f)+"."+{0:"2beb8eb4",4:"9e050c69",5:"fa494792",6:"3be2147b",7:"b565ae55"}[f]+".chunk.js",n=function(e){a.onerror=a.onload=null,clearTimeout(u);var t=d[f];if(0!==t){if(t){var r=e&&("load"===e.type?"missing":e.type),n=e&&e.target&&e.target.src,o=new Error("Loading chunk "+f+" failed.\n("+r+": "+n+")");o.type=r,o.request=n,t[1](o)}d[f]=void 0}};var u=setTimeout(function(){n({type:"timeout",target:a})},12e4);a.onerror=a.onload=n,document.head.appendChild(a)}return Promise.all(e)},p.m=c,p.c=r,p.d=function(e,t,r){p.o(e,t)||Object.defineProperty(e,t,{enumerable:!0,get:r})},p.r=function(e){"undefined"!=typeof Symbol&&Symbol.toStringTag&&Object.defineProperty(e,Symbol.toStringTag,{value:"Module"}),Object.defineProperty(e,"__esModule",{value:!0})},p.t=function(t,e){if(1&e&&(t=p(t)),8&e)return t;if(4&e&&"object"==typeof t&&t&&t.__esModule)return t;var r=Object.create(null);if(p.r(r),Object.defineProperty(r,"default",{enumerable:!0,value:t}),2&e&&"string"!=typeof t)for(var n in t)p.d(r,n,function(e){return t[e]}.bind(null,n));return r},p.n=function(e){var t=e&&e.__esModule?function(){return e.default}:function(){return e};return p.d(t,"a",t),t},p.o=function(e,t){return Object.prototype.hasOwnProperty.call(e,t)},p.p="/",p.oe=function(e){throw console.error(e),e};var t=window.webpackJsonp=window.webpackJsonp||[],n=t.push.bind(t);t.push=e,t=t.slice();for(var o=0;o<t.length;o++)e(t[o]);var h=n;l()}([])</script><script src="/static/js/3.8ea55e32.chunk.js"></script><script src="/static/js/main.bde03aab.chunk.js"></script></body></html>
```

nnictl log stderr
```
-----------------------------------------------------------------------
                Experiment start time 2020-11-03 14:46:42
-----------------------------------------------------------------------
```

nnictl log stdout
```
-----------------------------------------------------------------------
                Experiment start time 2020-11-03 14:46:42
-----------------------------------------------------------------------
```

**Comment by kvartet** [comment] 2021-04-16 07:02
@J-shang

**Comment by scarlett2018** [comment] 2021-06-10 02:03
> @J-shang

@kvartet @J-shang - is this a bug?

**Comment by J-shang** [comment] 2021-06-10 05:16
> > @J-shang
> 
> @kvartet @J-shang - is this a bug?

@scarlett2018 It‘s hard to reproduce and I think this may not a bug right now, we have not encountered this 
problem in recent versions, this might due to dispatcher exit in an unexcept way in old version.

**Comment by kvartet** [comment] 2021-06-10 05:35
@dsindex Can you upgrade to the latest version and try again?

**Comment by dsindex** [comment] 2021-06-10 08:41
@kvartet 

after upgrading to 2.2. it works well. thank you!

**Comment by kvartet** [comment] 2021-06-10 08:44
@dsindex, thanks for your feedback! It seems that this problem no longer exists in the latest version of NNI, so I will close this issue, feel free to reopen it.

**Closed by kvartet** 2021-06-10 08:44 UTC
Labels: cannot reproduce, customer raised, get start, support
