### ISSUE TITLE
AttributeError: 'Conv2d' object has no attribute 'layer_quant_setting'

### ISSUE THREAD

**Issue by ToniButland1998** [microsoft/nni#5204] opened 2022-11-05 05:41 UTC
**Describe the issue**:
When I call                 

calibration_config =quantizer.export_model(model_path =  ...)

it shows this error message: 
AttributeError: 'Conv2d' object has no attribute 'layer_quant_setting'
![image](https://user-images.githubusercontent.com/42618317/200104335-c6bb1b02-c99b-460e-8e42-667772e36ef0.png)

**Comment by Lijiaoa** [comment] 2022-11-07 02:17
hi @ToniButland1998 Thanks for raising this issue. Could you provide more details for us to debug this problem, such as your `code` or `example` and the reproduced progress?

**Comment by J-shang** [comment] 2022-11-07 12:26
hello @ToniButland1998 , did you export twice? `xxx.layer_quant_setting` will be deleted after export.

**Comment by ToniButland1998** [comment] 2022-11-08 04:20
> hello @ToniButland1998 , did you export twice? `xxx.layer_quant_setting` will be deleted after export.

Hi J-Shang, Thank you for your remind. I did export it twice. Now I only export once, and it works. Thanks.

**Comment by Lijiaoa** [comment] 2022-11-10 02:47
We'll close this issue as completed if you have any questions please reopen it.

**Closed** 2022-11-10 02:49 UTC

**Comment by diaofeng698** [comment] 2023-06-08 04:46
@J-shang  export twice? How can i do？ Can you please give more details because i met this issue according to NNI guide. Thanks
