### ISSUE TITLE
Strange problems in the opevo experimental environment？

### ISSUE THREAD

**Issue by jyhengcoder** [microsoft/nni#3152] opened 2020-12-02 11:28 UTC
## Environment
- NNI version: 1.8
- Is running in Docker?: Yes

I configured the experimental environment of **opevo** according to the guidelines of the [document ](https://nni.readthedocs.io/en/latest/TrialExample/OpEvoExamples.html). But I encountered a problem when starting docker.
### MakeFile
```
ocm-env: build 
    docker run -it --rm --privileged -v /:/host -w /root \ 
        -e BACKEND=c-rocm -p 8080:8080 \ 
        tvm4nni bash || true 
 
cuda-env: build 
    docker run -it --rm --privileged -v /:/host -w /root \ 
        -e BACKEND=c-cuda -p 8080:8080 \ 
        -v /usr/lib64/libcuda.so.1:/usr/lib/x86_64-linux-gnu/libcuda.so.1 \ 
        -v $(shell dirname `ldd /usr/lib64/libcuda.so.1 | grep nvidia-fatbinaryloader | awk '{print $$3}'`):/usr/local/nvidia/lib64 \ 
        tvm4nni bash || true 
 
build: 
    docker build -t tvm4nni --network=host .
```
### Create and start dockcer
Use the following commands :
```
make cuda-env
```
Then I found that the system commands can no longer be used.
> root@aaebe05e4b0c:~# ls                                                                      
ls: relocation error: /usr/local/nvidia/lib64/libpthread.so.0: symbol h_errno version GLIBC_PRIVATE not defined in file libc.so.6 with link time reference

To solve this problem, I modified the MakeFile
```
cuda-env: build 
    docker run -it --rm --privileged -v /:/host -w /root \ 
        -e BACKEND=c-cuda -p 8080:8080 \ 
        -v /lib64/:/lib64 \
        -v /usr/lib64/libcuda.so.1:/usr/lib/x86_64-linux-gnu/libcuda.so.1 \ 
        -v $(shell dirname `ldd /usr/lib64/libcuda.so.1 | grep nvidia-fatbinaryloader | awk '{print $$3}'`):/usr/local/nvidia/lib64 \ 
        tvm4nni bash || true 
```
Then start the docker by `make cuda-env` and the system commands back to normal.

### Start nni task
```
nnictl create --config experiments/mm/N512K1024M1024/config_opevo.yml
```
And then I met an error
> root@57cd4df95727:~# nnictl                                                                  
/usr/bin/python3: /usr/local/nvidia/lib64/libc.so.6: version `GLIBC_2.25' not found (required by /usr/bin/python3)

Then I modified the Makefile again.
```
cuda-env: build 
    docker run -it --rm --privileged -v /data1/jianyuheng/:/host -w /root \ 
        -e BACKEND=c-cuda -p 8080:8080 \ 
        -v /usr/:/usr/ \ 
        -v /lib64:/lib64/ \ 
        -v $(shell dirname `ldd /lib64/libcuda.so.1 | grep nvidia-fatbinaryloader | awk '{print $$3}'`):/usr/local/nvidia/lib64 \ 
        tvm4nni bash || true
```
Then I started the docker by `make cuda-env` and the system commands and nnictl command  all recovered normal. So I ran the following command:
```
nnictl create --config experiments/mm/N512K1024M1024/config_opevo.yml
```
I found that the task can run successfully this time, but few seconds later, I found stderr in all trials and I want to vim the stderr file. But the the system commands `vim` failed.
>root@96ff86eb3951:~# vim nni-experiments/ofNl0Uew/trials/P9Qia/stderr 
vim: relocation error: /usr/local/nvidia/lib64/libpthread.so.0: symbol __getrlimit, version GLIBC_PRIVATE not defined in file libc.so.6 with link time reference

>root@96ff86eb3951:~# ls
ls: relocation error: /usr/local/nvidia/lib64/libpthread.so.0: symbol __getrlimit, version GLIBC_PRIVATE not defined in file libc.so.6 with link time reference

Then I exit docker, and I found systems commands in my native environment are also failed and print the same error.
>~# ls
relocation error: /lib64/libpthread.so.0: symbol __getrlimit, version GLIBC_PRIVATE not defined in file libc.so.6 with link time reference

I solved this problem by 
```
LD_PRELOAD=/lib64/libc-2.17.so rm /usr/lib64/libc.so.6
LD_PRELOAD=/lib64/libc-2.17.so ln -s /lib64/libc-2.17.so  /usr/lib64/libc.so.6
```
**I tried several times to run nni task in docker and every time I met the same error**, I'm so confused about this problem, Anyone can help?

**Comment by gxiaotian** [comment] 2020-12-04 11:04
Hi @jyhengcoder, the first error might be relevant to the Linux distribution you used or the GPU driver, and the rest errors are caused by your modification. If there is no GPU driver problem in the host machine, I suggest you to install the latest version of docker (at least 19.03) and modify the Makefile as follows.
```
cuda-env: build 
        docker run -it --rm --privileged -v /:/host -w /root --gpus all \
        -e BACKEND=c-cuda -p 8080:8080 \
        tvm4nni bash || true
```

**Comment by jyhengcoder** [comment] 2020-12-07 04:10
@gxiaotian According to your method I solved this problem, I will close this issue.

**Comment by jyhengcoder** [comment] 2020-12-07 11:17
@gxiaotian Another problem is, how can I start autosys tuning on a machine without GPU?

**Comment by gxiaotian** [comment] 2020-12-10 11:46
> @gxiaotian Another problem is, how can I start autosys tuning on a machine without GPU?

The example of OpEvo aims to demonstrate its capability to tune kernels on various GPU platforms, so it requires a GPU to run.  [Here](https://github.com/microsoft/nni/blob/master/docs/en_US/TrialExample/RocksdbExamples.rst) is an example for tuning RocksDB with NNI, which doesn't require a GPU.

**Comment by jyhengcoder** [comment] 2020-12-11 03:48
> > @gxiaotian Another problem is, how can I start autosys tuning on a machine without GPU?
> 
> The example of OpEvo aims to demonstrate its capability to tune kernels on various GPU platforms, so it requires a GPU to run. [Here](https://github.com/microsoft/nni/blob/master/docs/en_US/TrialExample/RocksdbExamples.rst) is an example for tuning RocksDB with NNI, which doesn't require a GPU.

@gxiaotian I have read the paper, so I think opevo should be universally applicable to tuning on the CPU, right?

**Comment by gxiaotian** [comment] 2020-12-14 02:31
> > > @gxiaotian Another problem is, how can I start autosys tuning on a machine without GPU?
> > 
> > 
> > The example of OpEvo aims to demonstrate its capability to tune kernels on various GPU platforms, so it requires a GPU to run. [Here](https://github.com/microsoft/nni/blob/master/docs/en_US/TrialExample/RocksdbExamples.rst) is an example for tuning RocksDB with NNI, which doesn't require a GPU.
> 
> @gxiaotian I have read the paper, so I think opevo should be universally applicable to tuning on the CPU, right?

Yes, OpEvo can tune any hardware as long as there are topological structures in the search spaces. However, in this example, we only implemented GPU cases for demonstration purpose. You are encouraged to implement other cases you are interested in and submit pull requests.

**Comment by kvartet** [comment] 2021-06-10 14:52
hello @jyhengcoder, I will close this issue as it has not been updated for more than three months, feel free to reopen it if you still think it an active issue.

**Closed by kvartet** 2021-06-10 14:52 UTC
Labels: autosys, customer raised, support
