### ISSUE TITLE
404 page not found (TFJob on Azure Kubernetes Service)

### ISSUE THREAD

**Issue by konabuta** [microsoft/nni#1708] opened 2019-11-06 02:24 UTC
**Short summary about the issue/question**:

NNI TFJob failed with error "**Job management error: 404 page not found**" on Azure Kubernetes Service.

**Brief what process you are following**: 

I follow [Run an Experiment on Kubeflow](https://nni.readthedocs.io/en/latest/TrainingService/KubeflowMode.html)

The job is on CPU and simple MNIST. This is yml that I use ([config_kubeflow.yml.txt](https://github.com/microsoft/nni/files/3812198/config_kubeflow.yml.txt))

```bash
nnictl create --config config_kubeflow.yml --port 8080 --debug
```

**How to reproduce it**: 

**nni Environment**:
- nni version: 1.1 
- nni mode(local|pai|remote):kubeflow
- OS: NNIManager is on Ubuntu 16.04
- python version:  3.6.9
- is conda or virtualenv used?: Yes 
- is running in docker?:  Yes

**Azure Environment**:
- Kubernetes: 1.13.12

**need to update document(yes/no)**: no

**Anything else we need to know**:

Attached nnimanager.log & dispatcher.log
[nnimanager.log](https://github.com/microsoft/nni/files/3812174/nnimanager.log)
[dispatcher.log](https://github.com/microsoft/nni/files/3812175/dispatcher.log)

![image](https://user-images.githubusercontent.com/3815677/68262858-d3125380-0087-11ea-85bc-b8734629333a.png)

**Comment by SparkSnail** [comment] 2019-11-08 06:07
Hi @konabuta, this issue may be caused by the kubeflow environment. Could you please verify that your kubeflow tf-operator is installed correctly, and the apiVersion is `v1alpha2`? You could run a normal kubeflow job directly instead of from NNI to test.

**Comment by gaocegege** [comment] 2019-11-08 06:11
What's the version of kubeflow in your environment? TFJob v1alpha2 is deprecated after kubeflow 0.4

**Comment by gaocegege** [comment] 2019-11-08 06:15
@sparksnail If you have time, I suggest upgrading TFJob/PyTorchJob to v1 since the API is stable now.

**Comment by SparkSnail** [comment] 2019-11-08 06:37
Thanks @gaocegege, NNI support `v1alpha2`, `v1beta1`, `v1beta2` api-versions now, I'll investigate the `v1` version, and evaluate the effort of supporting.

**Comment by gaocegege** [comment] 2019-11-08 07:03
@SparkSnail 

v1 is similar to v1beta2. Thus if NNI supports v1beta2, it should be easy to support v1. And v1 is stable now and we will not have breaking changes about API in the future.

**Comment by konabuta** [comment] 2019-11-11 03:23
Let me share the current situation. Please see attached file.
[nni_error_log.txt](https://github.com/microsoft/nni/files/3829561/nni_error_log.txt)

-  I tied very simple TFJob and it works.
- My kubernetes is 0.7.0
- I tried v1beta2 and got the **same** error.

as for v1, it got error. How can I use v1 ?
```
(kubeflow) azureuser@kubenni:~/nni/examples/trials/mnist$ nnictl create --config config_kubeflow_v1.yml --debug
INFO: expand searchSpacePath: code/search_space.json to /home/azureuser/nni/examples/trials/mnist/code/search_space.json 
INFO: expand codeDir: . to /home/azureuser/nni/examples/trials/mnist/. 
INFO: Starting restful server...
INFO: Successfully started Restful server!
INFO: Setting kubeflow config...
ERROR: Failed! Error is: {"error":"Invalid tf-operator apiVersion v1"}```

**Comment by gaocegege** [comment] 2019-11-11 03:25
> My kubernetes is 0.7.0

Do you mean your kubeflow version is 0.7.0?

**Comment by SparkSnail** [comment] 2019-11-11 04:03
What is the version of your tf-operator? NNI only support `v1alpha2, v1beta1, v1beta2` now, the `v1` version is not supported yet. You should specify the correct version in NNI's kubeflowConfig.

**Comment by konabuta** [comment] 2019-11-11 08:27
@gaocegege  yes, kubeflow is 0.7.0. 

@SparkSnail  I use v1beta2 in NNI config file.

```yml
kubeflowConfig:
  operator: tf-operator
  apiVersion: v1beta2
  storage: azureStorage
  keyVault:
    vaultName: "kubebuta"
    name: "secret"
  azureStorage:
    accountName: "kubebuta"
    azureShare: "kubeflow"
```

**Comment by SparkSnail** [comment] 2019-11-11 09:25
@konabuta did your simple TFJob use v1beta2 operator?

**Comment by konabuta** [comment] 2019-11-11 16:25
@SparkSnail  I'm sorry ... I found **v1beta2** apiversion is working in my kubeflow.
```bash
error: unable to recognize "tf_job_azure_mnist_v1beta2.yml": no matches for kind "TFJob" in version "kubeflow.org/v1beta2"
```
I'm investigating how to use **v1beta2** in my kubeflow 0.7.0.

**Comment by scarlett2018** [comment] 2020-04-15 06:41
> @SparkSnail I'm sorry ... I found **v1beta2** apiversion is working in my kubeflow.
> 
> ```shell
> (kubeflow) azureuser@kubenni:~/tf-operator/examples/v1/mnist_with_summaries$ kubectl apply -f tf_job_azure_mnist_v1beta2.yml 
> error: unable to recognize "tf_job_azure_mnist_v1beta2.yml": no matches for kind "TFJob" in version "kubeflow.org/v1beta2"
> ```
> 
> I'm investigating how to use **v1beta2** in my kubeflow 0.7.0.

@konabuta - seems it's working on your side now, can we close the issue?

**Comment by kvartet** [comment] 2020-12-07 04:24
I’m closing this issue as it has no updates from customer for 3 months, please feel free to reopen if you are still seeing it an active issue.

**Closed by kvartet** 2020-12-07 04:24 UTC
Labels: Azure Kubernetes, Training Service, customer raised, support, waiting customer confirm
