### ISSUE TITLE
trials all failed while using docker container

### ISSUE THREAD

**Issue by janehiii** [microsoft/nni#1100] opened 2019-05-23 03:56 UTC
**Short summary about the issue/question**:
trials all failed while using docker container
**Brief what process you are following**: 
according to HowToUseDocker.md
I processed-------

`root@1a4511f2aa52:~# nnictl create --config nni/examples/trials/mnist/config.ymlINFO: expand searchSpacePath: search_space.json to /root/nni/examples/trials/mnist/search_space.json 
INFO: expand codeDir: . to /root/nni/examples/trials/mnist/. 
INFO: Starting restful server...
INFO: Successfully started Restful server!
INFO: Setting local config...
INFO: Successfully set local config!
INFO: Starting experiment...
INFO: Successfully started experiment!
-----------------------------------------------------------------------
The experiment id is G70LcB3U
The Web UI urls are: http://172.17.0.2:8080   http://127.0.0.1:8080
-----------------------------------------------------------------------

You can use these commands to get more information about the experiment
-----------------------------------------------------------------------
         commands                       description
1. nnictl experiment show        show the information of experiments
2. nnictl trial ls               list all of trial jobs
3. nnictl top                    monitor the status of running experiments
4. nnictl log stderr             show stderr log content
5. nnictl log stdout             show stdout log content
6. nnictl stop                   stop an experiment
7. nnictl trial kill             kill a trial job by id
8. nnictl --help                 get help information about nnictl
-----------------------------------------------------------------------
`

**How to reproduce it**: 

**nni Environment**:
- nni version:
- nni mode(local|pai|remote):
- OS:
- python version:
- is conda or virtualenv used?: 
- is running in docker?:yes

**need to update document(yes/no)**:

**Anything else we need to know**:
nnimanagerlog as following:

> [5/23/2019, 3:39:38 AM] INFO [ 'Datastore initialization done' ]
[5/23/2019, 3:39:38 AM] INFO [ 'Rest server listening on: http://0.0.0.0:8080' ]
[5/23/2019, 3:39:38 AM] INFO [ 'RestServer start' ]
[5/23/2019, 3:39:38 AM] INFO [ 'Construct local machine training service.' ]
[5/23/2019, 3:39:38 AM] INFO [ 'RestServer base port is 8080' ]
[5/23/2019, 3:39:39 AM] INFO [ 'NNIManager setClusterMetadata, key: trial_config, value: {"gpuNum":0,"command":"python3 mnist.py","codeDir":"/root/nni/examples/trials/mnist/."}' ]
[5/23/2019, 3:39:39 AM] INFO [ 'required GPU number is 0' ]
[5/23/2019, 3:39:39 AM] INFO [ 'Starting experiment: G70LcB3U' ]
[5/23/2019, 3:39:39 AM] INFO [ 'Change NNIManager status from: INITIALIZED to: RUNNING' ]
[5/23/2019, 3:39:39 AM] INFO [ 'Add event listeners' ]
[5/23/2019, 3:39:39 AM] INFO [ 'Run local machine training service.' ]
[5/23/2019, 3:39:40 AM] INFO [ 'NNIManager received command from dispatcher: ID, ' ]
[5/23/2019, 3:39:40 AM] INFO [ 'NNIManager received command from dispatcher: TR, {"parameter_id": 0, "parameter_source": "algorithm", "parameters": {"learning_rate": 0.0001, "conv_size": 7, "hidden_size": 1024, "batch_size": 8, "dropout_rate": 0.5697822345272465}}' ]
[5/23/2019, 3:39:44 AM] INFO [ 'submitTrialJob: form: {"jobType":"TRIAL","hyperParameters":{"value":"{\\"parameter_id\\": 0, \\"parameter_source\\": \\"algorithm\\", \\"parameters\\": {\\"learning_rate\\": 0.0001, \\"conv_size\\": 7, \\"hidden_size\\": 1024, \\"batch_size\\": 8, \\"dropout_rate\\": 0.5697822345272465}}","index":0}}' ]
[5/23/2019, 3:39:50 AM] INFO [ 'Trial job AhLFk status changed from WAITING to RUNNING' ]
[5/23/2019, 3:39:55 AM] INFO [ 'Trial job AhLFk status changed from RUNNING to FAILED' ]

I can't find any error report about this problem.

**Comment by SparkSnail** [comment] 2019-05-23 11:29
Hi, could you provide your trial's log? you could use `nnictl trial ls` to get trial log path, or get the log path from webui. Which docker image did you use? Are you using nni's offical docker image `msranni/nni`? If not, please make sure your docker image have the running environment, like python3, tensorflow etc.

**Comment by janehiii** [comment] 2019-05-23 12:30
root@22d31ba11ed6:~# nnictl trial ls
[
    {
        "endTime":"2019/05/23 12:29:03",
        "hyperParameters":[
            "{\"parameters\":{\"conv_size\":5,\"dropout_rate\":0.5203338282536201,\"learning_rate\":0.1,\"hidden_size\":124,\"batch_size\":1},\"parameter_id\":0,\"parameter_source\":\"algorithm\"}"
        ],
        "id":"Ij83o",
        "logPath":"file://localhost:/root/nni/experiments/DXVsxfQb/trials/Ij83o",
        "sequenceId":0,
        "startTime":"2019/05/23 12:29:03",
        "status":"FAILED",
        "stderrPath":"file:/localhost:/root/nni/experiments/DXVsxfQb/trials/Ij83o/stderr"
    }
]


I was using nni's offical docker image.

**Comment by janehiii** [comment] 2019-05-23 12:31
> Hi, could you provide your trial's log? you could use `nnictl trial ls` to get trial log path, or get the log path from webui. Which docker image did you use? Are you using nni's offical docker image `msranni/nni`? If not, please make sure your docker image have the running environment, like python3, tensorflow etc.

root@22d31ba11ed6:~# nnictl trial ls
[
{
"endTime":"2019/05/23 12:29:03",
"hyperParameters":[
"{"parameters":{"conv_size":5,"dropout_rate":0.5203338282536201,"learning_rate":0.1,"hidden_size":124,"batch_size":1},"parameter_id":0,"parameter_source":"algorithm"}"
],
"id":"Ij83o",
"logPath":"file://localhost:/root/nni/experiments/DXVsxfQb/trials/Ij83o",
"sequenceId":0,
"startTime":"2019/05/23 12:29:03",
"status":"FAILED",
"stderrPath":"file:/localhost:/root/nni/experiments/DXVsxfQb/trials/Ij83o/stderr"
}
]

I was using nni's offical docker image.

**Comment by janehiii** [comment] 2019-05-23 12:58
`Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/usr/lib/python3.5/imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "/usr/lib/python3.5/imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: libcuda.so.1: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "mnist.py", line 9, in <module>
    import tensorflow as tf
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/__init__.py", line 22, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/usr/lib/python3.5/imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "/usr/lib/python3.5/imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: libcuda.so.1: cannot open shared object file: No such file or directory


Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/install_sources#common_installation_problems

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.
~                                                 `
I was using nni's offical docker image

**Comment by janehiii** [comment] 2019-05-23 13:00
> Hi, could you provide your trial's log? you could use `nnictl trial ls` to get trial log path, or get the log path from webui. Which docker image did you use? Are you using nni's offical docker image `msranni/nni`? If not, please make sure your docker image have the running environment, like python3, tensorflow etc.



> Traceback (most recent call last):
>   File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
>     from tensorflow.python.pywrap_tensorflow_internal import *
>   File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
>     _pywrap_tensorflow_internal = swig_import_helper()
>   File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
>     _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
>   File "/usr/lib/python3.5/imp.py", line 242, in load_module
>     return load_dynamic(name, filename, file)
>   File "/usr/lib/python3.5/imp.py", line 342, in load_dynamic
>     return _load(spec)
> ImportError: libcuda.so.1: cannot open shared object file: No such file or directory
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "mnist.py", line 9, in <module>
>     import tensorflow as tf
>   File "/usr/local/lib/python3.5/dist-packages/tensorflow/__init__.py", line 22, in <module>
>     from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
>   File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/__init__.py", line 49, in <module>
>     from tensorflow.python import pywrap_tensorflow
>   File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/pywrap_tensorflow.py", line 74, in <module>
>     raise ImportError(msg)
> ImportError: Traceback (most recent call last):
>   File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
>     from tensorflow.python.pywrap_tensorflow_internal import *
>   File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
>     _pywrap_tensorflow_internal = swig_import_helper()
>   File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
>     _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
>   File "/usr/lib/python3.5/imp.py", line 242, in load_module
>     return load_dynamic(name, filename, file)
>   File "/usr/lib/python3.5/imp.py", line 342, in load_dynamic
>     return _load(spec)
> ImportError: libcuda.so.1: cannot open shared object file: No such file or directory
> 
> 
> Failed to load the native TensorFlow runtime.
> 
> See https://www.tensorflow.org/install/install_sources#common_installation_problems
> 
> for some common reasons and solutions.  Include the entire stack trace
> above this error message when asking for help.

I was using nni's offical docker image msranni/nni

**Comment by demianzhang** [comment] 2019-05-23 16:39
You need to install CUDA and cuDNN first, the docker use tensorflow-gpu version, I met this problem before. You can also install tensorflow cpu version if you don't have gpu to get around it. By the way if you met OOM(out of memory) error, you can expand the docker desktop memory to proper size.

**Comment by janehiii** [comment] 2019-05-24 08:51
Than you , I'll try. However, I noticed msranni/nni support CUDA 9.0, CuDNN 7.0.   Why ?

> You need to install CUDA and cuDNN first, the docker use tensorflow-gpu version, I met this problem before. You can also install tensorflow cpu version if you don't have gpu to get around it. By the way if you met OOM(out of memory) error, you can expand the docker desktop memory to proper size.

**Comment by janehiii** [comment] 2019-05-24 08:52
> You need to install CUDA and cuDNN first, the docker use tensorflow-gpu version, I met this problem before. You can also install tensorflow cpu version if you don't have gpu to get around it. By the way if you met OOM(out of memory) error, you can expand the docker desktop memory to proper size.

Thank you , I'll try. However, I noticed msranni/nni support CUDA 9.0, CuDNN 7.0. Why ?

**Comment by demianzhang** [comment] 2019-05-24 09:02
Hi, @janehiii  it's my mistake, it supports. Please make sure there is a gpu in your machine with docker tensorflow-gpu environment.

**Comment by pratimanagare** [comment] 2019-05-29 18:05
I have the issue, what do I do? @janehiii did you get it working?

**Comment by pratimanagare** [comment] 2019-05-31 09:33
> I have the same issue, what do I do? @janehiii did you get it working?
> 
> Here's what the logs say,
> 
> root@3fabf8565703:~# cat /root/nni/experiments/blJw6LUU/trials/p7xN3/stderr
> Traceback (most recent call last):
> File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in 
> from tensorflow.python.pywrap_tensorflow_internal import *
> File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in 
> _pywrap_tensorflow_internal = swig_import_helper()
> File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
> _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
> File "/usr/lib/python3.5/imp.py", line 242, in load_module
> return load_dynamic(name, filename, file)
> File "/usr/lib/python3.5/imp.py", line 342, in load_dynamic
> return _load(spec)
> ImportError: libcuda.so.1: cannot open shared object file: No such file or directory
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
> File "mnist.py", line 9, in 
> import tensorflow as tf
> File "/usr/local/lib/python3.5/dist-packages/tensorflow/**init**.py", line 22, in 
> from tensorflow.python import pywrap_tensorflow # pylint: disable=unused-import
> File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/**init**.py", line 49, in 
> from tensorflow.python import pywrap_tensorflow
> File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/pywrap_tensorflow.py", line 74, in 
> raise ImportError(msg)
> ImportError: Traceback (most recent call last):
> File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in 
> from tensorflow.python.pywrap_tensorflow_internal import *
> File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in 
> _pywrap_tensorflow_internal = swig_import_helper()
> File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
> _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
> File "/usr/lib/python3.5/imp.py", line 242, in load_module
> return load_dynamic(name, filename, file)
> File "/usr/lib/python3.5/imp.py", line 342, in load_dynamic
> return _load(spec)
> ImportError: libcuda.so.1: cannot open shared object file: No such file or directory

I got it resolved. There was some issue with my nvidia-drivers.

**Comment by scarlett2018** [comment] 2019-06-12 03:02
@janehiii - are you still having problem with the docker? if you are still not able to run trials, we can have IM chat in Gitter: https://gitter.im/Microsoft/nni directly.

**Comment by husimple** [comment] 2019-06-14 08:31
I also encountered a similar problem, my  trial's log is as follows：
[06/14/2019, 07:45:59 AM] ERROR (mnist_AutoML/MainThread) <urlopen error [Errno -3] Temporary failure in name resolution>
    h.request(req.get_method(), req.selector, req.data, headers)
  File "/usr/local/python3.5/lib/python3.5/http/client.py", line 1152, in _send_request
    self.endheaders(body)
  File "/usr/local/python3.5/lib/python3.5/http/client.py", line 1103, in endheaders
    self.send(msg)
  File "/usr/local/python3.5/lib/python3.5/http/client.py", line 877, in send
    self.connect()
  File "/usr/local/python3.5/lib/python3.5/http/client.py", line 1253, in connect
    super().connect()
  File "/usr/local/python3.5/lib/python3.5/http/client.py", line 849, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "/usr/local/python3.5/lib/python3.5/socket.py", line 694, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "/usr/local/python3.5/lib/python3.5/socket.py", line 733, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Temporary failure in name resolution

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
[06/14/2019, 07:45:59 AM] ERROR (mnist_AutoML/MainThread) <urlopen error [Errno -3] Temporary failure in name resolution>
Traceback (most recent call last):
  File "/usr/local/python3.5/lib/python3.5/urllib/request.py", line 1254, in do_open
    h.request(req.get_method(), req.selector, req.data, headers)
  File "/usr/local/python3.5/lib/python3.5/http/client.py", line 1107, in request
    self._send_request(method, url, body, headers)
  File "/usr/local/python3.5/lib/python3.5/http/client.py", line 1152, in _send_request
    self.endheaders(body)
  File "/usr/local/python3.5/lib/python3.5/http/client.py", line 1103, in endheaders
    self._send_output(message_body)
  File "/usr/local/python3.5/lib/python3.5/http/client.py", line 934, in _send_output
    self.send(msg)
  File "/usr/local/python3.5/lib/python3.5/http/client.py", line 877, in send
    self.connect()
  File "/usr/local/python3.5/lib/python3.5/http/client.py", line 1253, in connect
[06/14/2019, 07:45:59 AM] ERROR (mnist_AutoML/MainThread) <urlopen error [Errno -3] Temporary failure in name resolution>
Traceback (most recent call last):
  File "/usr/local/python3.5/lib/python3.5/urllib/request.py", line 1254, in do_open
    h.request(req.get_method(), req.selector, req.data, headers)
  File "/usr/local/python3.5/lib/python3.5/http/client.py", line 1107, in request
    self._send_request(method, url, body, headers)
  File "/usr/local/python3.5/lib/python3.5/http/client.py", line 1152, in _send_request
    self.endheaders(body)
  File "/usr/local/python3.5/lib/python3.5/http/client.py", line 1103, in endheaders
    self._send_output(message_body)
  File "/usr/local/python3.5/lib/python3.5/http/client.py", line 934, in _send_output
    self.send(msg)
  File "/usr/local/python3.5/lib/python3.5/http/client.py", line 877, in send
    self.connect()
  File "/usr/local/python3.5/lib/python3.5/http/client.py", line 1253, in connect
    super().connect()
  File "/usr/local/python3.5/lib/python3.5/http/client.py", line 849, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "/usr/local/python3.5/lib/python3.5/socket.py", line 694, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "/usr/local/python3.5/lib/python3.5/socket.py", line 733, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Temporary failure in name resolution
How can I solve this problem?

**Comment by SparkSnail** [comment] 2019-06-16 15:56
Hi, this issue seems caused by http client connection error. Which image and example did you use in your experiment?

**Comment by SparkSnail** [comment] 2019-06-16 15:56
> I also encountered a similar problem, my trial's log is as follows：
> [06/14/2019, 07:45:59 AM] ERROR (mnist_AutoML/MainThread) <urlopen error [Errno -3] Temporary failure in name resolution>
> h.request(req.get_method(), req.selector, req.data, headers)
> File "/usr/local/python3.5/lib/python3.5/http/client.py", line 1152, in _send_request
> self.endheaders(body)
> File "/usr/local/python3.5/lib/python3.5/http/client.py", line 1103, in endheaders
> self.send(msg)
> File "/usr/local/python3.5/lib/python3.5/http/client.py", line 877, in send
> self.connect()
> File "/usr/local/python3.5/lib/python3.5/http/client.py", line 1253, in connect
> super().connect()
> File "/usr/local/python3.5/lib/python3.5/http/client.py", line 849, in connect
> (self.host,self.port), self.timeout, self.source_address)
> File "/usr/local/python3.5/lib/python3.5/socket.py", line 694, in create_connection
> for res in getaddrinfo(host, port, 0, SOCK_STREAM):
> File "/usr/local/python3.5/lib/python3.5/socket.py", line 733, in getaddrinfo
> for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
> socket.gaierror: [Errno -3] Temporary failure in name resolution
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
> [06/14/2019, 07:45:59 AM] ERROR (mnist_AutoML/MainThread) <urlopen error [Errno -3] Temporary failure in name resolution>
> Traceback (most recent call last):
> File "/usr/local/python3.5/lib/python3.5/urllib/request.py", line 1254, in do_open
> h.request(req.get_method(), req.selector, req.data, headers)
> File "/usr/local/python3.5/lib/python3.5/http/client.py", line 1107, in request
> self._send_request(method, url, body, headers)
> File "/usr/local/python3.5/lib/python3.5/http/client.py", line 1152, in _send_request
> self.endheaders(body)
> File "/usr/local/python3.5/lib/python3.5/http/client.py", line 1103, in endheaders
> self._send_output(message_body)
> File "/usr/local/python3.5/lib/python3.5/http/client.py", line 934, in _send_output
> self.send(msg)
> File "/usr/local/python3.5/lib/python3.5/http/client.py", line 877, in send
> self.connect()
> File "/usr/local/python3.5/lib/python3.5/http/client.py", line 1253, in connect
> [06/14/2019, 07:45:59 AM] ERROR (mnist_AutoML/MainThread) <urlopen error [Errno -3] Temporary failure in name resolution>
> Traceback (most recent call last):
> File "/usr/local/python3.5/lib/python3.5/urllib/request.py", line 1254, in do_open
> h.request(req.get_method(), req.selector, req.data, headers)
> File "/usr/local/python3.5/lib/python3.5/http/client.py", line 1107, in request
> self._send_request(method, url, body, headers)
> File "/usr/local/python3.5/lib/python3.5/http/client.py", line 1152, in _send_request
> self.endheaders(body)
> File "/usr/local/python3.5/lib/python3.5/http/client.py", line 1103, in endheaders
> self._send_output(message_body)
> File "/usr/local/python3.5/lib/python3.5/http/client.py", line 934, in _send_output
> self.send(msg)
> File "/usr/local/python3.5/lib/python3.5/http/client.py", line 877, in send
> self.connect()
> File "/usr/local/python3.5/lib/python3.5/http/client.py", line 1253, in connect
> super().connect()
> File "/usr/local/python3.5/lib/python3.5/http/client.py", line 849, in connect
> (self.host,self.port), self.timeout, self.source_address)
> File "/usr/local/python3.5/lib/python3.5/socket.py", line 694, in create_connection
> for res in getaddrinfo(host, port, 0, SOCK_STREAM):
> File "/usr/local/python3.5/lib/python3.5/socket.py", line 733, in getaddrinfo
> for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
> socket.gaierror: [Errno -3] Temporary failure in name resolution
> How can I solve this problem?

Hi, this issue seems caused by http client connection error. Which image and example did you use in your experiment?

**Comment by husimple** [comment] 2019-06-28 09:37
Thank you very much for your reply, I have encountered a new problem.Remote TrainingService,How can I  set sshKeyPath.




| |
胡然
|
|
邮箱：hrpwtd@126.com
|

签名由 网易邮箱大师 定制

On 06/16/2019 23:56, SparkSnail wrote:

I also encountered a similar problem, my trial's log is as follows：
[06/14/2019, 07:45:59 AM] ERROR (mnist_AutoML/MainThread) <urlopen error [Errno -3] Temporary failure in name resolution>
h.request(req.get_method(), req.selector, req.data, headers)
File "/usr/local/python3.5/lib/python3.5/http/client.py", line 1152, in _send_request
self.endheaders(body)
File "/usr/local/python3.5/lib/python3.5/http/client.py", line 1103, in endheaders
self.send(msg)
File "/usr/local/python3.5/lib/python3.5/http/client.py", line 877, in send
self.connect()
File "/usr/local/python3.5/lib/python3.5/http/client.py", line 1253, in connect
super().connect()
File "/usr/local/python3.5/lib/python3.5/http/client.py", line 849, in connect
(self.host,self.port), self.timeout, self.source_address)
File "/usr/local/python3.5/lib/python3.5/socket.py", line 694, in create_connection
for res in getaddrinfo(host, port, 0, SOCK_STREAM):
File "/usr/local/python3.5/lib/python3.5/socket.py", line 733, in getaddrinfo
for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Temporary failure in name resolution

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
[06/14/2019, 07:45:59 AM] ERROR (mnist_AutoML/MainThread) <urlopen error [Errno -3] Temporary failure in name resolution>
Traceback (most recent call last):
File "/usr/local/python3.5/lib/python3.5/urllib/request.py", line 1254, in do_open
h.request(req.get_method(), req.selector, req.data, headers)
File "/usr/local/python3.5/lib/python3.5/http/client.py", line 1107, in request
self._send_request(method, url, body, headers)
File "/usr/local/python3.5/lib/python3.5/http/client.py", line 1152, in _send_request
self.endheaders(body)
File "/usr/local/python3.5/lib/python3.5/http/client.py", line 1103, in endheaders
self._send_output(message_body)
File "/usr/local/python3.5/lib/python3.5/http/client.py", line 934, in _send_output
self.send(msg)
File "/usr/local/python3.5/lib/python3.5/http/client.py", line 877, in send
self.connect()
File "/usr/local/python3.5/lib/python3.5/http/client.py", line 1253, in connect
[06/14/2019, 07:45:59 AM] ERROR (mnist_AutoML/MainThread) <urlopen error [Errno -3] Temporary failure in name resolution>
Traceback (most recent call last):
File "/usr/local/python3.5/lib/python3.5/urllib/request.py", line 1254, in do_open
h.request(req.get_method(), req.selector, req.data, headers)
File "/usr/local/python3.5/lib/python3.5/http/client.py", line 1107, in request
self._send_request(method, url, body, headers)
File "/usr/local/python3.5/lib/python3.5/http/client.py", line 1152, in _send_request
self.endheaders(body)
File "/usr/local/python3.5/lib/python3.5/http/client.py", line 1103, in endheaders
self._send_output(message_body)
File "/usr/local/python3.5/lib/python3.5/http/client.py", line 934, in _send_output
self.send(msg)
File "/usr/local/python3.5/lib/python3.5/http/client.py", line 877, in send
self.connect()
File "/usr/local/python3.5/lib/python3.5/http/client.py", line 1253, in connect
super().connect()
File "/usr/local/python3.5/lib/python3.5/http/client.py", line 849, in connect
(self.host,self.port), self.timeout, self.source_address)
File "/usr/local/python3.5/lib/python3.5/socket.py", line 694, in create_connection
for res in getaddrinfo(host, port, 0, SOCK_STREAM):
File "/usr/local/python3.5/lib/python3.5/socket.py", line 733, in getaddrinfo
for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Temporary failure in name resolution
How can I solve this problem?

Hi, this issue seems caused by http client connection error. Which image and example did you use in your experiment?

**Comment by SparkSnail** [comment] 2019-08-30 03:23
> Thank you very much for your reply, I have encountered a new problem.Remote TrainingService,How can I set sshKeyPath. | | 胡然 | | 邮箱：hrpwtd@126.com | 签名由 网易邮箱大师 定制 On 06/16/2019 23:56, SparkSnail wrote: I also encountered a similar problem, my trial's log is as follows： [06/14/2019, 07:45:59 AM] ERROR (mnist_AutoML/MainThread) <urlopen error [Errno -3] Temporary failure in name resolution> h.request(req.get_method(), req.selector, req.data, headers) File "/usr/local/python3.5/lib/python3.5/http/client.py", line 1152, in _send_request self.endheaders(body) File "/usr/local/python3.5/lib/python3.5/http/client.py", line 1103, in endheaders self.send(msg) File "/usr/local/python3.5/lib/python3.5/http/client.py", line 877, in send self.connect() File "/usr/local/python3.5/lib/python3.5/http/client.py", line 1253, in connect super().connect() File "/usr/local/python3.5/lib/python3.5/http/client.py", line 849, in connect (self.host,self.port), self.timeout, self.source_address) File "/usr/local/python3.5/lib/python3.5/socket.py", line 694, in create_connection for res in getaddrinfo(host, port, 0, SOCK_STREAM): File "/usr/local/python3.5/lib/python3.5/socket.py", line 733, in getaddrinfo for res in _socket.getaddrinfo(host, port, family, type, proto, flags): socket.gaierror: [Errno -3] Temporary failure in name resolution During handling of the above exception, another exception occurred: Traceback (most recent call last): [06/14/2019, 07:45:59 AM] ERROR (mnist_AutoML/MainThread) <urlopen error [Errno -3] Temporary failure in name resolution> Traceback (most recent call last): File "/usr/local/python3.5/lib/python3.5/urllib/request.py", line 1254, in do_open h.request(req.get_method(), req.selector, req.data, headers) File "/usr/local/python3.5/lib/python3.5/http/client.py", line 1107, in request self._send_request(method, url, body, headers) File "/usr/local/python3.5/lib/python3.5/http/client.py", line 1152, in _send_request self.endheaders(body) File "/usr/local/python3.5/lib/python3.5/http/client.py", line 1103, in endheaders self._send_output(message_body) File "/usr/local/python3.5/lib/python3.5/http/client.py", line 934, in _send_output self.send(msg) File "/usr/local/python3.5/lib/python3.5/http/client.py", line 877, in send self.connect() File "/usr/local/python3.5/lib/python3.5/http/client.py", line 1253, in connect [06/14/2019, 07:45:59 AM] ERROR (mnist_AutoML/MainThread) <urlopen error [Errno -3] Temporary failure in name resolution> Traceback (most recent call last): File "/usr/local/python3.5/lib/python3.5/urllib/request.py", line 1254, in do_open h.request(req.get_method(), req.selector, req.data, headers) File "/usr/local/python3.5/lib/python3.5/http/client.py", line 1107, in request self._send_request(method, url, body, headers) File "/usr/local/python3.5/lib/python3.5/http/client.py", line 1152, in _send_request self.endheaders(body) File "/usr/local/python3.5/lib/python3.5/http/client.py", line 1103, in endheaders self._send_output(message_body) File "/usr/local/python3.5/lib/python3.5/http/client.py", line 934, in _send_output self.send(msg) File "/usr/local/python3.5/lib/python3.5/http/client.py", line 877, in send self.connect() File "/usr/local/python3.5/lib/python3.5/http/client.py", line 1253, in connect super().connect() File "/usr/local/python3.5/lib/python3.5/http/client.py", line 849, in connect (self.host,self.port), self.timeout, self.source_address) File "/usr/local/python3.5/lib/python3.5/socket.py", line 694, in create_connection for res in getaddrinfo(host, port, 0, SOCK_STREAM): File "/usr/local/python3.5/lib/python3.5/socket.py", line 733, in getaddrinfo for res in _socket.getaddrinfo(host, port, family, type, proto, flags): socket.gaierror: [Errno -3] Temporary failure in name resolution How can I solve this problem? Hi, this issue seems caused by http client connection error. Which image and example did you use in your experiment? — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or mute the thread.

Hi, sshKeyPath is the path of your ssh key file, it is a local path. You could set the path in your machineList field, refer https://github.com/microsoft/nni/blob/master/docs/en_US/Tutorial/ExperimentConfig.md#configuration-spec

**Comment by scarlett2018** [comment] 2019-08-30 08:12
@husimple - does @SparkSnail 's latest feedback help?

**Comment by ultmaster** [comment] 2019-10-20 05:45
No updates. Closing it for now. If there are further questions, you can reopen it.

**Closed by ultmaster** 2019-10-20 05:45 UTC
Labels: customer raised, question, waiting customer confirm
