### ISSUE TITLE
Dart mode or One-shot mode?

### ISSUE THREAD

**Issue by xuehui1991** [microsoft/nni#1521] opened 2019-09-04 06:15 UTC
**Short summary about the issue/question**:
https://github.com/microsoft/nni/blob/master/examples/trials/mnist-nas/darts_mode/config_darts.yml

![image](https://user-images.githubusercontent.com/6280746/64230099-60b5b380-cf1e-11e9-9cad-fa011033ec7e.png)

It's kind of confuse me about the title "config_darts.yml" but use "one-shot mode" inside.

**Brief what process you are following**: 

**How to reproduce it**: 

**nni Environment**:
- nni version:
- nni mode(local|pai|remote):
- OS:
- python version:
- is conda or virtualenv used?: 
- is running in docker?:

**need to update document(yes/no)**:

**Anything else we need to know**:

**Comment by thomasbkahn** [comment] 2019-11-26 20:55
Can a maintainer comment on whether this is indeed a bug or is it intended?

I'm running this example now and the results appear strange

**Comment by QuanluZhang** [comment] 2019-11-27 00:20
@thomasbkahn The previous NAS interface becomes deprecated, thus, the corresponding examples using this interface including this one will also become deprecated. The refactored NAS interface can be found here (https://github.com/microsoft/nni/tree/v1.2/docs/en_US/NAS). You could follow the document to reproduce enas, darts and pdarts. We are supporting more NAS algorithms following the new NAS interface.

BTW, the refactored NAS interface will be released in v1.2 on next Monday. If you want to try it now, you can install NNI from source code by following the instruction here (https://nni.readthedocs.io/en/latest/Tutorial/Installation.html).

**Closed** 2019-11-27 03:09 UTC
Labels: documentation
