### ISSUE TITLE
AMC + InceptionV3

### ISSUE THREAD

**Issue by dingguodong-826** [microsoft/nni#4185] opened 2021-09-15 07:30 UTC
Hello, I am pruning InceptionV3 with AMC and I have the following problem when doing amc_train.py.
![image](https://user-images.githubusercontent.com/57715990/133389853-81eb2306-9554-458c-bced-0ff232ab93cd.png)
The checkpoint I got from the search is here.
https://drive.google.com/drive/folders/16u_3hegWuH95kS22DJ1bD6ewXgdkZbV0?usp=sharing
Thank you for your help!

**Comment by scarlett2018** [comment] 2021-09-26 07:39
@J-shang @dingguodong-826  @zheng-ningxin - is this problem the same problem in https://github.com/microsoft/nni/issues/4030? is it more efficient to set up a quick debug call through Teams?

**Comment by zheng-ningxin** [comment] 2021-09-26 07:50
This problem is caused by pruning a layer to empty. I have supported this problem offline. If you meet any new problem, please update here @dingguodong-826, if not, please close this issue, thanks.

**Closed** 2021-09-26 08:48 UTC
Labels: customer raised, model compression, support
