### ISSUE TITLE
How to restart a failed trial?

### ISSUE THREAD

**Issue by diggerdu** [microsoft/nni#1731] opened 2019-11-12 07:51 UTC
**Short summary about the issue/question**:
The nni framework does not support rerun the trial after the trial failed occasionally. Sorry for posting here beacuse I can't find a forum for nni.
**Brief what process you are following**: 

**How to reproduce it**: 

**nni Environment**:
- nni version: 1.0
- nni mode(local|pai|remote): local
- OS: Ubuntu 16.04
- python version: 1.3
- is conda or virtualenv used?: no
- is running in docker?: no

**need to update document(yes/no)**: no

**Anything else we need to know**: no

**Comment by liuzhe-lz** [comment] 2019-11-12 08:34
I'm sorry but it's not supported in current version.
This feature will come in next release.

**Comment by liuzhe-lz** [comment] 2019-11-12 08:35
Duplicate of #1700

**Closed** 2019-11-12 08:35 UTC
Labels: customer raised
