### ISSUE TITLE
HPO experiment hyper-parameters page error.

### ISSUE THREAD

**Issue by crj1998** [microsoft/nni#5127] opened 2022-09-15 01:37 UTC
**Describe the issue**:
HPO experiment hyper-parameters page error.

[experiment.zip](https://github.com/microsoft/nni/files/9570986/experiment.zip)
**Environment**:
- NNI version:  dev
- Training service (local|remote|pai|aml|etc): local
- Client OS: Ubuntu 
- Server OS (for remote mode only): 
- Python version:  3.9.12
- PyTorch/TensorFlow version: pytorch 1.12.1
- Is conda/virtualenv/venv used?: yes
- Is running in Docker?: yes

**Configuration**:
 - Experiment config (remember to remove secrets!):
 - Search space:

**Log message**:
 - nnimanager.log:
 - dispatcher.log:
 - nnictl stdout and stderr:
 

**How to reproduce it?**:

**Comment by Lijiaoa** [comment] 2022-09-15 10:00
The problem is being followed up, and all data show normal, and the same type of experiment has not reproduced the problem. **ongoing operation.**

**Comment by Lijiaoa** [comment] 2022-10-19 02:07
hi @crj1998 Thanks for raising this bug. It's caused by the localstorage and had been fixed in PR #5145!

**Closed** 2022-10-20 02:30 UTC
Labels: v2.9.1
