### ISSUE TITLE
 I am a student of Tsinghua University, and I am very confused about the mistakes in using my own data training 

### ISSUE THREAD

**Issue by xianglei3** [microsoft/nni#2473] opened 2020-05-22 04:00 UTC
## NNI 学生项目问题概述 / General Question of Student Program

**请简要概述您的问题 / 观点 :**

the error is 
RuntimeError: Caught RuntimeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/torch/utils/data/_utils/worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "/usr/local/lib/python3.5/dist-packages/torch/utils/data/_utils/fetch.py", line 47, in fetch
    return self.collate_fn(data)
  File "/usr/local/lib/python3.5/dist-packages/torch/utils/data/_utils/collate.py", line 79, in default_collate
    return [default_collate(samples) for samples in transposed]
  File "/usr/local/lib/python3.5/dist-packages/torch/utils/data/_utils/collate.py", line 79, in <listcomp>
    return [default_collate(samples) for samples in transposed]
  File "/usr/local/lib/python3.5/dist-packages/torch/utils/data/_utils/collate.py", line 55, in default_collate
    return torch.stack(batch, 0, out=out)
RuntimeError: invalid argument 0: Sizes of tensors must match except in dimension 0. Got 128 and 146 in dimension 2 at /pytorch/aten/src/TH/generic/THTensor.cpp:612

**Short summary about the question / idea :**

**请提供 NNI 环境信息 :**
**nni Environment :**
- nni version:
- nni mode(local|pai|remote):
- OS:
- python version:
- is conda or virtualenv used?:
- is running in docker?:

## 其他建议 / Other Advice

**是否需要更新文档（是 / 否）:**
**Need to update document ( yes / no ) :**

**其他分享内容 :**
**Anything else we need to know :**

**Log message / 日志信息 :**
 - [nnimanager.log and dispatcher.log](https://github.com/microsoft/nni/blob/master/docs/en_US/Tutorial/HowToDebug.md#experiment-root-directory) : 

 - [nnictl stdout and stderr](https://github.com/microsoft/nni/blob/master/docs/en_US/Tutorial/Nnictl.md#nnictl%20log%20stdout) :

**Comment by chicm-ms** [comment] 2020-05-22 09:38
This seems a model tensor shape problem,  you can try to run it without nni to find the problem,  when the model code is correct, then tune it with nni.

**Comment by scarlett2018** [comment] 2020-06-23 08:12
Closing it as duplicate of #2472 , @xianglei3 feel free to reopen if it is a different problem.

**Closed by scarlett2018** 2020-06-23 08:12 UTC
Labels: duplicate
