### ISSUE TITLE
No information when submit a cutimized trial in WebUI

### ISSUE THREAD

**Issue by xuehui1991** [microsoft/nni#2009] opened 2020-02-07 02:19 UTC
![image](https://user-images.githubusercontent.com/6280746/73995347-41222b80-4993-11ea-8948-bb39f9dac7ab.png)

There happened an error when I trying to submit a customized trial in WebUI. But I don't know why and how to fix it. Can nni give more inforamtion?

**Short summary about the issue/question**:

**Brief what process you are following**: 

**How to reproduce it**: 

**nni Environment**:
- nni version:
- nni mode(local|pai|remote):
- OS:
- python version:
- is conda or virtualenv used?: 
- is running in docker?:

**need to update document(yes/no)**:

**Anything else we need to know**:

**Comment by scarlett2018** [comment] 2020-02-07 02:52
seems like a dupe of #1985

**Comment by kvartet** [comment] 2021-04-22 09:24
closing the issue as it is a duplicate issue

**Closed by kvartet** 2021-04-22 09:24 UTC
Labels: duplicate, nnidev
