### ISSUE TITLE
ERROR: Restful server start failed

### ISSUE THREAD

**Issue by SicleBoypy** [microsoft/nni#3516] opened 2021-04-08 03:25 UTC
一直报这个错误，nnictl create反复启动依然失败！

**Comment by SparkSnail** [comment] 2021-04-09 08:57
@acured to take a look.

**Comment by acured** [comment] 2021-04-09 09:02
Hi @SicleBoypy, 
Could you provide more details about this? For example, logs, screenshots, running environment, etc.

**Comment by SicleBoypy** [comment] 2021-04-09 09:49
> 
> 
> Hi @SicleBoypy,
> Could you provide more details about this? For example, logs, screenshots, running environment, etc.

Thanks you reply, it has been not succeeded in creating, so the log appears to be blank. And I dont get any infomation. For  environment:
conda env:
torch: 1.7.0+cu110
nni: 2.1

**Comment by acured** [comment] 2021-04-09 09:56
> > Hi @SicleBoypy,
> > Could you provide more details about this? For example, logs, screenshots, running environment, etc.
> 
> Thanks you reply, it has been not succeeded in creating, so the log appears to be blank. And I dont get any infomation. For environment:
> conda env:
> torch: 1.7.0+cu110
> nni: 2.1

Any message on terminal?

**Comment by SicleBoypy** [comment] 2021-04-09 09:59
> 
> 
> > > Hi @SicleBoypy,
> > > Could you provide more details about this? For example, logs, screenshots, running environment, etc.
> > 
> > 
> > Thanks you reply, it has been not succeeded in creating, so the log appears to be blank. And I dont get any infomation. For environment:
> > conda env:
> > torch: 1.7.0+cu110
> > nni: 2.1
> 
> Any message on terminal?

only info for this:

INFO:  expand searchSpacePath: search_space.json to /home/work/search_space.json 
INFO:  expand codeDir: . to /home/work/. 
INFO:  Starting restful server...
ERROR: Restful server start failed!
INFO:   Stdout:
-----------------------------------------------------------------------
                Experiment start time 2021-04-08 05:59:36
-----------------------------------------------------------------------




INFO:   Stderr:
-----------------------------------------------------------------------
                Experiment start time 2021-04-08 05:59:36
-----------------------------------------------------------------------

**Comment by acured** [comment] 2021-04-12 02:07
> > > > Hi @SicleBoypy,
> > > > Could you provide more details about this? For example, logs, screenshots, running environment, etc.
> > > 
> > > 
> > > Thanks you reply, it has been not succeeded in creating, so the log appears to be blank. And I dont get any infomation. For environment:
> > > conda env:
> > > torch: 1.7.0+cu110
> > > nni: 2.1
> > 
> > 
> > Any message on terminal?
> 
> only info for this:
> 
> ## INFO: expand searchSpacePath: search_space.json to /home/work/search_space.json
> INFO: expand codeDir: . to /home/work/.
> INFO: Starting restful server...
> ERROR: Restful server start failed!
> INFO: Stdout:
> ```
>             Experiment start time 2021-04-08 05:59:36
> ```
> 
> ## INFO: Stderr:
> ```
>             Experiment start time 2021-04-08 05:59:36
> ```

Hi @SicleBoypy , is there any log named "nnimanager.log" generated?  
If not you can have a try with launch the service part directly by using this cmd:
_"node.exe --max-old-space-size=4096 main.js --port 8080 --mode local --experiment_id <replace your id> --start_mode new --log_dir <replace your log dir>"_
Hope to get some useful information.

**Comment by SicleBoypy** [comment] 2021-04-12 03:24
> 
> 
> > > > > Hi @SicleBoypy,
> > > > > Could you provide more details about this? For example, logs, screenshots, running environment, etc.
> > > > 
> > > > 
> > > > Thanks you reply, it has been not succeeded in creating, so the log appears to be blank. And I dont get any infomation. For environment:
> > > > conda env:
> > > > torch: 1.7.0+cu110
> > > > nni: 2.1
> > > 
> > > 
> > > Any message on terminal?
> > 
> > 
> > only info for this:
> > ## INFO: expand searchSpacePath: search_space.json to /home/work/search_space.json
> > INFO: expand codeDir: . to /home/work/.
> > INFO: Starting restful server...
> > ERROR: Restful server start failed!
> > INFO: Stdout:
> > ```
> >             Experiment start time 2021-04-08 05:59:36
> > ```
> > 
> > 
> > ## INFO: Stderr:
> > ```
> >             Experiment start time 2021-04-08 05:59:36
> > ```
> 
> Hi @SicleBoypy , is there any log named "nnimanager.log" generated?
> If not you can have a try with launch the service part directly by using this cmd:
> _"node --max-old-space-size=4096 main.js --port 8080 --mode local --experiment_id 'replace your id' --start_mode new --log_dir 'replace your log dir'"_
> Hope to get some useful information.
I get nnimanager.log:
[2021-04-12 03:01:37] INFO [ 'Construct local machine training service.' ]
[2021-04-12 03:01:37] INFO [ 'Change NNIManager status from: INITIALIZED to: STOPPING' ]
[2021-04-12 03:01:37] INFO [ 'Stopping experiment, cleaning up ...' ]
[2021-04-12 03:01:37] ERROR [ 'Tuner has not been setup' ]
[2021-04-12 03:01:37] INFO [ 'Stopping local machine training service...' ]
[2021-04-12 03:01:38] INFO [ 'Datastore initialization done' ]
[2021-04-12 03:01:38] INFO [ 'RestServer start' ]
[2021-04-12 03:01:38] INFO [ 'RestServer base port is 8080' ]
[2021-04-12 03:01:38] INFO [ 'Rest server listening on: http://0.0.0.0:8080' ]
[2021-04-12 03:06:21] INFO [ 'Stopping experiment, cleaning up ...' ]
[2021-04-12 03:06:21] ERROR [ 'Tuner has not been setup' ]
[2021-04-12 03:06:21] INFO [ 'Stopping local machine training service...' ]
[2021-04-12 03:06:21] INFO [ 'Change NNIManager status from: STOPPING to: STOPPED' ]
[2021-04-12 03:06:21] INFO [ 'Experiment stopped.' ]
It seems that tuner has not been setup. How to solve it?

**Comment by acured** [comment] 2021-04-12 07:28
> > > > > > Hi @SicleBoypy,
> > > > > > Could you provide more details about this? For example, logs, screenshots, running environment, etc.
> > > > > 
> > > > > 
> > > > > Thanks you reply, it has been not succeeded in creating, so the log appears to be blank. And I dont get any infomation. For environment:
> > > > > conda env:
> > > > > torch: 1.7.0+cu110
> > > > > nni: 2.1
> > > > 
> > > > 
> > > > Any message on terminal?
> > > 
> > > 
> > > only info for this:
> > > ## INFO: expand searchSpacePath: search_space.json to /home/work/search_space.json
> > > INFO: expand codeDir: . to /home/work/.
> > > INFO: Starting restful server...
> > > ERROR: Restful server start failed!
> > > INFO: Stdout:
> > > ```
> > >             Experiment start time 2021-04-08 05:59:36
> > > ```
> > > 
> > > 
> > > ## INFO: Stderr:
> > > ```
> > >             Experiment start time 2021-04-08 05:59:36
> > > ```
> > 
> > 
> > Hi @SicleBoypy , is there any log named "nnimanager.log" generated?
> > If not you can have a try with launch the service part directly by using this cmd:
> > _"node --max-old-space-size=4096 main.js --port 8080 --mode local --experiment_id 'replace your id' --start_mode new --log_dir 'replace your log dir'"_
> > Hope to get some useful information.
> > I get nnimanager.log:
> > [2021-04-12 03:01:37] INFO [ 'Construct local machine training service.' ]
> > [2021-04-12 03:01:37] INFO [ 'Change NNIManager status from: INITIALIZED to: STOPPING' ]
> > [2021-04-12 03:01:37] INFO [ 'Stopping experiment, cleaning up ...' ]
> > [2021-04-12 03:01:37] ERROR [ 'Tuner has not been setup' ]
> > [2021-04-12 03:01:37] INFO [ 'Stopping local machine training service...' ]
> > [2021-04-12 03:01:38] INFO [ 'Datastore initialization done' ]
> > [2021-04-12 03:01:38] INFO [ 'RestServer start' ]
> > [2021-04-12 03:01:38] INFO [ 'RestServer base port is 8080' ]
> > [2021-04-12 03:01:38] INFO [ 'Rest server listening on: http://0.0.0.0:8080' ]
> > [2021-04-12 03:06:21] INFO [ 'Stopping experiment, cleaning up ...' ]
> > [2021-04-12 03:06:21] ERROR [ 'Tuner has not been setup' ]
> > [2021-04-12 03:06:21] INFO [ 'Stopping local machine training service...' ]
> > [2021-04-12 03:06:21] INFO [ 'Change NNIManager status from: STOPPING to: STOPPED' ]
> > [2021-04-12 03:06:21] INFO [ 'Experiment stopped.' ]
> > It seems that tuner has not been setup. How to solve it?

Looks like you need to setup tuner first. Ref here : https://nni.readthedocs.io/en/latest/Tuner/BuiltinTuner.html

**Comment by acured** [comment] 2021-04-14 01:44
Hi @SicleBoypy , any update?

**Comment by SicleBoypy** [comment] 2021-04-14 02:37
> 
> 
> > > > > > > Hi @SicleBoypy,
> > > > > > > Could you provide more details about this? For example, logs, screenshots, running environment, etc.
> > > > > > 
> > > > > > 
> > > > > > Thanks you reply, it has been not succeeded in creating, so the log appears to be blank. And I dont get any infomation. For environment:
> > > > > > conda env:
> > > > > > torch: 1.7.0+cu110
> > > > > > nni: 2.1
> > > > > 
> > > > > 
> > > > > Any message on terminal?
> > > > 
> > > > 
> > > > only info for this:
> > > > ## INFO: expand searchSpacePath: search_space.json to /home/work/search_space.json
> > > > INFO: expand codeDir: . to /home/work/.
> > > > INFO: Starting restful server...
> > > > ERROR: Restful server start failed!
> > > > INFO: Stdout:
> > > > ```
> > > >             Experiment start time 2021-04-08 05:59:36
> > > > ```
> > > > 
> > > > 
> > > > ## INFO: Stderr:
> > > > ```
> > > >             Experiment start time 2021-04-08 05:59:36
> > > > ```
> > > 
> > > 
> > > Hi @SicleBoypy , is there any log named "nnimanager.log" generated?
> > > If not you can have a try with launch the service part directly by using this cmd:
> > > _"node --max-old-space-size=4096 main.js --port 8080 --mode local --experiment_id 'replace your id' --start_mode new --log_dir 'replace your log dir'"_
> > > Hope to get some useful information.
> > > I get nnimanager.log:
> > > [2021-04-12 03:01:37] INFO [ 'Construct local machine training service.' ]
> > > [2021-04-12 03:01:37] INFO [ 'Change NNIManager status from: INITIALIZED to: STOPPING' ]
> > > [2021-04-12 03:01:37] INFO [ 'Stopping experiment, cleaning up ...' ]
> > > [2021-04-12 03:01:37] ERROR [ 'Tuner has not been setup' ]
> > > [2021-04-12 03:01:37] INFO [ 'Stopping local machine training service...' ]
> > > [2021-04-12 03:01:38] INFO [ 'Datastore initialization done' ]
> > > [2021-04-12 03:01:38] INFO [ 'RestServer start' ]
> > > [2021-04-12 03:01:38] INFO [ 'RestServer base port is 8080' ]
> > > [2021-04-12 03:01:38] INFO [ 'Rest server listening on: http://0.0.0.0:8080' ]
> > > [2021-04-12 03:06:21] INFO [ 'Stopping experiment, cleaning up ...' ]
> > > [2021-04-12 03:06:21] ERROR [ 'Tuner has not been setup' ]
> > > [2021-04-12 03:06:21] INFO [ 'Stopping local machine training service...' ]
> > > [2021-04-12 03:06:21] INFO [ 'Change NNIManager status from: STOPPING to: STOPPED' ]
> > > [2021-04-12 03:06:21] INFO [ 'Experiment stopped.' ]
> > > It seems that tuner has not been setup. How to solve it?
> 
> Looks like you need to setup tuner first. Ref here : https://nni.readthedocs.io/en/latest/Tuner/BuiltinTuner.html

I only use the  Tuner of TPE, and set up nni by "pip install nni". See the doc，there is no problem for installation. If not, I
 will not succeed in sometimes, but fail in all the time.

**Comment by acured** [comment] 2021-04-15 05:40
> > > > > > > > Hi @SicleBoypy,
> > > > > > > > Could you provide more details about this? For example, logs, screenshots, running environment, etc.
> > > > > > > 
> > > > > > > 
> > > > > > > Thanks you reply, it has been not succeeded in creating, so the log appears to be blank. And I dont get any infomation. For environment:
> > > > > > > conda env:
> > > > > > > torch: 1.7.0+cu110
> > > > > > > nni: 2.1
> > > > > > 
> > > > > > 
> > > > > > Any message on terminal?
> > > > > 
> > > > > 
> > > > > only info for this:
> > > > > ## INFO: expand searchSpacePath: search_space.json to /home/work/search_space.json
> > > > > INFO: expand codeDir: . to /home/work/.
> > > > > INFO: Starting restful server...
> > > > > ERROR: Restful server start failed!
> > > > > INFO: Stdout:
> > > > > ```
> > > > >             Experiment start time 2021-04-08 05:59:36
> > > > > ```
> > > > > 
> > > > > 
> > > > > ## INFO: Stderr:
> > > > > ```
> > > > >             Experiment start time 2021-04-08 05:59:36
> > > > > ```
> > > > 
> > > > 
> > > > Hi @SicleBoypy , is there any log named "nnimanager.log" generated?
> > > > If not you can have a try with launch the service part directly by using this cmd:
> > > > _"node --max-old-space-size=4096 main.js --port 8080 --mode local --experiment_id 'replace your id' --start_mode new --log_dir 'replace your log dir'"_
> > > > Hope to get some useful information.
> > > > I get nnimanager.log:
> > > > [2021-04-12 03:01:37] INFO [ 'Construct local machine training service.' ]
> > > > [2021-04-12 03:01:37] INFO [ 'Change NNIManager status from: INITIALIZED to: STOPPING' ]
> > > > [2021-04-12 03:01:37] INFO [ 'Stopping experiment, cleaning up ...' ]
> > > > [2021-04-12 03:01:37] ERROR [ 'Tuner has not been setup' ]
> > > > [2021-04-12 03:01:37] INFO [ 'Stopping local machine training service...' ]
> > > > [2021-04-12 03:01:38] INFO [ 'Datastore initialization done' ]
> > > > [2021-04-12 03:01:38] INFO [ 'RestServer start' ]
> > > > [2021-04-12 03:01:38] INFO [ 'RestServer base port is 8080' ]
> > > > [2021-04-12 03:01:38] INFO [ 'Rest server listening on: http://0.0.0.0:8080' ]
> > > > [2021-04-12 03:06:21] INFO [ 'Stopping experiment, cleaning up ...' ]
> > > > [2021-04-12 03:06:21] ERROR [ 'Tuner has not been setup' ]
> > > > [2021-04-12 03:06:21] INFO [ 'Stopping local machine training service...' ]
> > > > [2021-04-12 03:06:21] INFO [ 'Change NNIManager status from: STOPPING to: STOPPED' ]
> > > > [2021-04-12 03:06:21] INFO [ 'Experiment stopped.' ]
> > > > It seems that tuner has not been setup. How to solve it?
> > 
> > 
> > Looks like you need to setup tuner first. Ref here : https://nni.readthedocs.io/en/latest/Tuner/BuiltinTuner.html
> 
> I only use the Tuner of TPE, and set up nni by "pip install nni". See the doc，there is no problem for installation. If not, I
> will not succeed in sometimes, but fail in all the time.

Hi @SicleBoypy,  Any message on "dispatcher.log"?

**Comment by SicleBoypy** [comment] 2021-04-15 06:22
> 
> 
> > > > > > > > > Hi @SicleBoypy,
> > > > > > > > > Could you provide more details about this? For example, logs, screenshots, running environment, etc.
> > > > > > > > 
> > > > > > > > 
> > > > > > > > Thanks you reply, it has been not succeeded in creating, so the log appears to be blank. And I dont get any infomation. For environment:
> > > > > > > > conda env:
> > > > > > > > torch: 1.7.0+cu110
> > > > > > > > nni: 2.1
> > > > > > > 
> > > > > > > 
> > > > > > > Any message on terminal?
> > > > > > 
> > > > > > 
> > > > > > only info for this:
> > > > > > ## INFO: expand searchSpacePath: search_space.json to /home/work/search_space.json
> > > > > > INFO: expand codeDir: . to /home/work/.
> > > > > > INFO: Starting restful server...
> > > > > > ERROR: Restful server start failed!
> > > > > > INFO: Stdout:
> > > > > > ```
> > > > > >             Experiment start time 2021-04-08 05:59:36
> > > > > > ```
> > > > > > 
> > > > > > 
> > > > > > ## INFO: Stderr:
> > > > > > ```
> > > > > >             Experiment start time 2021-04-08 05:59:36
> > > > > > ```
> > > > > 
> > > > > 
> > > > > Hi @SicleBoypy , is there any log named "nnimanager.log" generated?
> > > > > If not you can have a try with launch the service part directly by using this cmd:
> > > > > _"node --max-old-space-size=4096 main.js --port 8080 --mode local --experiment_id 'replace your id' --start_mode new --log_dir 'replace your log dir'"_
> > > > > Hope to get some useful information.
> > > > > I get nnimanager.log:
> > > > > [2021-04-12 03:01:37] INFO [ 'Construct local machine training service.' ]
> > > > > [2021-04-12 03:01:37] INFO [ 'Change NNIManager status from: INITIALIZED to: STOPPING' ]
> > > > > [2021-04-12 03:01:37] INFO [ 'Stopping experiment, cleaning up ...' ]
> > > > > [2021-04-12 03:01:37] ERROR [ 'Tuner has not been setup' ]
> > > > > [2021-04-12 03:01:37] INFO [ 'Stopping local machine training service...' ]
> > > > > [2021-04-12 03:01:38] INFO [ 'Datastore initialization done' ]
> > > > > [2021-04-12 03:01:38] INFO [ 'RestServer start' ]
> > > > > [2021-04-12 03:01:38] INFO [ 'RestServer base port is 8080' ]
> > > > > [2021-04-12 03:01:38] INFO [ 'Rest server listening on: http://0.0.0.0:8080' ]
> > > > > [2021-04-12 03:06:21] INFO [ 'Stopping experiment, cleaning up ...' ]
> > > > > [2021-04-12 03:06:21] ERROR [ 'Tuner has not been setup' ]
> > > > > [2021-04-12 03:06:21] INFO [ 'Stopping local machine training service...' ]
> > > > > [2021-04-12 03:06:21] INFO [ 'Change NNIManager status from: STOPPING to: STOPPED' ]
> > > > > [2021-04-12 03:06:21] INFO [ 'Experiment stopped.' ]
> > > > > It seems that tuner has not been setup. How to solve it?
> > > 
> > > 
> > > Looks like you need to setup tuner first. Ref here : https://nni.readthedocs.io/en/latest/Tuner/BuiltinTuner.html
> > 
> > 
> > I only use the Tuner of TPE, and set up nni by "pip install nni". See the doc，there is no problem for installation. If not, I
> > will not succeed in sometimes, but fail in all the time.
> 
> Hi @SicleBoypy, Any message on "dispatcher.log"?

There is no “"dispatcher.log”  to generate, And I try to again , and find the info in "nnictl_stderr.log":
(node:40346) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'run' of undefined
    at SqlDB.storeExperimentProfile (/home/work/.conda/envs/torch-3090/lib/python3.7/site-packages/nni_node/core/sqlDatabase.js:111:17)
    at NNIDataStore.storeExperimentProfile (/home/work/.conda/envs/torch-3090/lib/python3.7/site-packages/nni_node/core/nniDataStore.js:49:27)
    at NNIManager.storeExperimentProfile (/home/work/.conda/envs/torch-3090/lib/python3.7/site-packages/nni_node/core/nnimanager.js:518:31)
    at NNIManager.stopExperimentBottomHalf (/home/work/.conda/envs/torch-3090/lib/python3.7/site-packages/nni_node/core/nnimanager.js:250:20)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:40346) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:40346) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
~

**Comment by acured** [comment] 2021-04-15 07:12
Hi @SicleBoypy , looks like there are difference issues in your experiment(tuner issue and storage issue).
Could you have a try with a new(pure) env to start the experiment just in case those issue are not caused by current some env setting.

**Comment by SicleBoypy** [comment] 2021-04-15 07:27
> 
> 
> Hi @SicleBoypy , looks like there are difference issues in your experiment(tuner issue and storage issue).
> Could you have a try with a new(pure) env to start the experiment just in case those issues are not caused by current env setting.

I have not changed any , "nnimanager.log“ ：
[2021-04-15 06:11:46] INFO [ 'Construct local machine training service.' ]
[2021-04-15 06:11:46] INFO [ 'Change NNIManager status from: INITIALIZED to: STOPPING' ]
[2021-04-15 06:11:46] INFO [ 'Stopping experiment, cleaning up ...' ]
[2021-04-15 06:11:46] ERROR [ 'Tuner has not been setup' ]
[2021-04-15 06:11:46] INFO [ 'Stopping local machine training service...' ]
[2021-04-15 06:11:47] INFO [ 'Datastore initialization done' ]
[2021-04-15 06:11:47] INFO [ 'RestServer start' ]
[2021-04-15 06:11:47] INFO [ 'RestServer base port is 8080' ]
[2021-04-15 06:11:47] INFO [ 'Rest server listening on: http://0.0.0.0:8080' ]

and "nnictl_stder.log":
-----------------------------------------------------------------------
                Experiment start time 2021-04-15 06:11:10
-----------------------------------------------------------------------
(node:40346) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'run' of undefined
    at SqlDB.storeExperimentProfile (/home/work/.conda/envs/torch-3090/lib/python3.7/site-packages/nni_node/core/sqlDatabase.js:111:17)
    at NNIDataStore.storeExperimentProfile (/home/work/.conda/envs/torch-3090/lib/python3.7/site-packages/nni_node/core/nniDataStore.js:49:27)
    at NNIManager.storeExperimentProfile (/home/work/.conda/envs/torch-3090/lib/python3.7/site-packages/nni_node/core/nnimanager.js:518:31)
    at NNIManager.stopExperimentBottomHalf (/home/work/.conda/envs/torch-3090/lib/python3.7/site-packages/nni_node/core/nnimanager.js:250:20)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:40346) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:40346) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

and "nnictl_stdout.log":
-----------------------------------------------------------------------
                Experiment start time 2021-04-15 06:11:10
-----------------------------------------------------------------------

The 3 files in same directory. According to the time in log, it happned in same time.

**Comment by acured** [comment] 2021-04-15 07:46
Your right, but "Cannot read property 'run' of undefined" was not appears in the previous "nnictl_stder.log".

**Comment by acured** [comment] 2021-04-16 06:11
Hi @SicleBoypy , Have you try experiment on any new env?

**Comment by scarlett2018** [comment] 2021-06-10 01:20
> Hi @SicleBoypy , Have you try experiment on any new env?

@SicleBoypy - Has the problem been solved?

**Comment by JuAobo** [comment] 2021-08-20 07:30
@acured I also got the problem on windows10, any suggestion for solving this?

(base) PS D:\code> nnictl create --config nni\examples\trials\mnist-pytorch\config_windows.yml
INFO:  expand searchSpacePath: search_space.json to D:\code\nni\examples\trials\mnist-pytorch\search_space.json
INFO:  expand codeDir: . to D:\code\nni\examples\trials\mnist-pytorch\.
INFO:  Starting restful server...
ERROR: Restful server start failed!
INFO:   Stdout:
-----------------------------------------------------------------------
                Experiment start time 2021-08-20 15:21:34
-----------------------------------------------------------------------




INFO:   Stderr:
-----------------------------------------------------------------------
                Experiment start time 2021-08-20 15:21:34
-----------------------------------------------------------------------
Failed to create log dir: RangeError: Invalid time value
    at Date.toISOString (<anonymous>)
    at Logger.log (d:\code\anaconda\lib\site-packages\nni_node\common\log.js:54:72)
    at Logger.error (d:\code\anaconda\lib\site-packages\nni_node\common\log.js:41:14)
    at d:\code\anaconda\lib\site-packages\nni_node\main.js:109:33

Traceback (most recent call last):
  File "d:\code\anaconda\lib\site-packages\psutil\_pswindows.py", line 707, in wrapper
    return fun(self, *args, **kwargs)
  File "d:\code\anaconda\lib\site-packages\psutil\_pswindows.py", line 954, in create_time
    return cext.proc_create_time(self.pid)
ProcessLookupError: [Errno 3] No such process

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "d:\code\anaconda\lib\site-packages\psutil\__init__.py", line 474, in _init
    self.create_time()
  File "d:\code\anaconda\lib\site-packages\psutil\__init__.py", line 824, in create_time
    self._create_time = self._proc.create_time()
  File "d:\code\anaconda\lib\site-packages\psutil\_pswindows.py", line 709, in wrapper
    raise convert_oserror(err, pid=self.pid, name=self._name)
psutil.NoSuchProcess: psutil.NoSuchProcess process no longer exists (pid=13388)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "d:\code\anaconda\lib\site-packages\nni\tools\nnictl\launcher.py", line 432, in launch_experiment
    kill_command(rest_process.pid)
  File "d:\code\anaconda\lib\site-packages\nni\tools\nnictl\command_utils.py", line 37, in kill_command
    process = psutil.Process(pid=pid)
  File "d:\code\anaconda\lib\site-packages\psutil\__init__.py", line 447, in __init__
    self._init(pid)
  File "d:\code\anaconda\lib\site-packages\psutil\__init__.py", line 487, in _init
    raise NoSuchProcess(pid, None, msg)
psutil.NoSuchProcess: psutil.NoSuchProcess no process found with pid 13388

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "d:\code\anaconda\lib\site-packages\nni\tools\nnictl\launcher.py", line 525, in create_experiment
    launch_experiment(args, config_v2, 'new', experiment_id, 2)
  File "d:\code\anaconda\lib\site-packages\nni\tools\nnictl\launcher.py", line 434, in launch_experiment
    raise Exception(ERROR_INFO % 'Rest server stopped!')
TypeError: not all arguments converted during string formatting

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "d:\code\anaconda\lib\site-packages\psutil\_pswindows.py", line 707, in wrapper
    return fun(self, *args, **kwargs)
  File "d:\code\anaconda\lib\site-packages\psutil\_pswindows.py", line 954, in create_time
    return cext.proc_create_time(self.pid)
ProcessLookupError: [Errno 3] No such process

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "d:\code\anaconda\lib\site-packages\psutil\__init__.py", line 474, in _init
    self.create_time()
  File "d:\code\anaconda\lib\site-packages\psutil\__init__.py", line 824, in create_time
    self._create_time = self._proc.create_time()
  File "d:\code\anaconda\lib\site-packages\psutil\_pswindows.py", line 709, in wrapper
    raise convert_oserror(err, pid=self.pid, name=self._name)
psutil.NoSuchProcess: psutil.NoSuchProcess process no longer exists (pid=13388)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "d:\code\anaconda\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "d:\code\anaconda\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\code\Anaconda\Scripts\nnictl.exe\__main__.py", line 7, in <module>
  File "d:\code\anaconda\lib\site-packages\nni\tools\nnictl\nnictl.py", line 290, in parse_args
    args.func(args)
  File "d:\code\anaconda\lib\site-packages\nni\tools\nnictl\launcher.py", line 529, in create_experiment
    kill_command(restServerPid)
  File "d:\code\anaconda\lib\site-packages\nni\tools\nnictl\command_utils.py", line 37, in kill_command
    process = psutil.Process(pid=pid)
  File "d:\code\anaconda\lib\site-packages\psutil\__init__.py", line 447, in __init__
    self._init(pid)
  File "d:\code\anaconda\lib\site-packages\psutil\__init__.py", line 487, in _init
    raise NoSuchProcess(pid, None, msg)
psutil.NoSuchProcess: psutil.NoSuchProcess no process found with pid 13388

**Comment by AkshayRoyal** [comment] 2021-08-28 08:12
I am also getting the same error while trying to run nni on remote server

My logs look like this

nnimanager.log
```
[2021-08-28 13:33:06] INFO [ 'Datastore initialization done' ]
[2021-08-28 13:33:06] INFO [ 'RestServer start' ]
[2021-08-28 13:33:06] INFO [ 'RestServer base port is 8091' ]
[2021-08-28 13:33:06] INFO [ 'Rest server listening on: http://0.0.0.0:8091' ]
[2021-08-28 13:33:25] INFO [ 'Change NNIManager status from: INITIALIZED to: STOPPING' ]
```
nnnictl_stderr.log

```
-----------------------------------------------------------------------
                Experiment start time 2021-08-28 13:33:05
-----------------------------------------------------------------------
(node:13544) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'id' of undefined
    at NNIManager.setStatus (/home/maths/integrated/mt6130583/anaconda3/envs/ds/lib/python3.9/site-packages/nni_node/core/nnimanager.js:700:77)
    at NNIManager.stopExperimentTopHalf (/home/maths/integrated/mt6130583/anaconda3/envs/ds/lib/python3.9/site-packages/nni_node/core/nnimanager.js:223:14)
    at NNIManager.stopExperiment (/home/maths/integrated/mt6130583/anaconda3/envs/ds/lib/python3.9/site-packages/nni_node/core/nnimanager.js:219:20)
    at process.cleanUp (/home/maths/integrated/mt6130583/anaconda3/envs/ds/lib/python3.9/site-packages/nni_node/main.js:126:38)
    at process.emit (events.js:203:15)
(node:13544) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:13544) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

nnictl_stdout.log is blank

I have tried this on nniv2.2 and nniv2.3

I got this error while trying to run examples/trials/mnist-tfv2

My config_remote.yml file looks like this
```
authorName: default
experimentName: example_mnist
trialConcurrency: 1
maxExecDuration: 1h
maxTrialNum: 10
nniManagerIp: xx.xx.xx.xx
#choice: local, remote, pai
trainingServicePlatform: remote
searchSpacePath: search_space.json
#choice: true, false
useAnnotation: false
tuner:
  #choice: TPE, Random, Anneal, Evolution, BatchTuner, MetisTuner
  #SMAC (SMAC should be installed through nnictl)
  builtinTunerName: TPE
  classArgs:
    #choice: maximize, minimize
    optimize_mode: maximize
trial:
  command: python3 mnist.py
  codeDir: .
  gpuNum: 0
#machineList can be empty if the platform is local
machineList:
  - ip: ${hpc.iitd.ac.in}
    username: ${xx}
    sshKeyPath: ~/mycerts/xx.key
    # Below are examples of specifying python environment.
    # pythonPath: /opt/python3.7/bin
    # pythonPath: C:/Python37
    # Below is an example of specifying python environment for windows anaconda user. Multiple paths separated by ';'. 
    # pythonPath: C:/Users/yourname/.conda/envs/myenv;C:/Users/yourname/.conda/envs/myenv/Scripts;C:/Users/yourname/.conda/envs/myenv/Library/bin
    pythonPath: ${~/anaconda3/envs/ds/bin/python}

```

**Comment by scarlett2018** [comment] 2022-08-15 08:33
Adding this month's scrum master @ultmaster - who can take a look at this issue? seems there are 2 more users hit it.

**Comment by scarlett2018** [comment] 2022-09-07 02:58
Closing as overdue. We had done a set of server side log improvement in the recent releases and also has plan to further improve  the logs in coming 3.0 release.

**Closed by scarlett2018** 2022-09-07 02:58 UTC
Labels: customer raised, support
