### ISSUE TITLE
Any example of distributed RL?

### ISSUE THREAD

**Issue by forhonourlx** [microsoft/nni#1912] opened 2020-01-01 11:27 UTC
Hi, 
Is there any example of distributed RL?
Thanks in advance.

**Comment by QuanluZhang** [comment] 2020-01-02 00:59
@forhonourlx thanks for asking. The framework of NNI can be used to support distributed RL. Specifically, [tuner](https://github.com/microsoft/nni/blob/master/docs/en_US/Tuner/CustomizeTuner.md) could act as, for example, policy network. While [trials](https://github.com/microsoft/nni/blob/master/docs/en_US/TrialExample/Trials.md) could be the episodes. NNI by design runs trials in parallel on various platforms.

We currently don't have examples for classic RL tasks, for example, atari games. But we do have an example for distributed RL (not a pure example though), we use PPO algorithm to tune neural architectures in a distributed manner. You can refer to [here](https://github.com/microsoft/nni/tree/master/src/sdk/pynni/nni/ppo_tuner) for [the PPO algorithm](https://github.com/microsoft/nni/blob/master/docs/en_US/Tuner/PPOTuner.md), and the corresponding trial example can be found [here](https://github.com/microsoft/nni/tree/master/examples/nas/classic_nas). This is for NAS scenario, maybe not easy to understand, a simple example for distributed RL could be provided in future.

**Comment by scarlett2018** [comment] 2020-01-02 10:43
@forhonourlx thanks for raising the question, I'm closing the issue as the question has been answered in the above comment. please feel free to raise more questions whenever needed.

**Closed by scarlett2018** 2020-01-02 10:43 UTC
Labels: customer raised, question
