### ISSUE TITLE
[macOS] nnictl: command not found

### ISSUE THREAD

**Issue by blakete** [microsoft/nni#1661] opened 2019-10-29 02:47 UTC
**Short summary about the issue/question**:
I  am running into an error where the 'nnictl' command is not found after installing nni via pip3. 

**Brief what process you are following**: 
I  am following the Mac/Linux install instructions from the official documentation (https://github.com/Microsoft/nni/) and am unable to run the nnictl command even after the package is installed.

- Operating type: initial deployment
- Brief what deployment process you are following 

**nni Environment**: 
- nni version: 1.1
- nni mode(local|pai|remote): local
- OS: macOS Catalina
- python version: 3.6
- is conda or virtualenv used?: virtualenv and tried installing locally outside virtual env.
- is running in docker?: no

**Anything else we need to know**:
I  need to be able to use NNI to run my NN experiments. Hoping to hear back from someone soon!

**Comment by SparkSnail** [comment] 2019-11-04 02:05
Hi @blakeedwards823, could you try `which nnictl` in command line to see if nnictl is installed in machine?

**Comment by scarlett2018** [comment] 2020-01-31 14:59
@SparkSnail - I hit the same problem for NNI 1.3, python 3.6.9, windows' ubuntu 18 app.

**Comment by scarlett2018** [comment] 2020-01-31 15:24
> @SparkSnail - I hit the same problem for NNI 1.3, python 3.6.9, windows' ubuntu 18 app.
> 
> I tried `which nnictl`, it returns nothing.

The problem is fixed after I restart the console.

**Comment by scarlett2018** [comment] 2020-01-31 15:27
> Hi @blakeedwards823, could you try `which nnictl` in command line to see if nnictl is installed in machine?

@blakeedwards823 - are you still seeing the problem? may you kindly responds? we will close overdue issues with no responds over months. thanks for the support.

**Comment by scarlett2018** [comment] 2020-04-28 03:07
Closing the issue as we are not able to reproduce and there are no more info feedback from @blaketeedwards823 (feel free to reopen if you are still able to reproduce it, thanks.)

**Closed by scarlett2018** 2020-04-28 03:07 UTC
Labels: cannot reproduce, customer raised, installation, macOS, tobe-overdued, waiting customer confirm
