### ISSUE TITLE
mnist-pytorch error

### ISSUE THREAD

**Issue by xiaokaioneone** [microsoft/nni#4514] opened 2022-01-26 14:27 UTC
{"error":"File not found: C:\\Users\\Zhengxiaokai\\nni-experiments\\upef940d\\trials\\TaGue\\trial.log"}

**Comment by J-shang** [comment] 2022-02-07 03:28
Hi @xiaokaioneone , could you describe more detailed information about this issue? Which config did you use and how did you find this error?

**Comment by scarlett2018** [comment] 2022-03-18 09:01
> Hi @xiaokaioneone , could you describe more detailed information about this issue? Which config did you use and how did you find this error?

@xiaokaioneone - we can not help to narrow down the root cause till you provide more context. Please help to answer the above questions, thanks.

**Comment by scarlett2018** [comment] 2022-04-06 03:31
Closing the issue as overdue as it has no responds for a while, feel free to reopen if you are still seeing the problem on your side.

**Closed by scarlett2018** 2022-04-06 03:31 UTC
Labels: waiting customer confirm, support, close-as-overdue

**Comment by xiaokaioneone** [comment] 2022-04-06 06:01
我的是win10系统，需要把源码里面的一个python3改为python

**Comment by xiaokaioneone** [comment] 2022-04-06 06:02
> 关闭该问题，因为它有一段时间没有响应，如果您仍然看到问题在您身边，请随时重新打开。

我是win10系统，需要把源码里面的一个python3改为python
