### ISSUE TITLE
prunning model using dependency_aware=True and multiple inputs 

### ISSUE THREAD

**Issue by zccyman** [microsoft/nni#3372] opened 2021-02-08 08:08 UTC
**Environment**:
- NNI version: v2.0
- NNI mode (local|remote|pai):
- Client OS:
- Server OS (for remote mode only):
- Python version: 3.7
- PyTorch/TensorFlow version: 1.6.0
- Is conda/virtualenv/venv used?: Yes
- Is running in Docker?: Yes

**Log message**:
 - nnimanager.log: 
 - dispatcher.log:
 - nnictl stdout and stderr:
 

**What issue meet, what's expected?**:
prunning model using dependency_aware=True and multiple inputs 
````
Enable the dependency_aware mode
Traceback (most recent call last):
  File "train.py", line 226, in <module>
    pruner = create_pruner(model, pruner_name, optimizer, dependency_aware, dummy_input=(f1, f2, x_h, x_o))
  File "train.py", line 163, in create_pruner
    pruner = pruner_class(model, config_list, optimizer, **kw_args)
  File "/root/anaconda3/envs/python3.7/lib/python3.7/site-packages/nni/algorithms/compression/pytorch/pruning/one_shot.py", line 292, in __init__
    dependency_aware=dependency_aware, dummy_input=dummy_input)
  File "/root/anaconda3/envs/python3.7/lib/python3.7/site-packages/nni/algorithms/compression/pytorch/pruning/one_shot.py", line 167, in __init__
    self.graph = TorchModuleGraph(model, dummy_input)
  File "/root/anaconda3/envs/python3.7/lib/python3.7/site-packages/nni/common/graph_utils.py", line 251, in __init__
    self._extract_auxiliary_info()
  File "/root/anaconda3/envs/python3.7/lib/python3.7/site-packages/nni/common/graph_utils.py", line 774, in _extract_auxiliary_info
    node_group, cpp_node)
  File "/root/anaconda3/envs/python3.7/lib/python3.7/site-packages/nni/common/graph_utils.py", line 444, in _extract_cat_info
    input_order.append(self.output_to_node[debug_name].unique_name)
KeyError: 'f1'
````

**How to reproduce it?**: 

````
class RRN(nn.Module):
    def __init__(self):
        super(RRN, self).__init__()

        self.SRnet = rrn(scale=2, n_c=128, n_b=10)

    def forward(self, f1, f2, x_h, x_o):
        x_h, x_o = self.SRnet(f1, f2, x_h, x_o)
        
        return x_h, x_o

def create_pruner(model, pruner_name, optimizer=None, dependency_aware=False, dummy_input=None):
    pruner_class = prune_config[pruner_name]['pruner_class']
    config_list = prune_config[pruner_name]['config_list']
    kw_args = {}
    if dependency_aware:
        print('Enable the dependency_aware mode')
        # note that, not all pruners support the dependency_aware mode
        kw_args['dependency_aware'] = True
        kw_args['dummy_input'] = dummy_input
    pruner = pruner_class(model, config_list, optimizer, **kw_args)
    return pruner

prune_config = {
    'l1filter': {
        'pruner_class': L1FilterPruner,
        'config_list': [{
            'sparsity': 0.25,
            'op_types': ['Conv2d'],
        }]
    },
}

model = RRN()
pruner_name = "l1filter"
pruner = create_pruner(model, pruner_name, optimizer, dependency_aware=True, dummy_input=(f1, f2, x_h, x_o))
model = pruner.compress()
````

**Additional information**:

**Comment by zheng-ningxin** [comment] 2021-02-20 12:06
Thanks for the feedback! looks like it fails when create the model graph based on `torch.jit` (Note: torch.jit.trace does not support the value-dependent models, reference [jit.trace](https://pytorch.org/docs/stable/generated/torch.jit.trace.html) for more information ). I need the definition of `rrn` to reproduce this problem, could you please show the code snippet of the `rrn`? Thanks?

**Comment by zccyman** [comment] 2021-02-22 02:05
> Thanks for the feedback! looks like it fails when create the model graph based on `torch.jit` (Note: torch.jit.trace does not support the value-dependent models, reference [jit.trace](https://pytorch.org/docs/stable/generated/torch.jit.trace.html) for more information ). I need the definition of `rrn` to reproduce this problem, could you please show the code snippet of the `rrn`? Thanks?

````
from __future__ import absolute_import
import torch
import torch.nn as nn
from torch.nn import functional as F
from torch.autograd import Variable
import torchvision
from torch.nn import init
import numpy as np
import functools

def make_layer(block, n_layers):
    layers = []
    for _ in range(n_layers):
        layers.append(block())
    return nn.Sequential(*layers)

class ResidualBlock_noBN(nn.Module):
    '''Residual block w/o BN
    ---Conv-ReLU-Conv-+-
     |________________|
    '''
    def __init__(self, nf=64):
        super(ResidualBlock_noBN, self).__init__()
        self.conv1 = nn.Conv2d(nf, nf, 3, 1, 1, bias=True)
        self.conv2 = nn.Conv2d(nf, nf, 3, 1, 1, bias=True)

        # initialization
        initialize_weights([self.conv1, self.conv2], 0.1)

    def forward(self, x):
        identity = x
        out = F.relu(self.conv1(x), inplace=True)
        out = self.conv2(out)
        return identity + out

class neuro(nn.Module):
    def __init__(self, n_c=128, n_b=10, scale=2):
        super(neuro, self).__init__()
        pad = (1,1)
        block = []
        self.conv_1 = nn.Conv2d(scale**2*3 + n_c + 3*2, n_c, (3,3), stride=(1,1), padding=pad)
        basic_block = functools.partial(ResidualBlock_noBN, nf=n_c)
        self.recon_trunk = make_layer(basic_block, n_b)
        self.conv_h = nn.Conv2d(n_c, n_c, (3,3), stride=(1,1), padding=pad)
        self.conv_o = nn.Conv2d(n_c, scale**2*3, (3,3), stride=(1,1), padding=pad)
        initialize_weights([self.conv_1, self.conv_h, self.conv_o], 0.1)

        self.down = PixelUnShuffle(upscale_factor=scale)

    def forward(self, f1, f2, h, o):
        x = torch.cat((f1, f2), dim=1)
        o = self.down(o)

        x = torch.cat((x, h, o), dim=1)
        x = F.relu(self.conv_1(x))
        x = self.recon_trunk(x)
        x_h = F.relu(self.conv_h(x))
        x_o = self.conv_o(x)
        return x_h, x_o

class rrn(nn.Module):
    def __init__(self, scale=2, n_c=128, n_b=10):
        super(rrn, self).__init__()
        self.neuro = neuro(n_c=n_c, n_b=n_b, scale=scale)
        self.scale = scale
        
    def forward(self, f1, f2, x_h, x_o):
        x_h, x_o = self.neuro(f1, f2, x_h, x_o)
        x_o = F.pixel_shuffle(x_o, self.scale) + F.interpolate(f2, scale_factor=self.scale, mode='bilinear', align_corners=False)
        x_o = torch.clamp(x_o, 0.0, 1.0)
        
        return x_h, x_o

def pixel_unshuffle(input, upscale_factor):
    batch_size, channels, in_height, in_width = input.size()
    out_height = in_height // upscale_factor
    out_width = in_width // upscale_factor

    input_view = input.contiguous().view(
        batch_size, channels, out_height, upscale_factor,
        out_width, upscale_factor)

    channels *= upscale_factor ** 2
    unshuffle_out = input_view.permute(0, 1, 3, 5, 2, 4).contiguous()
    return unshuffle_out.view(batch_size, channels, out_height, out_width)

class PixelUnShuffle(nn.Module):
    def __init__(self, upscale_factor):
        super(PixelUnShuffle, self).__init__()
        self.upscale_factor = upscale_factor
    def forward(self, input):
        return pixel_unshuffle(input, self.upscale_factor)

    def extra_repr(self):
        return 'upscale_factor={}'.format(self.upscale_factor)

````

**Comment by zheng-ningxin** [comment] 2021-02-22 11:47
Thanks for the response, would you please also provide the tensor shapes of the `dummy_input` ( dummy_input=(f1, f2, x_h, x_o))?

**Comment by zccyman** [comment] 2021-02-23 06:52
> Thanks for the response, would you please also provide the tensor shapes of the `dummy_input` ( dummy_input=(f1, f2, x_h, x_o))?

````
f1 = torch.randn(1, 3, 120, 120, dtype=float32).cuda()
f2 = torch.randn(1, 3, 120, 120, dtype=float32).cuda()
x_h = torch.randn(1, 128, 120, 120, dtype=float32).cuda()
x_o = torch.randn(1, 3, 240, 240, dtype=float32).cuda()
````

**Comment by zheng-ningxin** [comment] 2021-02-24 02:32
Hi please try again when this [pr](https://github.com/microsoft/nni/pull/3399) merged, thanks. By the way, I found that there are some operators that currently not supported in the `ModelSpeedup`, so we cannot use `ModelSpeedup` to accelerate the pruned model temporarily. However, you still can use simulated method(the model with mask) to evaluate your pruning algorithm.

![image](https://user-images.githubusercontent.com/49771382/108938708-8e9b3480-768b-11eb-9e69-ded365850751.png)

**Closed** 2021-03-04 01:14 UTC
Labels: customer raised, model compression, support
