### ISSUE TITLE
SMAC算法多并发，trial出现waiting

### ISSUE THREAD

**Issue by CoderMusou** [microsoft/nni#3451] opened 2021-03-15 06:56 UTC
**Environment**:
- NNI version: 2.0.0
- NNI mode (local|remote|pai): local
- Client OS: Ubuntu
- Server OS (for remote mode only):
- Python version: 3.7.6
- PyTorch/TensorFlow version: pytorch 1.5.1+cu101
- Is conda/virtualenv/venv used?: conda
- Is running in Docker?: no

**Log message**:
 - nnimanager.log: 
```
[2021-03-14 21:25:30] INFO [ 'Datastore initialization done' ]
[2021-03-14 21:25:30] INFO [ 'RestServer start' ]
[2021-03-14 21:25:30] INFO [ 'Construct local machine training service.' ]
[2021-03-14 21:25:30] INFO [ 'RestServer base port is 1825' ]
[2021-03-14 21:25:30] INFO [ 'Rest server listening on: http://0.0.0.0:1825' ]
[2021-03-14 21:25:30] INFO [ 'NNIManager setClusterMetadata, key: trial_config, value: {"command":"python main.py --dataset weibo --nni True","codeDir":"/home/ws/MMECT/.","gpuNum":1}' ]
[2021-03-14 21:25:30] INFO [ 'required GPU number is 1' ]
[2021-03-14 21:25:30] INFO [ 'Starting experiment: NpfCABwW' ]
[2021-03-14 21:25:30] INFO [ 'Change NNIManager status from: INITIALIZED to: RUNNING' ]
[2021-03-14 21:25:30] INFO [ 'Add event listeners' ]
[2021-03-14 21:25:30] INFO [ 'Run local machine training service.' ]
[2021-03-14 21:25:31] INFO [ 'NNIManager received command from dispatcher: ID, ' ]
[2021-03-14 21:25:31] INFO [ 'NNIManager received command from dispatcher: TR, {"parameter_id": 0, "parameter_source": "algorithm", "parameters": {"char_dropout": 0, "components_embed_lr_rate": 0.001, "ff_dropout": 0.2, "ff_dropout_2": 0.2, "gaz_dropout": 0.5, "lr": 0.0015, "momentum": 0.95, "radical_dropout": 0, "warmup": 0.1}, "parameter_index": 0}' ]
[2021-03-14 21:25:31] INFO [ 'NNIManager received command from dispatcher: TR, {"parameter_id": 1, "parameter_source": "algorithm", "parameters": {"char_dropout": 0.4, "components_embed_lr_rate": 0.0016, "ff_dropout": 0.2, "ff_dropout_2": 0, "gaz_dropout": 0.4, "lr": 0.0014, "momentum": 0.9, "radical_dropout": 0.2, "warmup": 0.1}, "parameter_index": 0}' ]
[2021-03-14 21:25:31] INFO [ 'NNIManager received command from dispatcher: TR, {"parameter_id": 2, "parameter_source": "algorithm", "parameters": {"char_dropout": 0, "components_embed_lr_rate": 0.002, "ff_dropout": 0.2, "ff_dropout_2": 0.4, "gaz_dropout": 0.4, "lr": 0.001, "momentum": 0.85, "radical_dropout": 0, "warmup": 0.3}, "parameter_index": 0}' ]
[2021-03-14 21:25:35] INFO [ 'submitTrialJob: form: {"sequenceId":0,"hyperParameters":{"value":"{\\"parameter_id\\": 0, \\"parameter_source\\": \\"algorithm\\", \\"parameters\\": {\\"char_dropout\\": 0, \\"components_embed_lr_rate\\": 0.001, \\"ff_dropout\\": 0.2, \\"ff_dropout_2\\": 0.2, \\"gaz_dropout\\": 0.5, \\"lr\\": 0.0015, \\"momentum\\": 0.95, \\"radical_dropout\\": 0, \\"warmup\\": 0.1}, \\"parameter_index\\": 0}","index":0}}' ]
[2021-03-14 21:25:35] INFO [ 'submitTrialJob: form: {"sequenceId":1,"hyperParameters":{"value":"{\\"parameter_id\\": 1, \\"parameter_source\\": \\"algorithm\\", \\"parameters\\": {\\"char_dropout\\": 0.4, \\"components_embed_lr_rate\\": 0.0016, \\"ff_dropout\\": 0.2, \\"ff_dropout_2\\": 0, \\"gaz_dropout\\": 0.4, \\"lr\\": 0.0014, \\"momentum\\": 0.9, \\"radical_dropout\\": 0.2, \\"warmup\\": 0.1}, \\"parameter_index\\": 0}","index":0}}' ]
[2021-03-14 21:25:35] INFO [ 'submitTrialJob: form: {"sequenceId":2,"hyperParameters":{"value":"{\\"parameter_id\\": 2, \\"parameter_source\\": \\"algorithm\\", \\"parameters\\": {\\"char_dropout\\": 0, \\"components_embed_lr_rate\\": 0.002, \\"ff_dropout\\": 0.2, \\"ff_dropout_2\\": 0.4, \\"gaz_dropout\\": 0.4, \\"lr\\": 0.001, \\"momentum\\": 0.85, \\"radical_dropout\\": 0, \\"warmup\\": 0.3}, \\"parameter_index\\": 0}","index":0}}' ]
[2021-03-14 21:25:40] INFO [ 'Trial job nncIx status changed from WAITING to RUNNING' ]
[2021-03-14 21:25:41] INFO [ 'Trial job QKPTf status changed from WAITING to RUNNING' ]
[2021-03-14 21:25:41] INFO [ 'Trial job plX1I status changed from WAITING to RUNNING' ]
[2021-03-14 21:39:13] INFO [ 'Trial job plX1I status changed from RUNNING to SUCCEEDED' ]
[2021-03-14 21:39:13] INFO [ 'NNIManager received command from dispatcher: TR, {"parameter_id": 3, "parameter_source": "algorithm", "parameters": {"char_dropout": 0, "components_embed_lr_rate": 0.001, "ff_dropout": 0.4, "ff_dropout_2": 0, "gaz_dropout": 0.4, "lr": 0.0014, "momentum": 0.9, "radical_dropout": 0.4, "warmup": 0.3}, "parameter_index": 0}' ]
[2021-03-14 21:39:18] INFO [ 'Trial job QKPTf status changed from RUNNING to SUCCEEDED' ]
[2021-03-14 21:39:18] INFO [ 'submitTrialJob: form: {"sequenceId":3,"hyperParameters":{"value":"{\\"parameter_id\\": 3, \\"parameter_source\\": \\"algorithm\\", \\"parameters\\": {\\"char_dropout\\": 0, \\"components_embed_lr_rate\\": 0.001, \\"ff_dropout\\": 0.4, \\"ff_dropout_2\\": 0, \\"gaz_dropout\\": 0.4, \\"lr\\": 0.0014, \\"momentum\\": 0.9, \\"radical_dropout\\": 0.4, \\"warmup\\": 0.3}, \\"parameter_index\\": 0}","index":0}}' ]
[2021-03-14 21:39:18] INFO [ 'NNIManager received command from dispatcher: TR, {"parameter_id": 4, "parameter_source": "algorithm", "parameters": {"char_dropout": 0.4, "components_embed_lr_rate": 0.0012, "ff_dropout": 0, "ff_dropout_2": 0.2, "gaz_dropout": 0.4, "lr": 0.0016, "momentum": 0.85, "radical_dropout": 0, "warmup": 0.3}, "parameter_index": 0}' ]
[2021-03-14 21:39:23] INFO [ 'Trial job Cmizi status changed from WAITING to RUNNING' ]
[2021-03-14 21:39:23] INFO [ 'submitTrialJob: form: {"sequenceId":4,"hyperParameters":{"value":"{\\"parameter_id\\": 4, \\"parameter_source\\": \\"algorithm\\", \\"parameters\\": {\\"char_dropout\\": 0.4, \\"components_embed_lr_rate\\": 0.0012, \\"ff_dropout\\": 0, \\"ff_dropout_2\\": 0.2, \\"gaz_dropout\\": 0.4, \\"lr\\": 0.0016, \\"momentum\\": 0.85, \\"radical_dropout\\": 0, \\"warmup\\": 0.3}, \\"parameter_index\\": 0}","index":0}}' ]
[2021-03-14 21:39:33] INFO [ 'Trial job nncIx status changed from RUNNING to SUCCEEDED' ]
[2021-03-14 21:39:33] INFO [ 'Trial job v4yfV status changed from WAITING to RUNNING' ]
[2021-03-14 21:39:33] INFO [ 'NNIManager received command from dispatcher: TR, {"parameter_id": 5, "parameter_source": "algorithm", "parameters": {"char_dropout": 0.2, "components_embed_lr_rate": 0.001, "ff_dropout": 0, "ff_dropout_2": 0.2, "gaz_dropout": 0.5, "lr": 0.0008, "momentum": 0.85, "radical_dropout": 0, "warmup": 0.2}, "parameter_index": 0}' ]
[2021-03-14 21:39:38] INFO [ 'submitTrialJob: form: {"sequenceId":5,"hyperParameters":{"value":"{\\"parameter_id\\": 5, \\"parameter_source\\": \\"algorithm\\", \\"parameters\\": {\\"char_dropout\\": 0.2, \\"components_embed_lr_rate\\": 0.001, \\"ff_dropout\\": 0, \\"ff_dropout_2\\": 0.2, \\"gaz_dropout\\": 0.5, \\"lr\\": 0.0008, \\"momentum\\": 0.85, \\"radical_dropout\\": 0, \\"warmup\\": 0.2}, \\"parameter_index\\": 0}","index":0}}' ]
[2021-03-14 21:39:43] INFO [ 'Trial job o0QUy status changed from WAITING to RUNNING' ]
[2021-03-14 21:53:06] INFO [ 'Trial job o0QUy status changed from RUNNING to SUCCEEDED' ]
[2021-03-14 21:53:06] INFO [ 'NNIManager received command from dispatcher: TR, {"parameter_id": 6, "parameter_source": "algorithm", "parameters": {"char_dropout": 0, "components_embed_lr_rate": 0.0014, "ff_dropout": 0.2, "ff_dropout_2": 0.4, "gaz_dropout": 0.5, "lr": 0.0016, "momentum": 0.85, "radical_dropout": 0, "warmup": 0.3}, "parameter_index": 0}' ]
[2021-03-14 21:53:11] INFO [ 'Trial job Cmizi status changed from RUNNING to SUCCEEDED' ]
[2021-03-14 21:53:11] INFO [ 'Trial job v4yfV status changed from RUNNING to SUCCEEDED' ]
[2021-03-14 21:53:11] INFO [ 'submitTrialJob: form: {"sequenceId":6,"hyperParameters":{"value":"{\\"parameter_id\\": 6, \\"parameter_source\\": \\"algorithm\\", \\"parameters\\": {\\"char_dropout\\": 0, \\"components_embed_lr_rate\\": 0.0014, \\"ff_dropout\\": 0.2, \\"ff_dropout_2\\": 0.4, \\"gaz_dropout\\": 0.5, \\"lr\\": 0.0016, \\"momentum\\": 0.85, \\"radical_dropout\\": 0, \\"warmup\\": 0.3}, \\"parameter_index\\": 0}","index":0}}' ]
[2021-03-14 21:53:11] INFO [ 'NNIManager received command from dispatcher: TR, {"parameter_id": 7, "parameter_source": "algorithm", "parameters": {"char_dropout": 0.4, "components_embed_lr_rate": 0.0016, "ff_dropout": 0, "ff_dropout_2": 0.2, "gaz_dropout": 0.5, "lr": 0.001, "momentum": 0.85, "radical_dropout": 0, "warmup": 0.4}, "parameter_index": 0}' ]
[2021-03-14 21:53:11] INFO [ 'NNIManager received command from dispatcher: TR, {"parameter_id": 8, "parameter_source": "algorithm", "parameters": {"char_dropout": 0.4, "components_embed_lr_rate": 0.0014, "ff_dropout": 0.2, "ff_dropout_2": 0.4, "gaz_dropout": 0.5, "lr": 0.001, "momentum": 0.9, "radical_dropout": 0, "warmup": 0.2}, "parameter_index": 0}' ]
[2021-03-14 21:53:16] INFO [ 'Trial job ks9bX status changed from WAITING to RUNNING' ]
[2021-03-14 21:53:16] INFO [ 'submitTrialJob: form: {"sequenceId":7,"hyperParameters":{"value":"{\\"parameter_id\\": 7, \\"parameter_source\\": \\"algorithm\\", \\"parameters\\": {\\"char_dropout\\": 0.4, \\"components_embed_lr_rate\\": 0.0016, \\"ff_dropout\\": 0, \\"ff_dropout_2\\": 0.2, \\"gaz_dropout\\": 0.5, \\"lr\\": 0.001, \\"momentum\\": 0.85, \\"radical_dropout\\": 0, \\"warmup\\": 0.4}, \\"parameter_index\\": 0}","index":0}}' ]
[2021-03-14 21:53:16] INFO [ 'submitTrialJob: form: {"sequenceId":8,"hyperParameters":{"value":"{\\"parameter_id\\": 8, \\"parameter_source\\": \\"algorithm\\", \\"parameters\\": {\\"char_dropout\\": 0.4, \\"components_embed_lr_rate\\": 0.0014, \\"ff_dropout\\": 0.2, \\"ff_dropout_2\\": 0.4, \\"gaz_dropout\\": 0.5, \\"lr\\": 0.001, \\"momentum\\": 0.9, \\"radical_dropout\\": 0, \\"warmup\\": 0.2}, \\"parameter_index\\": 0}","index":0}}' ]
[2021-03-14 21:53:21] INFO [ 'Trial job Z3l0l status changed from WAITING to RUNNING' ]
[2021-03-14 21:53:21] INFO [ 'Trial job ZjECF status changed from WAITING to RUNNING' ]
[2021-03-14 22:06:39] INFO [ 'Trial job Z3l0l status changed from RUNNING to SUCCEEDED' ]
[2021-03-14 22:06:39] INFO [ 'NNIManager received command from dispatcher: TR, {"parameter_id": 9, "parameter_source": "algorithm", "parameters": {"char_dropout": 0.4, "components_embed_lr_rate": 0.0018, "ff_dropout": 0.4, "ff_dropout_2": 0.4, "gaz_dropout": 0.4, "lr": 0.0012, "momentum": 0.9, "radical_dropout": 0.2, "warmup": 0.2}, "parameter_index": 0}' ]
[2021-03-14 22:06:44] INFO [ 'submitTrialJob: form: {"sequenceId":9,"hyperParameters":{"value":"{\\"parameter_id\\": 9, \\"parameter_source\\": \\"algorithm\\", \\"parameters\\": {\\"char_dropout\\": 0.4, \\"components_embed_lr_rate\\": 0.0018, \\"ff_dropout\\": 0.4, \\"ff_dropout_2\\": 0.4, \\"gaz_dropout\\": 0.4, \\"lr\\": 0.0012, \\"momentum\\": 0.9, \\"radical_dropout\\": 0.2, \\"warmup\\": 0.2}, \\"parameter_index\\": 0}","index":0}}' ]
[2021-03-14 22:06:49] INFO [ 'Trial job TYxNH status changed from WAITING to RUNNING' ]
[2021-03-14 22:07:09] INFO [ 'Trial job ks9bX status changed from RUNNING to SUCCEEDED' ]
[2021-03-14 22:07:09] INFO [ 'Trial job ZjECF status changed from RUNNING to SUCCEEDED' ]
[2021-03-14 22:07:09] INFO [ 'NNIManager received command from dispatcher: TR, {"parameter_id": 10, "parameter_source": "algorithm", "parameters": {"char_dropout": 0, "components_embed_lr_rate": 0.0008, "ff_dropout": 0.2, "ff_dropout_2": 0, "gaz_dropout": 0.4, "lr": 0.002, "momentum": 0.9, "radical_dropout": 0, "warmup": 0.3}, "parameter_index": 0}' ]
[2021-03-14 22:07:09] INFO [ 'NNIManager received command from dispatcher: TR, {"parameter_id": 11, "parameter_source": "algorithm", "parameters": {"char_dropout": 0.4, "components_embed_lr_rate": 0.0015, "ff_dropout": 0.4, "ff_dropout_2": 0, "gaz_dropout": 0.5, "lr": 0.0018, "momentum": 0.95, "radical_dropout": 0, "warmup": 0.3}, "parameter_index": 0}' ]
[2021-03-14 22:07:14] INFO [ 'submitTrialJob: form: {"sequenceId":10,"hyperParameters":{"value":"{\\"parameter_id\\": 10, \\"parameter_source\\": \\"algorithm\\", \\"parameters\\": {\\"char_dropout\\": 0, \\"components_embed_lr_rate\\": 0.0008, \\"ff_dropout\\": 0.2, \\"ff_dropout_2\\": 0, \\"gaz_dropout\\": 0.4, \\"lr\\": 0.002, \\"momentum\\": 0.9, \\"radical_dropout\\": 0, \\"warmup\\": 0.3}, \\"parameter_index\\": 0}","index":0}}' ]
[2021-03-14 22:07:14] INFO [ 'submitTrialJob: form: {"sequenceId":11,"hyperParameters":{"value":"{\\"parameter_id\\": 11, \\"parameter_source\\": \\"algorithm\\", \\"parameters\\": {\\"char_dropout\\": 0.4, \\"components_embed_lr_rate\\": 0.0015, \\"ff_dropout\\": 0.4, \\"ff_dropout_2\\": 0, \\"gaz_dropout\\": 0.5, \\"lr\\": 0.0018, \\"momentum\\": 0.95, \\"radical_dropout\\": 0, \\"warmup\\": 0.3}, \\"parameter_index\\": 0}","index":0}}' ]
[2021-03-14 22:07:19] INFO [ 'Trial job GeMVt status changed from WAITING to RUNNING' ]
[2021-03-14 22:07:19] INFO [ 'Trial job d2AMl status changed from WAITING to RUNNING' ]
[2021-03-14 22:20:17] INFO [ 'Trial job TYxNH status changed from RUNNING to SUCCEEDED' ]
[2021-03-14 22:20:17] INFO [ 'NNIManager received command from dispatcher: TR, {"parameter_id": 12, "parameter_source": "algorithm", "parameters": {"char_dropout": 0, "components_embed_lr_rate": 0.0012, "ff_dropout": 0, "ff_dropout_2": 0, "gaz_dropout": 0.5, "lr": 0.0016, "momentum": 0.9, "radical_dropout": 0, "warmup": 0.3}, "parameter_index": 0}' ]
[2021-03-14 22:20:22] INFO [ 'submitTrialJob: form: {"sequenceId":12,"hyperParameters":{"value":"{\\"parameter_id\\": 12, \\"parameter_source\\": \\"algorithm\\", \\"parameters\\": {\\"char_dropout\\": 0, \\"components_embed_lr_rate\\": 0.0012, \\"ff_dropout\\": 0, \\"ff_dropout_2\\": 0, \\"gaz_dropout\\": 0.5, \\"lr\\": 0.0016, \\"momentum\\": 0.9, \\"radical_dropout\\": 0, \\"warmup\\": 0.3}, \\"parameter_index\\": 0}","index":0}}' ]
[2021-03-14 22:20:37] INFO [ 'Trial job GeMVt status changed from RUNNING to SUCCEEDED' ]
[2021-03-14 22:20:37] INFO [ 'Trial job d2AMl status changed from RUNNING to SUCCEEDED' ]
[2021-03-14 22:20:37] INFO [ 'NNIManager received command from dispatcher: TR, {"parameter_id": 13, "parameter_source": "algorithm", "parameters": {"char_dropout": 0.4, "components_embed_lr_rate": 0.0018, "ff_dropout": 0, "ff_dropout_2": 0, "gaz_dropout": 0.5, "lr": 0.0014, "momentum": 0.9, "radical_dropout": 0, "warmup": 0.1}, "parameter_index": 0}' ]
[2021-03-14 22:20:37] INFO [ 'NNIManager received command from dispatcher: TR, {"parameter_id": 14, "parameter_source": "algorithm", "parameters": {"char_dropout": 0.2, "components_embed_lr_rate": 0.0014, "ff_dropout": 0.2, "ff_dropout_2": 0, "gaz_dropout": 0.4, "lr": 0.0014, "momentum": 0.95, "radical_dropout": 0.2, "warmup": 0.4}, "parameter_index": 0}' ]
[2021-03-14 22:20:42] INFO [ 'submitTrialJob: form: {"sequenceId":13,"hyperParameters":{"value":"{\\"parameter_id\\": 13, \\"parameter_source\\": \\"algorithm\\", \\"parameters\\": {\\"char_dropout\\": 0.4, \\"components_embed_lr_rate\\": 0.0018, \\"ff_dropout\\": 0, \\"ff_dropout_2\\": 0, \\"gaz_dropout\\": 0.5, \\"lr\\": 0.0014, \\"momentum\\": 0.9, \\"radical_dropout\\": 0, \\"warmup\\": 0.1}, \\"parameter_index\\": 0}","index":0}}' ]
[2021-03-14 22:20:42] INFO [ 'submitTrialJob: form: {"sequenceId":14,"hyperParameters":{"value":"{\\"parameter_id\\": 14, \\"parameter_source\\": \\"algorithm\\", \\"parameters\\": {\\"char_dropout\\": 0.2, \\"components_embed_lr_rate\\": 0.0014, \\"ff_dropout\\": 0.2, \\"ff_dropout_2\\": 0, \\"gaz_dropout\\": 0.4, \\"lr\\": 0.0014, \\"momentum\\": 0.95, \\"radical_dropout\\": 0.2, \\"warmup\\": 0.4}, \\"parameter_index\\": 0}","index":0}}' ]
```
 - dispatcher.log:
```
[2021-03-14 21:25:31] INFO (nni.runtime.msg_dispatcher_base/MainThread) Dispatcher started
[2021-03-14 21:25:31] INFO (smac_AutoML/Thread-1) update search space in SMAC.
[2021-03-14 21:25:31] INFO (smac_AutoML/Thread-1) SMAC call: /home/ws/anaconda3/envs/nlp/lib/python3.7/site-packages/nni/__main__.py --exp_params eyJhdXRob3JOYW1lIjoiZGVmYXVsdCIsImV4cGVyaW1lbnROYW1lIjoiTU1FQ1QgV2VpYm8iLCJ0cmlhbENvbmN1cnJlbmN5IjozLCJtYXhFeGVjRHVyYXRpb24iOjg2MzEzNjAwLCJtYXhUcmlhbE51bSI6OTk5OTksInRyYWluaW5nU2VydmljZVBsYXRmb3JtIjoibG9jYWwiLCJ0dW5lciI6eyJidWlsdGluVHVuZXJOYW1lIjoiU01BQyIsImNsYXNzQXJncyI6eyJvcHRpbWl6ZV9tb2RlIjoibWF4aW1pemUiLCJjb25maWdfZGVkdXAiOnRydWV9fSwidmVyc2lvbkNoZWNrIjp0cnVlLCJjbHVzdGVyTWV0YURhdGEiOlt7ImtleSI6ImNvZGVEaXIiLCJ2YWx1ZSI6Ii9ob21lL3dzL01NRUNULy4ifSx7ImtleSI6ImNvbW1hbmQiLCJ2YWx1ZSI6InB5dGhvbiBtYWluLnB5IC0tZGF0YXNldCB3ZWlibyAtLW5uaSBUcnVlIn1dfQ==
```
 - nnictl stdout and stderr: 
stdout :
```
 -----------------------------------------------------------------------
                Experiment start time 2021-03-14 21:25:29
-----------------------------------------------------------------------
INFO:   Reading scenario file: scenario.txt
INFO:   Output to smac3-output_2021-03-14_21:25:31_351225
<!-- Where can you find the log files: [log](https://github.com/microsoft/nni/blob/master/docs/en_US/Tutorial/HowToDebug.md#experiment-root-director), [stdout/stderr](https://github.com/microsoft/nni/blob/master/docs/en_US/Tutorial/Nnictl.md#nnictl%20log%20stdout) -->
```
stderr:
```
-----------------------------------------------------------------------
                Experiment start time 2021-03-14 21:25:29
-----------------------------------------------------------------------
/home/ws/anaconda3/envs/nlp/lib/python3.7/site-packages/pyparsing.py:3190: FutureWarning: Possible set intersection at position 3
  self.re = re.compile(self.reString)
/home/ws/anaconda3/envs/nlp/lib/python3.7/site-packages/json_tricks/nonp.py:225: JsonTricksDeprecation: `json_tricks.load(s)` stripped some comments, but `ignore_comments` was not passed; in the next major release, the behaviour when `ignore_comments` is not passed will change; it is recommended to explicitly pass `ignore_comments=True` if you want to strip comments; see https://github.com/mverleg/pyjson_tricks/issues/74
  JsonTricksDeprecation)
```

**What issue meet, what's expected?**:
我用SMAC算法，配置了3个trial并发，会在第8-12个左右的trial一直显示waiting。配置了3个trial并发，会有所缓解，但是跑到100多个trial也会出现同样的问题。前面的trial都可以正常执行
![image](https://user-images.githubusercontent.com/20904589/111114647-78073f80-859e-11eb-9684-fb4901cf5eb4.png)

**How to reproduce it?**: 

**Additional information**:

**Comment by SparkSnail** [comment] 2021-03-18 07:15
Hi @CoderMusou, I didn't find enough information in your nniManager.log, could you please use `nnictl create --config {file} --debug` to enable debug mode on NNI, and paste nniManager.log file here? What is your experiment' status when the issue happens? You could check experiment status in overview page.
There some possible reasons:  
1. Will your issue happen when you do not set GPU configuration in experiment? NNI will not schedule trial jobs to GPU when the GPU has another process running on it, could you please double check if there are another processes running on you GPU devices when trial blocks on waitting status? You could set [useActiveGpu](https://github.com/microsoft/nni/blob/master/docs/en_US/Tutorial/ExperimentConfig.rst#useactivegpu) config to avoid this situation.
2. NNI has [maxExecDuration](https://github.com/microsoft/nni/blob/master/docs/en_US/Tutorial/ExperimentConfig.rst#maxexecduration) to specifies the max duration time of an experiment, you should make sure you set enough duration time for your experiment.

I noticed you use NNI v2.0 to run experiment, could you please upgrade NNI version to v2.1 and try again?

**Comment by CoderMusou** [comment] 2021-03-19 03:00
My experiment's status is RUNNING and GPU has no processes running when the issue happens.  And the maxExecDuration also the maximum, 1438560. I’ll check the logs in debug mode, and I’ll let you know

**Comment by CoderMusou** [comment] 2021-03-19 08:03
Hello, I have the same problem in debug mode, but the log file is larger, how can I show you?

**Comment by CoderMusou** [comment] 2021-03-19 08:05
Hello, I have the same problem in debug mode, but the log file is larger, how can I show you? Now I’ll try to see if this happens when I update to v2.1.

**Comment by SparkSnail** [comment] 2021-03-19 09:18
Just zip your file, and drag it to github chat dialog. Github will upload your file automatically.

**Comment by CoderMusou** [comment] 2021-03-19 11:19
Ok, This is the log file.
[nnimanager.log](https://github.com/microsoft/nni/files/6170712/nnimanager.log)

**Comment by SparkSnail** [comment] 2021-03-23 10:58
Hi, I've checked the nniManager.log, and didn't find useful information from the log. Is there any content under the `WAITING` trials' log path? For example, the path` /home/ws/nni-experiments/4udb3gEL/trials/P03i4` in your last experimet. Is there content in `nnictl log stderr 4udb3gEL` and `nnictl log stdout 4udb3gEL`?

**Comment by CoderMusou** [comment] 2021-03-24 01:47
I'm so sorry, the file in the directory `nni-experiments` was deleted by me. Because  I upgraded to v2.1, I still had this issue. When I used v1.9 and deleted the `nni-experiments` directory, the problem disappeared. The problem started after I upgraded from 1.9 to 2.0, and someone in the wechat group should have the same problem as me.

**Comment by QuanluZhang** [comment] 2021-03-24 01:52
@CoderMusou , thanks for the detailed description. we will try to reproduce this problem using the mnist-pytorch example in v2.1

**Comment by QuanluZhang** [comment] 2021-03-26 01:25
@CoderMusou , sorry, I failed to reproduce your problem. It is not the problem of SMAC, because the experiment has already received new trial configurations. it is waiting mainly because there is no available resource or the training service cannot find available resource due to some reason. As @SparkSnail suggested, could you show us `nnictl log stderr <exp-id>` and `nnictl log stdout <exp-id>`? thanks.

**Comment by QuanluZhang** [comment] 2021-03-26 04:04
@CoderMusou , we preproduce this problem. We are finding the root cause. For now, you can run `METRIC_OUTPUT_DIR=/tmp/<your-user-account>/nni/script python3 -m nni.tools.gpu_tool.gpu_metrics_collector` for workaround. after this command is executed, the waiting jobs will start running.

**Comment by yangqin0309** [comment] 2021-04-12 01:29
Hi, has this problem been solved? 
I have the same issue with hyperparams tuning by TPE.
![image](https://user-images.githubusercontent.com/69283864/114329273-dca3c300-9b79-11eb-83aa-971ce6d4fc37.png)

**Comment by QuanluZhang** [comment] 2021-04-12 06:25
@yangqin0309 please use the above workaround for now. We are trying to find out the reason why `gpu_metrics_collector` is killed silently.

**Comment by yangqin0309** [comment] 2021-04-12 06:59
> @yangqin0309 please use the above workaround for now. We are trying to find out the reason why `gpu_metrics_collector` is killed silently.

Ok, thanks a lot.

**Comment by QingXIA233** [comment] 2021-04-29 07:31
Hello all,

I have the same issue when I try to use grid search to get the best choice of parameters for Efficientnet-v2-M on my own datasets. When I used a small amount of data, everything went all right, all 15 trials succeeded:
![image](https://user-images.githubusercontent.com/64100948/116514830-2290b300-a8fe-11eb-9775-cd9b8a057402.png)

However, when I tried to use more data, 7 trials succeeded but then it got stuck in WAITING state for the rest of the trials.
![image](https://user-images.githubusercontent.com/64100948/116515223-916e0c00-a8fe-11eb-9fc3-2fe5aad111fd.png)

I couldn't figure out the problem. Meanwhile, using less data can't be the solution here because I got different best choices when I use a small amount of data for searching. (The first time, trial N.O 2 got the best result but when I re-tried the SAME experiment, trial N.O 5 got the best result.) 

Please provide me some clues about the reason why this issue occurs. BTW, when I run my trials and set the concurrency as 4, it always get 1 trial RUNNING and 3 trials WAITING, could you guys please give me some hints about this problem, too? Thanks a lot.

**Comment by scarlett2018** [comment] 2021-06-10 01:25
> Hello all,
> 
> I have the same issue when I try to use grid search to get the best choice of parameters for Efficientnet-v2-M on my own datasets. When I used a small amount of data, everything went all right, all 15 trials succeeded:
> ![image](https://user-images.githubusercontent.com/64100948/116514830-2290b300-a8fe-11eb-9775-cd9b8a057402.png)
> 
> However, when I tried to use more data, 7 trials succeeded but then it got stuck in WAITING state for the rest of the trials.
> ![image](https://user-images.githubusercontent.com/64100948/116515223-916e0c00-a8fe-11eb-9fc3-2fe5aad111fd.png)
> 
> I couldn't figure out the problem. Meanwhile, using less data can't be the solution here because I got different best choices when I use a small amount of data for searching. (The first time, trial N.O 2 got the best result but when I re-tried the SAME experiment, trial N.O 5 got the best result.)
> 
> Please provide me some clues about the reason why this issue occurs. BTW, when I run my trials and set the concurrency as 4, it always get 1 trial RUNNING and 3 trials WAITING, could you guys please give me some hints about this problem, too? Thanks a lot.

as the original problem has been resolved, closing this issue and opening a new issue for the latest comment in #3786

**Closed by scarlett2018** 2021-06-10 01:25 UTC
Labels: customer raised, support
