### ISSUE TITLE
experiment exit before the set time

### ISSUE THREAD

**Issue by ghost** [microsoft/nni#2243] opened 2020-03-27 06:17 UTC
**nni Environment**:
- nni version: 1.1
- nni mode(local|pai|remote): remote
- OS: centos
- python version: 3.7
- is conda or virtualenv used?:  no
- is running in docker?: yes
- nni tuner : NetworkMorphism
- dataset: cifar10_pytorch

**Anything else we need to know**:
My environment is built on a docker, experiment time setting 24h, I run nni in remote mode on Intel's DGX-2 (16GPU*8) without problems, but when I deploy the container to run on another server(8GPU*16),test several times and exit at the same time.
I in several break branches of the tuner.py run () function performed _logger.info and got commend is None ,I would like to know what is the possible cause of this problem.

**config.yml:**
`authorName: default
experimentName: example_cifar10-network-morphism-test
trialConcurrency: 128
maxExecDuration: 24h
maxTrialNum: 6000
debug: true
#choice: local, remote, pai
trainingServicePlatform: remote
nniManagerIp: 
#searchSpacePath: search_space.json
#choice: true, false
useAnnotation: false
tuner:
  #choice: TPE, Random, Anneal, Evolution, BatchTuner, NetworkMorphism
  #SMAC (SMAC should be installed through nnictl)
  builtinTunerName: NetworkMorphism
  classArgs:
    #choice: maximize, minimize
    optimize_mode: maximize
    #for now, this tuner only supports cv domain
    task: cv
    #input image width
    input_width: 32
    #input image channel
    input_channel: 3
    #number of classes
    n_output_node: 10
trial:
  command: python3 cifar10_pytorch.py
  codeDir: .
  gpuNum: 1
machineList:
  - ip: 
    port: 
    username: 
    passwd:`

**dispatcher.log**

> [03/25/2020, 03:30:26 AM] INFO (NetworkMorphism_AutoML/MainThread) self.path = /root/mountdir/nni/experiments/qgSL0U9d/log/model_path
> [03/25/2020, 03:30:26 AM] INFO (nni.msg_dispatcher_base/MainThread) Start dispatcher
> [03/25/2020, 03:30:44 AM] PRINT New model generated, current jobs = 1
> [03/25/2020, 03:30:44 AM] PRINT New model generated, current jobs = 2
> [03/25/2020, 03:30:45 AM] PRINT New model generated, current jobs = 3
> [03/25/2020, 03:30:45 AM] PRINT New model generated, current jobs = 4
> [03/25/2020, 03:30:46 AM] PRINT New model generated, current jobs = 5
> [03/25/2020, 03:30:46 AM] PRINT New model generated, current jobs = 6
> [03/25/2020, 03:30:48 AM] PRINT New model generated, current jobs = 7
> [03/25/2020, 03:30:48 AM] PRINT New model generated, current jobs = 8
> [03/25/2020, 03:30:49 AM] PRINT New model generated, current jobs = 9
> [03/25/2020, 03:30:49 AM] PRINT New model generated, current jobs = 10
> [03/25/2020, 03:30:49 AM] PRINT New model generated, current jobs = 11
> [03/25/2020, 03:30:49 AM] PRINT New model generated, current jobs = 12
> [03/25/2020, 03:30:51 AM] PRINT New model generated, current jobs = 13
> [03/25/2020, 03:30:51 AM] PRINT New model generated, current jobs = 14
> [03/25/2020, 03:30:56 AM] PRINT New model generated, current jobs = 15
> [03/25/2020, 03:30:56 AM] PRINT New model generated, current jobs = 16
> [03/25/2020, 03:30:57 AM] PRINT New model generated, current jobs = 17
> [03/25/2020, 03:30:57 AM] PRINT New model generated, current jobs = 18
> [03/25/2020, 03:30:57 AM] PRINT New model generated, current jobs = 19
> [03/25/2020, 03:30:57 AM] PRINT New model generated, current jobs = 20
> [03/25/2020, 03:30:58 AM] PRINT New model generated, current jobs = 21
> [03/25/2020, 03:30:58 AM] PRINT New model generated, current jobs = 22
> [03/25/2020, 03:30:59 AM] PRINT New model generated, current jobs = 23
> [03/25/2020, 03:30:59 AM] PRINT New model generated, current jobs = 24
> [03/25/2020, 03:30:59 AM] PRINT New model generated, current jobs = 25
> [03/25/2020, 03:30:59 AM] PRINT New model generated, current jobs = 26
> [03/25/2020, 03:31:05 AM] PRINT New model generated, current jobs = 27
> [03/25/2020, 03:31:05 AM] PRINT New model generated, current jobs = 28
> [03/25/2020, 03:31:05 AM] PRINT New model generated, current jobs = 29
> [03/25/2020, 03:31:05 AM] PRINT New model generated, current jobs = 30
> [03/25/2020, 03:31:05 AM] PRINT New model generated, current jobs = 31
> [03/25/2020, 03:31:05 AM] PRINT New model generated, current jobs = 32
> [03/25/2020, 03:31:07 AM] PRINT New model generated, current jobs = 33
> [03/25/2020, 03:31:07 AM] PRINT New model generated, current jobs = 34
> [03/25/2020, 03:31:10 AM] PRINT New model generated, current jobs = 35
> [03/25/2020, 03:31:10 AM] PRINT New model generated, current jobs = 36
> [03/25/2020, 03:31:11 AM] PRINT New model generated, current jobs = 37
> [03/25/2020, 03:31:11 AM] PRINT New model generated, current jobs = 38
> [03/25/2020, 03:31:11 AM] PRINT New model generated, current jobs = 39
> [03/25/2020, 03:31:11 AM] PRINT New model generated, current jobs = 40
> [03/25/2020, 03:31:12 AM] PRINT New model generated, current jobs = 41
> [03/25/2020, 03:31:12 AM] PRINT New model generated, current jobs = 42
> [03/25/2020, 03:31:14 AM] PRINT New model generated, current jobs = 43
> [03/25/2020, 03:31:14 AM] PRINT New model generated, current jobs = 44
> [03/25/2020, 03:31:15 AM] PRINT New model generated, current jobs = 45
> [03/25/2020, 03:31:15 AM] PRINT New model generated, current jobs = 46
> [03/25/2020, 03:31:15 AM] PRINT New model generated, current jobs = 47
> [03/25/2020, 03:31:15 AM] PRINT New model generated, current jobs = 48
> [03/25/2020, 03:31:17 AM] PRINT New model generated, current jobs = 49
> [03/25/2020, 03:31:17 AM] PRINT New model generated, current jobs = 50
> [03/25/2020, 03:31:21 AM] PRINT New model generated, current jobs = 51
> [03/25/2020, 03:31:21 AM] PRINT New model generated, current jobs = 52
> [03/25/2020, 03:31:23 AM] PRINT New model generated, current jobs = 53
> [03/25/2020, 03:31:23 AM] PRINT New model generated, current jobs = 54
> [03/25/2020, 03:31:23 AM] PRINT New model generated, current jobs = 55
> [03/25/2020, 03:31:23 AM] PRINT New model generated, current jobs = 56
> [03/25/2020, 03:31:24 AM] PRINT New model generated, current jobs = 57
> [03/25/2020, 03:31:24 AM] PRINT New model generated, current jobs = 58
> [03/25/2020, 03:31:25 AM] PRINT New model generated, current jobs = 59
> [03/25/2020, 03:31:25 AM] PRINT New model generated, current jobs = 60
> [03/25/2020, 03:31:26 AM] PRINT New model generated, current jobs = 61
> [03/25/2020, 03:31:26 AM] PRINT New model generated, current jobs = 62
> [03/25/2020, 03:31:27 AM] PRINT New model generated, current jobs = 63
> [03/25/2020, 03:31:27 AM] PRINT New model generated, current jobs = 64
> [03/25/2020, 03:31:30 AM] PRINT New model generated, current jobs = 65
> [03/25/2020, 03:31:30 AM] PRINT New model generated, current jobs = 66
> [03/25/2020, 03:31:32 AM] PRINT New model generated, current jobs = 67
> [03/25/2020, 03:31:32 AM] PRINT New model generated, current jobs = 68
> [03/25/2020, 03:31:32 AM] PRINT New model generated, current jobs = 69
> [03/25/2020, 03:31:32 AM] PRINT New model generated, current jobs = 70
> [03/25/2020, 03:31:32 AM] PRINT New model generated, current jobs = 71
> [03/25/2020, 03:31:32 AM] PRINT New model generated, current jobs = 72
> [03/25/2020, 03:31:33 AM] PRINT New model generated, current jobs = 73
> [03/25/2020, 03:31:33 AM] PRINT New model generated, current jobs = 74
> [03/25/2020, 03:31:33 AM] PRINT New model generated, current jobs = 75
> [03/25/2020, 03:31:34 AM] PRINT New model generated, current jobs = 76
> [03/25/2020, 03:31:37 AM] PRINT New model generated, current jobs = 77
> [03/25/2020, 03:31:37 AM] PRINT New model generated, current jobs = 78
> [03/25/2020, 03:31:40 AM] PRINT New model generated, current jobs = 79
> [03/25/2020, 03:31:40 AM] PRINT New model generated, current jobs = 80
> [03/25/2020, 03:31:44 AM] PRINT New model generated, current jobs = 81
> [03/25/2020, 03:31:44 AM] PRINT New model generated, current jobs = 82
> [03/25/2020, 03:31:46 AM] PRINT New model generated, current jobs = 83
> [03/25/2020, 03:31:46 AM] PRINT New model generated, current jobs = 84
> [03/25/2020, 03:31:46 AM] PRINT New model generated, current jobs = 85
> [03/25/2020, 03:31:46 AM] PRINT New model generated, current jobs = 86
> [03/25/2020, 03:31:46 AM] PRINT New model generated, current jobs = 87
> [03/25/2020, 03:31:46 AM] PRINT New model generated, current jobs = 88
> [03/25/2020, 03:31:47 AM] PRINT New model generated, current jobs = 89
> [03/25/2020, 03:31:47 AM] PRINT New model generated, current jobs = 90
> [03/25/2020, 03:31:49 AM] PRINT New model generated, current jobs = 91
> [03/25/2020, 03:31:49 AM] PRINT New model generated, current jobs = 92
> [03/25/2020, 03:31:49 AM] PRINT New model generated, current jobs = 93
> [03/25/2020, 03:31:50 AM] PRINT New model generated, current jobs = 94
> [03/25/2020, 03:31:52 AM] PRINT New model generated, current jobs = 95
> [03/25/2020, 03:31:52 AM] PRINT New model generated, current jobs = 96
> [03/25/2020, 03:31:54 AM] PRINT New model generated, current jobs = 97
> [03/25/2020, 03:31:54 AM] PRINT New model generated, current jobs = 98
> [03/25/2020, 03:31:54 AM] PRINT New model generated, current jobs = 99
> [03/25/2020, 03:31:54 AM] PRINT New model generated, current jobs = 100
> ......
> [03/25/2020, 07:16:53 PM] PRINT New model generated, current jobs = 231
> [03/25/2020, 07:16:56 PM] PRINT New model generated, current jobs = 232
> [03/25/2020, 07:17:00 PM] PRINT New model generated, current jobs = 233
> [03/25/2020, 07:17:03 PM] PRINT New model generated, current jobs = 234
> [03/25/2020, 07:17:05 PM] PRINT New model generated, current jobs = 235
> [03/25/2020, 07:17:07 PM] PRINT New model generated, current jobs = 236
> [03/25/2020, 07:17:08 PM] PRINT Job finished, current jobs = 235
> [03/25/2020, 07:17:08 PM] INFO (NetworkMorphism_AutoML/Thread-1) Saving model.
> [03/25/2020, 07:17:08 PM] PRINT Update time = 0.0031898021697998047
> [03/25/2020, 07:17:10 PM] PRINT New model generated, current jobs = 236
> [03/25/2020, 07:17:16 PM] PRINT Job finished, current jobs = 235
> [03/25/2020, 07:17:16 PM] INFO (NetworkMorphism_AutoML/Thread-1) Saving model.
> [03/25/2020, 07:17:16 PM] PRINT Update time = 0.008588314056396484
> [03/25/2020, 07:18:28 PM] PRINT New model generated, current jobs = 236
> [03/25/2020, 07:18:32 PM] PRINT New model generated, current jobs = 237
> [03/25/2020, 07:18:35 PM] PRINT New model generated, current jobs = 238
> [03/25/2020, 07:19:47 PM] PRINT Job finished, current jobs = 237
> [03/25/2020, 07:19:47 PM] INFO (NetworkMorphism_AutoML/Thread-1) Saving model.
> [03/25/2020, 07:19:47 PM] PRINT Update time = 0.008461475372314453
> [03/25/2020, 07:20:14 PM] PRINT New model generated, current jobs = 238
> [03/25/2020, 07:21:27 PM] PRINT Job finished, current jobs = 237
> [03/25/2020, 07:21:27 PM] INFO (NetworkMorphism_AutoML/Thread-1) Saving model.
> [03/25/2020, 07:21:27 PM] PRINT Update time = 0.010284185409545898
> [03/25/2020, 07:22:29 PM] PRINT New model generated, current jobs = 238
> [03/25/2020, 07:23:48 PM] PRINT Job finished, current jobs = 237
> [03/25/2020, 07:23:48 PM] INFO (NetworkMorphism_AutoML/Thread-1) Saving model.
> [03/25/2020, 07:23:48 PM] PRINT Update time = 0.0032012462615966797
> [03/25/2020, 07:24:11 PM] PRINT Job finished, current jobs = 236
> [03/25/2020, 07:24:11 PM] INFO (NetworkMorphism_AutoML/Thread-1) Saving model.
> [03/25/2020, 07:24:11 PM] PRINT Update time = 0.006117582321166992
> [03/25/2020, 07:24:33 PM] INFO (nni.msg_dispatcher_base/MainThread) command is None
> [03/25/2020, 07:24:33 PM] INFO (nni.msg_dispatcher_base/MainThread) Dispatcher exiting...

**Comment by chicm-ms** [comment] 2020-03-28 16:59
@c-h-j Would you please run it again with --debug command line argument to collect more debug info?  And did you use the same tuner settings when you run it successfully?  nnimanager communicates with dispatcher through pipe, it appears that dispatcher did not receive correct command from nnimanager since the command is None.

**Comment by c-h-j** [comment] 2020-03-31 08:57
> @chj您是否可以使用--debug命令行参数再次运行它以收集更多调试信息？成功运行时，您是否使用了相同的调谐器设置？nnimanager通过管道与调度程序通信，由于命令为None，调度程序似乎未从nnimanager收到正确的命令。

Yes, I'm sure I use the same environment because it's deployed using the same container.I added the debug option and got " Pipe EOF encountered " before exiting, I suspect it is a system or network problem.Because the log
 is too large, I uploaded it as an attachment.
[dispatcher.log](https://github.com/microsoft/nni/files/4407794/dispatcher.log)

**Comment by chicm-ms** [comment] 2020-03-31 16:45
@c-h-j Thanks! Could you please attach the `nnimanager.log` of the experiment run with `--debug` ?  I suspect there are errors on nnimanager side which cause the pipe EOF.

**Comment by c-h-j** [comment] 2020-04-01 07:08
I just enable debug in the configuration file, without adding --debug in the nnictl command.
[nnimanager.log](https://send.firefox.com/download/735f6626d13011fa/#JA1ygtiwpubvHMjHfblcqA)The file is too large to upload as an attachment, I temporarily uploaded it to Firefox.
I will get the log through --debug, which may take a little time

**Comment by c-h-j** [comment] 2020-04-02 01:48
> @chj谢谢！您能否附上`nnimanager.log`实验运行的`--debug`？我怀疑nnimanager侧存在导致管道EOF的错误。

I added debug to the command nnictl and config and got the logs.
[Uploading nnimanager.zip…]()
[dispatcher.log](https://github.com/microsoft/nni/files/4418441/dispatcher.log)

**Comment by c-h-j** [comment] 2020-04-02 01:51
I added debug to the command nnictl and config and got the logs.
[nnimanager.zip](https://github.com/microsoft/nni/files/4418467/nnimanager.zip)
[dispatcher.log](https://github.com/microsoft/nni/files/4418468/dispatcher.log)

**Comment by chicm-ms** [comment] 2020-04-03 10:18
Hi @c-h-j ,
Thanks! 
Was nni still running when this problem happened?  (it can be checked through nni webui  or `nnictl experiment status` command)

And would you please run following commands and paste here the output?
```
nnictl log stderr XwrFRFwg
nnictl log stdout XwrFRFwg
```
The `XwrFRFwg` is the experiment id I found in nnimanager.log.
After investigating the log files, we suspect nnimanager process is crashed for some reason, the error log should be in the output of above commands since we can not find them in nnimanager.log

**Comment by c-h-j** [comment] 2020-04-07 03:24
@chicm-ms Sorry, the lease period of the machine is up. I need to lease the machine again. From the log, it seems that nnimanager exits when the ping command is sent to the master at 5 seconds intervals. Caused dispatcher to quit.
![473815805](https://user-images.githubusercontent.com/33076909/78626680-0c165480-78c2-11ea-9c9e-a698b98a75a9.jpg)

**Comment by c-h-j** [comment] 2020-04-09 08:12
@chicm-ms Sorry, I forgot to add debug,I executed x and got "Error: EMFILE: too many open files", this seems to be caused by insufficient file descriptors.The maximum value I got through x is 26315047, and the current value obtained by ulimit -n is 1048576, at the same time, dmesg also printed y, I do n’t know if it is related to nfs.
[log.zip](https://github.com/microsoft/nni/files/4454858/log.zip)

**Comment by chicm-ms** [comment] 2020-04-09 15:00
@c-h-j Thanks for the log files, there is no obvious clue regarding whether/why nnimanager crashed. Can you check whether nni crashed when the problem happened?  ( you can check through webui or `nnictl exeperiment status`)
I noticed you are using nni v1.1,  is it possible for you to upgrade to latest nni version?
I was trying to reproduce the problem with latest nni version but could not reproduce it yet, I will do more investigation on this. At the same time you can try with nni v1.4 if possible.

**Comment by chicm-ms** [comment] 2020-04-17 11:19
Hi @c-h-j  Please try with latest nni v1.5,  the 'too many open files' problem should have been fixed on v1.5.

**Comment by scarlett2018** [comment] 2020-06-01 03:06
> Hi @c-h-j Please try with latest nni v1.5, the 'too many open files' problem should have been fixed on v1.5.

@c-h-j got a chance tried this in v1.5? thanks.

**Comment by ragavvenkatesan** [comment] 2020-06-16 19:37
Same problem here: Everything was fine. A Few trials succeeded and all of a sudden server crashed. Tail of nnimanager.log fie in debug mode as was requested in the thread above. nni version 1.5 as requested above as well. 

`[06/16/2020, 07:31:31 PM] DEBUG (nni.msg_dispatcher_base/Thread-2) process_command: command: [CommandType.ReportMetricData], data: [OrderedDict([('parameter_id', 2), ('trial_job_id', 'mN2hg'), ('type', 'PERIODICAL'), ('sequence', 44), ('value', '0.09799999743700027')])]
[06/16/2020, 07:31:32 PM] DEBUG (nni.protocol/MainThread) Received command, header: [b'ME00000000000115']
[06/16/2020, 07:31:32 PM] DEBUG (nni.protocol/MainThread) Received command, data: [{"parameter_id": 2, "trial_job_id": "mN2hg", "type": "PERIODICAL", "sequence": 45, "value": "0.11349999904632568"}
]
[06/16/2020, 07:31:32 PM] DEBUG (nni.msg_dispatcher_base/Thread-2) process_command: command: [CommandType.ReportMetricData], data: [OrderedDict([('parameter_id', 2), ('trial_job_id', 'mN2hg'), ('type', 'PERIODICAL'), ('sequence', 45), ('value', '0.11349999904632568')])]
[06/16/2020, 07:31:33 PM] DEBUG (nni.protocol/MainThread) Received command, header: [b'ME00000000000115']
[06/16/2020, 07:31:33 PM] DEBUG (nni.protocol/MainThread) Received command, data: [{"parameter_id": 2, "trial_job_id": "mN2hg", "type": "PERIODICAL", "sequence": 46, "value": "0.10090000182390213"}
]
[06/16/2020, 07:31:33 PM] DEBUG (nni.msg_dispatcher_base/Thread-2) process_command: command: [CommandType.ReportMetricData], data: [OrderedDict([('parameter_id', 2), ('trial_job_id', 'mN2hg'), ('type', 'PERIODICAL'), ('sequence', 46), ('value', '0.10090000182390213')])]
[06/16/2020, 07:31:34 PM] DEBUG (nni.protocol/MainThread) Received command, header: [b'ME00000000000115']
[06/16/2020, 07:31:34 PM] DEBUG (nni.protocol/MainThread) Received command, data: [{"parameter_id": 2, "trial_job_id": "mN2hg", "type": "PERIODICAL", "sequence": 47, "value": "0.11349999904632568"}
]
[06/16/2020, 07:31:34 PM] DEBUG (nni.msg_dispatcher_base/Thread-2) process_command: command: [CommandType.ReportMetricData], data: [OrderedDict([('parameter_id', 2), ('trial_job_id', 'mN2hg'), ('type', 'PERIODICAL'), ('sequence', 47), ('value', '0.11349999904632568')])]
[06/16/2020, 07:31:35 PM] DEBUG (nni.protocol/MainThread) Received command, header: [b'ME00000000000115']
[06/16/2020, 07:31:35 PM] DEBUG (nni.protocol/MainThread) Received command, data: [{"parameter_id": 2, "trial_job_id": "mN2hg", "type": "PERIODICAL", "sequence": 48, "value": "0.11349999904632568"}
]
[06/16/2020, 07:31:35 PM] DEBUG (nni.msg_dispatcher_base/Thread-2) process_command: command: [CommandType.ReportMetricData], data: [OrderedDict([('parameter_id', 2), ('trial_job_id', 'mN2hg'), ('type', 'PERIODICAL'), ('sequence', 48), ('value', '0.11349999904632568')])]
[06/16/2020, 07:31:36 PM] DEBUG (nni.protocol/MainThread) Received command, header: [b'ME00000000000115']
[06/16/2020, 07:31:36 PM] DEBUG (nni.protocol/MainThread) Received command, data: [{"parameter_id": 2, "trial_job_id": "mN2hg", "type": "PERIODICAL", "sequence": 49, "value": "0.11349999904632568"}
]
[06/16/2020, 07:31:36 PM] DEBUG (nni.msg_dispatcher_base/Thread-2) process_command: command: [CommandType.ReportMetricData], data: [OrderedDict([('parameter_id', 2), ('trial_job_id', 'mN2hg'), ('type', 'PERIODICAL'), ('sequence', 49), ('value', '0.11349999904632568')])]
[06/16/2020, 07:31:36 PM] DEBUG (nni.protocol/MainThread) Received command, header: [b'PI00000000000000']
[06/16/2020, 07:31:36 PM] DEBUG (nni.protocol/MainThread) Received command, data: []
[06/16/2020, 07:31:36 PM] DEBUG (nni.msg_dispatcher_base/Thread-1) process_command: command: [CommandType.Ping], data: []
[06/16/2020, 07:31:36 PM] DEBUG (nni.protocol/MainThread) Received command, header: [b'']
[06/16/2020, 07:31:36 PM] DEBUG (nni.protocol/MainThread) Pipe EOF encountered
[06/16/2020, 07:31:36 PM] INFO (nni.msg_dispatcher_base/MainThread) Dispatcher exiting...
[06/16/2020, 07:31:39 PM] INFO (nni.msg_dispatcher_base/MainThread) Terminated by NNI manager`

**Comment by scarlett2018** [comment] 2021-06-10 01:28
@c-h-j  @ragavvenkatesan - ping to check whether this is still a problem on your side, thanks.

**Closed** 2022-04-06 02:46 UTC
Labels: bug, customer raised, waiting customer confirm, NAS, close-as-overdue
