### ISSUE TITLE
slow rendering of webui

### ISSUE THREAD

**Issue by QuanluZhang** [microsoft/nni#590] opened 2019-01-10 02:19 UTC
when using https://github.com/Microsoft/nni/blob/master/examples/trials/mnist/config_pai.yml, and set trialConcurrency to 50, 2 issues were found. 

**In scope**
Issue 1: The rendering becomes very slow. 

**Out of scope**
Issue 2: The update of trial jobs' state has high latency compared to the states from pai's webui. **This issue will cover in #592** 

The original problem is not able to reproduce. We had discussed and would like to fix the problem in 2 aspects:
- reduce the loading actions and frequency
- batch get results

**Exit Criteria**
Precondition: mock 6000 trial with 100 intermediate results for each (yuge)

**Comment by jpat6179** [comment] 2019-01-10 03:18
Hello

**Comment by scarlett2018** [comment] 2019-04-10 01:47
Are we still seeing this in v0.6? how slow it is?

**Comment by QuanluZhang** [comment] 2019-04-10 01:49
"the update of trial jobs' state has high latency compared to the states from pai's webui" this part will be fixed in v0.7 by @chicm-ms

**Comment by scarlett2018** [comment] 2019-04-10 02:04
> "the update of trial jobs' state has high latency compared to the states from pai's webui" this part will be fixed in v0.7 by @chicm-ms

Thanks, updating this Issue's scope in the first comment.

**Comment by scarlett2018** [comment] 2019-07-01 02:44
Assign to Quanlu to verify whether this is still an issue for the latest build.

**Comment by scarlett2018** [comment] 2019-07-22 02:53
@LeonardoWang had verified the issue is no longer reproducible, closing it.

**Comment by ultmaster** [comment] 2019-10-20 06:58
Tracked in #1425. Closing it.

**Closed by ultmaster** 2019-10-20 06:58 UTC
Labels: enhancement
