### ISSUE TITLE
Run example via docker

### ISSUE THREAD

**Issue by Garfield2013** [microsoft/nni#1561] opened 2019-09-19 19:09 UTC
I'm new to Docker - so any help would be highly appreciated!

`docker run msranni/nni python /nni/examples/trials/mnist/mnist.py`

Error response from daemon: OCI runtime create failed: container_linux.go:345: starting container process caused "exec: \"python\": executable file not found in $PATH": unknown.

What do I do wrong here?

**Comment by liuzhe-lz** [comment] 2019-09-20 02:10
Try changing `python` to `python3`.

**Comment by Garfield2013** [comment] 2019-09-20 08:39
I only have one version of Python installed:
python --version
Python 3.6.2

**Comment by liuzhe-lz** [comment] 2019-09-20 08:42
@Garfield2013 You are using the Python inside docker image, not the Python of your host system.

**Comment by Garfield2013** [comment] 2019-09-20 08:58
From the DOC: [https://nni.readthedocs.io/en/latest/Tutorial/HowToUseDocker.html](https://nni.readthedocs.io/en/latest/Tutorial/HowToUseDocker.html)

For example, you could start a new docker container from following command:
docker run -i -t -p [hostPort]:[containerPort] [image]

I just tried: docker run -i -t -p 12000:12000 msranni/nni
root@c8ecb7b2df45:~# 

I think it works? But now what / what does this means?
http://localhost:12000/ in my browser doesn't show anything?

**Comment by Garfield2013** [comment] 2019-09-20 09:38
I now found this linux cmd from the GitHub page:
`nnictl create --config nni/examples/trials/mnist/config.yml`

But it just returns:ERROR: Please set correct config path!

Why make the instructions to this project so bad?? No matter if I read the GitHub or the official NNI Docs I still can't find and follow some simple steps to make it work and run examples when using docker??

**Comment by SparkSnail** [comment] 2019-09-20 10:06
Hi,
   NNI's offical image does not contain example, you should download example from github first, and then run the `nnictl` command to start an experiment. [refer](https://nni.readthedocs.io/en/latest/Tutorial/HowToUseDocker.html#step3-run-nni-in-docker-container)
   Note that the experiment should use the port you mapped when you start your docker contatiner, for example, use `nnictl create --config nni/examples/trials/mnist/config.yml --port 12000` to start an experiment in your container, then you can see the web UI from http://localhost:12000.

**Comment by Garfield2013** [comment] 2019-09-20 12:06
1. I was able to run to website
2. I needed to run: pip install dill (it failed due to some pickling process...)
3. As you can see below - the website still fails when running the MNIST example?

[9/20/2019, 11:57:41 AM] INFO [ 'Datastore initialization done' ]
[9/20/2019, 11:57:41 AM] INFO [ 'Rest server listening on: http://0.0.0.0:12000' ]
[9/20/2019, 11:57:41 AM] INFO [ 'RestServer start' ]
[9/20/2019, 11:57:41 AM] INFO [ 'Construct local machine training service.' ]
[9/20/2019, 11:57:41 AM] INFO [ 'RestServer base port is 12000' ]
[9/20/2019, 11:57:43 AM] INFO [ 'NNIManager setClusterMetadata, key: trial_config, value: {"gpuNum":0,"codeDir":"/root/nni/examples/trials/mnist/.","command":"python3 mnist.py"}' ]
[9/20/2019, 11:57:43 AM] INFO [ 'required GPU number is 0' ]
[9/20/2019, 11:57:43 AM] INFO [ 'Starting experiment: xx5GAVwc' ]
[9/20/2019, 11:57:43 AM] INFO [ 'Change NNIManager status from: INITIALIZED to: RUNNING' ]
[9/20/2019, 11:57:43 AM] INFO [ 'Add event listeners' ]
[9/20/2019, 11:57:43 AM] INFO [ 'Run local machine training service.' ]
[9/20/2019, 11:57:44 AM] INFO [ 'NNIManager received command from dispatcher: ID, ' ]
[9/20/2019, 11:57:44 AM] INFO [ 'NNIManager received command from dispatcher: TR, {"parameter_id": 0, "parameters": {"learning_rate": 0.1, "hidden_size": 124, "dropout_rate": 0.8522341876312933, "batch_size": 1, "conv_size": 5}, "parameter_source": "algorithm", "parameter_index": 0}' ]
[9/20/2019, 11:57:48 AM] INFO [ 'submitTrialJob: form: {"jobType":"TRIAL","hyperParameters":{"value":"{\\"parameter_id\\": 0, \\"parameters\\": {\\"learning_rate\\": 0.1, \\"hidden_size\\": 124, \\"dropout_rate\\": 0.8522341876312933, \\"batch_size\\": 1, \\"conv_size\\": 5}, \\"parameter_source\\": \\"algorithm\\", \\"parameter_index\\": 0}","index":0}}' ]
[9/20/2019, 11:57:53 AM] INFO [ 'Trial job ahThA status changed from WAITING to RUNNING' ]
[9/20/2019, 11:57:58 AM] INFO [ 'Trial job ahThA status changed from RUNNING to FAILED' ]
[9/20/2019, 11:57:58 AM] INFO [ 'NNIManager received command from dispatcher: TR, {"parameter_id": 1, "parameters": {"learning_rate": 0.01, "hidden_size": 1024, "dropout_rate": 0.7045073313585446, "batch_size": 16, "conv_size": 2}, "parameter_source": "algorithm", "parameter_index": 0}' ]
[9/20/2019, 11:58:03 AM] INFO [ 'submitTrialJob: form: {"jobType":"TRIAL","hyperParameters":{"value":"{\\"parameter_id\\": 1, \\"parameters\\": {\\"learning_rate\\": 0.01, \\"hidden_size\\": 1024, \\"dropout_rate\\": 0.7045073313585446, \\"batch_size\\": 16, \\"conv_size\\": 2}, \\"parameter_source\\": \\"algorithm\\", \\"parameter_index\\": 0}","index":0}}' ]
[9/20/2019, 11:58:08 AM] INFO [ 'Trial job uwyxU status changed from WAITING to RUNNING' ]
[9/20/2019, 11:58:13 AM] INFO [ 'Trial job uwyxU status changed from RUNNING to FAILED' ]
[9/20/2019, 11:58:14 AM] INFO [ 'NNIManager received command from dispatcher: TR, {"parameter_id": 2, "parameters": {"learning_rate": 0.01, "hidden_size": 124, "dropout_rate": 0.7219161311124843, "batch_size": 1, "conv_size": 2}, "parameter_source": "algorithm", "parameter_index": 0}' ]
[9/20/2019, 11:58:19 AM] INFO [ 'submitTrialJob: form: {"jobType":"TRIAL","hyperParameters":{"value":"{\\"parameter_id\\": 2, \\"parameters\\": {\\"learning_rate\\": 0.01, \\"hidden_size\\": 124, \\"dropout_rate\\": 0.7219161311124843, \\"batch_size\\": 1, \\"conv_size\\": 2}, \\"parameter_source\\": \\"algorithm\\", \\"parameter_index\\": 0}","index":0}}' ]
[9/20/2019, 11:58:24 AM] INFO [ 'Trial job iW2wx status changed from WAITING to FAILED' ]
[9/20/2019, 11:58:24 AM] INFO [ 'NNIManager received command from dispatcher: TR, {"parameter_id": 3, "parameters": {"learning_rate": 0.0001, "hidden_size": 1024, "dropout_rate": 0.7710976162131247, "batch_size": 4, "conv_size": 7}, "parameter_source": "algorithm", "parameter_index": 0}' ]
[9/20/2019, 11:58:29 AM] INFO [ 'submitTrialJob: form: {"jobType":"TRIAL","hyperParameters":{"value":"{\\"parameter_id\\": 3, \\"parameters\\": {\\"learning_rate\\": 0.0001, \\"hidden_size\\": 1024, \\"dropout_rate\\": 0.7710976162131247, \\"batch_size\\": 4, \\"conv_size\\": 7}, \\"parameter_source\\": \\"algorithm\\", \\"parameter_index\\": 0}","index":0}}' ]
[9/20/2019, 11:58:34 AM] INFO [ 'Trial job sKgFZ status changed from WAITING to FAILED' ]
[9/20/2019, 11:58:34 AM] INFO [ 'NNIManager received command from dispatcher: TR, {"parameter_id": 4, "parameters": {"learning_rate": 0.1, "hidden_size": 512, "dropout_rate": 0.8930232370676324, "batch_size": 16, "conv_size": 7}, "parameter_source": "algorithm", "parameter_index": 0}' ]
[9/20/2019, 11:58:39 AM] INFO [ 'submitTrialJob: form: {"jobType":"TRIAL","hyperParameters":{"value":"{\\"parameter_id\\": 4, \\"parameters\\": {\\"learning_rate\\": 0.1, \\"hidden_size\\": 512, \\"dropout_rate\\": 0.8930232370676324, \\"batch_size\\": 16, \\"conv_size\\": 7}, \\"parameter_source\\": \\"algorithm\\", \\"parameter_index\\": 0}","index":0}}' ]
[9/20/2019, 11:58:44 AM] INFO [ 'Trial job Cr0ck status changed from WAITING to FAILED' ]
[9/20/2019, 11:58:44 AM] INFO [ 'NNIManager received command from dispatcher: TR, {"parameter_id": 5, "parameters": {"learning_rate": 0.001, "hidden_size": 124, "dropout_rate": 0.7926513650438656, "batch_size": 32, "conv_size": 5}, "parameter_source": "algorithm", "parameter_index": 0}' ]
[9/20/2019, 11:58:49 AM] INFO [ 'submitTrialJob: form: {"jobType":"TRIAL","hyperParameters":{"value":"{\\"parameter_id\\": 5, \\"parameters\\": {\\"learning_rate\\": 0.001, \\"hidden_size\\": 124, \\"dropout_rate\\": 0.7926513650438656, \\"batch_size\\": 32, \\"conv_size\\": 5}, \\"parameter_source\\": \\"algorithm\\", \\"parameter_index\\": 0}","index":0}}' ]
[9/20/2019, 11:58:54 AM] INFO [ 'Trial job n3IC4 status changed from WAITING to FAILED' ]
[9/20/2019, 11:58:54 AM] INFO [ 'NNIManager received command from dispatcher: TR, {"parameter_id": 6, "parameters": {"learning_rate": 0.001, "hidden_size": 124, "dropout_rate": 0.8434550546215369, "batch_size": 16, "conv_size": 5}, "parameter_source": "algorithm", "parameter_index": 0}' ]
[9/20/2019, 11:58:59 AM] INFO [ 'submitTrialJob: form: {"jobType":"TRIAL","hyperParameters":{"value":"{\\"parameter_id\\": 6, \\"parameters\\": {\\"learning_rate\\": 0.001, \\"hidden_size\\": 124, \\"dropout_rate\\": 0.8434550546215369, \\"batch_size\\": 16, \\"conv_size\\": 5}, \\"parameter_source\\": \\"algorithm\\", \\"parameter_index\\": 0}","index":0}}' ]
[9/20/2019, 11:59:04 AM] INFO [ 'Trial job Tga03 status changed from WAITING to FAILED' ]
[9/20/2019, 11:59:04 AM] INFO [ 'NNIManager received command from dispatcher: TR, {"parameter_id": 7, "parameters": {"learning_rate": 0.001, "hidden_size": 124, "dropout_rate": 0.6202327677874316, "batch_size": 1, "conv_size": 3}, "parameter_source": "algorithm", "parameter_index": 0}' ]
[9/20/2019, 11:59:09 AM] INFO [ 'submitTrialJob: form: {"jobType":"TRIAL","hyperParameters":{"value":"{\\"parameter_id\\": 7, \\"parameters\\": {\\"learning_rate\\": 0.001, \\"hidden_size\\": 124, \\"dropout_rate\\": 0.6202327677874316, \\"batch_size\\": 1, \\"conv_size\\": 3}, \\"parameter_source\\": \\"algorithm\\", \\"parameter_index\\": 0}","index":0}}' ]
[9/20/2019, 11:59:14 AM] INFO [ 'Trial job jMMm3 status changed from WAITING to FAILED' ]
[9/20/2019, 11:59:14 AM] INFO [ 'NNIManager received command from dispatcher: TR, {"parameter_id": 8, "parameters": {"learning_rate": 0.0001, "hidden_size": 1024, "dropout_rate": 0.7110290462121701, "batch_size": 32, "conv_size": 3}, "parameter_source": "algorithm", "parameter_index": 0}' ]
[9/20/2019, 11:59:19 AM] INFO [ 'submitTrialJob: form: {"jobType":"TRIAL","hyperParameters":{"value":"{\\"parameter_id\\": 8, \\"parameters\\": {\\"learning_rate\\": 0.0001, \\"hidden_size\\": 1024, \\"dropout_rate\\": 0.7110290462121701, \\"batch_size\\": 32, \\"conv_size\\": 3}, \\"parameter_source\\": \\"algorithm\\", \\"parameter_index\\": 0}","index":0}}' ]
[9/20/2019, 11:59:24 AM] INFO [ 'Trial job amC8G status changed from WAITING to FAILED' ]
[9/20/2019, 11:59:24 AM] INFO [ 'NNIManager received command from dispatcher: TR, {"parameter_id": 9, "parameters": {"learning_rate": 0.001, "hidden_size": 1024, "dropout_rate": 0.7117021520919176, "batch_size": 1, "conv_size": 2}, "parameter_source": "algorithm", "parameter_index": 0}' ]
[9/20/2019, 11:59:29 AM] INFO [ 'submitTrialJob: form: {"jobType":"TRIAL","hyperParameters":{"value":"{\\"parameter_id\\": 9, \\"parameters\\": {\\"learning_rate\\": 0.001, \\"hidden_size\\": 1024, \\"dropout_rate\\": 0.7117021520919176, \\"batch_size\\": 1, \\"conv_size\\": 2}, \\"parameter_source\\": \\"algorithm\\", \\"parameter_index\\": 0}","index":0}}' ]
[9/20/2019, 11:59:34 AM] INFO [ 'Trial job nb13Q status changed from WAITING to FAILED' ]
[9/20/2019, 11:59:34 AM] INFO [ 'Change NNIManager status from: RUNNING to: NO_MORE_TRIAL' ]
[9/20/2019, 11:59:34 AM] INFO [ 'Change NNIManager status from: NO_MORE_TRIAL to: DONE' ]
[9/20/2019, 11:59:34 AM] INFO [ 'NNIManager received command from dispatcher: TR, {"parameter_id": 10, "parameters": {"learning_rate": 0.01, "hidden_size": 124, "dropout_rate": 0.7809111780098358, "batch_size": 4, "conv_size": 7}, "parameter_source": "algorithm", "parameter_index": 0}' ]
[9/20/2019, 11:59:34 AM] INFO [ 'Experiment done.' ]

**Comment by SparkSnail** [comment] 2019-09-20 12:51
Could you please provide your trial's log content? You could find the logPath in webui or use `nnictl log trial` in your terminal.

**Comment by Garfield2013** [comment] 2019-09-20 14:19
I'm not used to Linux - But I guess it is a list of log files? But how do I open them?

root@c8ecb7b2df45:~# nnictl log trial
id:amC8G path:file://localhost:/root/nni/experiments/xx5GAVwc/trials/amC8G
id:ahThA path:file://localhost:/root/nni/experiments/xx5GAVwc/trials/ahThA
id:uwyxU path:file://localhost:/root/nni/experiments/xx5GAVwc/trials/uwyxU
id:jMMm3 path:file://localhost:/root/nni/experiments/xx5GAVwc/trials/jMMm3
id:Tga03 path:file://localhost:/root/nni/experiments/xx5GAVwc/trials/Tga03
id:nb13Q path:file://localhost:/root/nni/experiments/xx5GAVwc/trials/nb13Q
id:n3IC4 path:file://localhost:/root/nni/experiments/xx5GAVwc/trials/n3IC4
id:sKgFZ path:file://localhost:/root/nni/experiments/xx5GAVwc/trials/sKgFZ
id:Cr0ck path:file://localhost:/root/nni/experiments/xx5GAVwc/trials/Cr0ck
id:iW2wx path:file://localhost:/root/nni/experiments/xx5GAVwc/trials/iW2wx
root@c8ecb7b2df45:~# localhost:/root/nni/experiments/xx5GAVwc/trials/amC8G

**Comment by Garfield2013** [comment] 2019-09-20 14:22
Btw - what I'm really interested in is to run as many different NN/architectures on my own custom dataset... Can you point me in any direction how I accomplish a task like that with NNI?

**Comment by SparkSnail** [comment] 2019-09-20 14:35
You could use `cat /root/nni/experiments/xx5GAVwc/trials/amC8G` command to show the content of file in Linux, or you could download the file to local machine and open it with notepad.
NNI is easy to be used for your own dataset, you just need to write your own trial code using NNI's API. [refer](https://nni.readthedocs.io/en/latest/TrialExample/Trials.html)

**Comment by Garfield2013** [comment] 2019-09-20 15:05
root@c8ecb7b2df45:~/nni/experiments/xx5GAVwc/trials/amC8G# ls
parameter.cfg  run.sh  stderr
root@c8ecb7b2df45:~/nni/experiments/xx5GAVwc/trials/amC8G# cat parameter.cfg
{"parameter_id": 8, "parameters": {"learning_rate": 0.0001, "hidden_size": 1024, "dropout_rate": 0.7110290462121701, "batch_size": 32, "conv_size": 3}, "parameter_source": "algorithm", "parameter_index": 0}root@c8ecb7b2df45:~/nni/experiments/xx5GAVwc/trials/amC8G# cat run.sh
#!/bin/bash
cd /root/nni/examples/trials/mnist/.
export NNI_PLATFORM=local
export NNI_EXP_ID=xx5GAVwc
export NNI_SYS_DIR=/root/nni/experiments/xx5GAVwc/trials/amC8G
export NNI_TRIAL_JOB_ID=amC8G
export NNI_OUTPUT_DIR=/root/nni/experiments/xx5GAVwc/trials/amC8G
export NNI_TRIAL_SEQ_ID=8
export MULTI_PHASE=false
export CUDA_VISIBLE_DEVICES=-1
eval python3 mnist.py 2>/root/nni/experiments/xx5GAVwc/trials/amC8G/stderr
echo $? `date +%s%3N` >/root/nni/experiments/xx5GAVwc/trials/amC8G/.nni/stateroot@c8ecb7b2df45:~/nni/experiments/xx5GAVwc/trials/amC8G# cat stderr
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/usr/lib/python3.5/imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "/usr/lib/python3.5/imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: libcuda.so.1: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "mnist.py", line 9, in <module>
    import tensorflow as tf
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/__init__.py", line 22, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/usr/lib/python3.5/imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "/usr/lib/python3.5/imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: libcuda.so.1: cannot open shared object file: No such file or directory


Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/install_sources#common_installation_problems

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.
root@c8ecb7b2df45:~/nni/experiments/xx5GAVwc/trials/amC8G#

**Comment by SparkSnail** [comment] 2019-09-21 03:59
Hi @Garfield2013,
    This problem might caused by the CUDA environment in your machine. NNI's official docker iamge use `nvidia/cuda:9.0-cudnn7-runtime-ubuntu16.04` backend, and installed tensorflow-gpu as the tensorflow environment. Does your machine have GPU and installed CUDA and cuDNN environment? If you have installed CUDA and cuDNN,  you may need to use `nvidia-docker` command to start docker. 
    If your machine do not have GPU and CUDA environment, a workaround way is to use `python3 -m pip uninstall tensorflow-gpu` command to uninstall tensorflow-gpu first, and then use `python3 -m pip install tensorflow` to install tensorflow. Then you can use `nnictl` command to use NNI. Note that you could not use GPU in this way.

**Comment by Garfield2013** [comment] 2019-09-21 07:37
My laptop contains a GeForce 1050 Ti and all installed: Tensorflow-GPU
1.12, Cudnn 7.4 and Cuda 10.0.

But isn’t the entire point of Docker that it runs inside a 100% isolated
container/process - so why would it be possible to generate a conflict
(when is has its own filesystem etc)?

Actually it is my first experience with Docker (and NNI) and so far I’m
really not impressed - I thought everything would go so smooth without any
issues at all.

So what would you suggest I try now? What are the nvidia-commands? Do I
need another image as well? What do everybody else do (this project has
over 3.000 stars?)

Thank you so much for you assistance my friend.

lør. 21. sep. 2019 kl. 07.59 skrev SparkSnail <notifications@github.com>:

**Comment by SparkSnail** [comment] 2019-09-21 12:52
Hi,
    The Tensorflow-gpu environment problem is caused by the docker platform you are using. The default `docker` command does not support GPU and CUDA environment, so we could not use Tensorflow-gpu in the container started by `docker` command.
For your question, there are a few solutions:
1.Still use NNI's official image `msranni/nni`, replace the tensorflow version. After you started the container using `docker` command, then use `python3 -m pip uninstall tensorflow-gpu` command to uninstall the tensorflow environment provided by NNI, reinstall tensorflow by `python3 -m pip install tensorflow`. After you install the tensorflow environment, you could enter python3 bash command, and use `import tensorflow` to test the environment. This is the quick way to run NNI's example, but you could not use GPU version of tensorflow.
2. Still use NNI's official image `msranni/nni`, and install `nvidia-docker` environment in your own machine, then use `nvidia-docker` command to start the iamge. [refer](https://github.com/NVIDIA/nvidia-docker). This way is suggested.
3. Do not use NNI's official image, find a docker image with tensorflow which works fine in your own machine, for example you could use the tensorflow's official image. Then you should use `python3 -m pip install nni` in the image to prepare NNI environment. Attention that if you don't have `nvidia-docker` environment in your machine, you could only use CPU version of docker.
4. Do not use Docker, just run NNI in your own machine. Firstly, you should make sure your own machine have a healthy tensorflow environment, then you could install NNI from `python3 -m pip install nni` command.  Of course, you could uninstall NNI using `python3 -m pip uninstall nni` if you do not want to keep NNI. Most people run NNI in this way.
Regards

**Comment by Garfield2013** [comment] 2019-09-22 13:57
That you so much for your great response!

1. I'm still about to give up though ... I'm on Windows on my localhost and can't  install: [https://github.com/NVIDIA/nvidia-docker](https://github.com/NVIDIA/nvidia-docker) ... 

2. I also checked out Nvidia's containers for at solution: [https://ngc.nvidia.com/catalog/containers?query=&quickFilter=deep-learning&filters=&orderBy=](https://ngc.nvidia.com/catalog/containers?query=&quickFilter=deep-learning&filters=&orderBy=)

3. I also tried to install NNI directly on my Windows Laptop:

```
python -m pip install --upgrade nni
git clone -b v1.0 https://github.com/Microsoft/nni.git
cd nni
powershell -ExecutionPolicy Bypass -file install.ps1
nnictl create --config nni\examples\trials\mnist\config_windows.yml
```

`output: ERROR: Please set correct config path!`

4. 
```
PS C:\Users\TB\Downloads\nni> cd .\examples\trials\mnist\
PS C:\Users\TB\Downloads\nni\examples\trials\mnist> nnictl create --config config_windows.yml
INFO: expand searchSpacePath: search_space.json to C:\Users\TB\Downloads\nni\examples\trials\mnist\search_space.json
INFO: expand codeDir: . to C:\Users\TB\Downloads\nni\examples\trials\mnist\.
INFO: Starting restful server...
Traceback (most recent call last):
  File "c:\program files\python36\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\program files\python36\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Program Files\Python36\Scripts\nnictl.exe\__main__.py", line 9, in <module>
  File "c:\program files\python36\lib\site-packages\nni_cmd\nnictl.py", line 217, in parse_args
    args.func(args)
  File "c:\program files\python36\lib\site-packages\nni_cmd\launcher.py", line 554, in create_experiment
    launch_experiment(args, experiment_config, 'new', config_file_name)
  File "c:\program files\python36\lib\site-packages\nni_cmd\launcher.py", line 377, in launch_experiment
    rest_process, start_time = start_rest_server(args.port, experiment_config['trainingServicePlatform'], mode, config_file_name, experiment_id, log_dir, log_level)
  File "c:\program files\python36\lib\site-packages\nni_cmd\launcher.py", line 137, in start_rest_server
    process = Popen(cmds, cwd=entry_dir, stdout=stdout_file, stderr=stderr_file, creationflags=CREATE_NEW_PROCESS_GROUP)
  File "c:\program files\python36\lib\subprocess.py", line 707, in __init__
    restore_signals, start_new_session)
  File "c:\program files\python36\lib\subprocess.py", line 992, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified
PS C:\Users\TB\Downloads\nni\examples\trials\mnist>
```

I only tried to use Docker - because it thought it would be a "safe heaven" ...But not in this case.

5. If you can provide me with the code I need just to make it work directly on my Windows laptop - I would be very happy :-)

6. What is the difference between NNI and Uber's [Ludwig ](https://github.com/uber/ludwig) framework?

**Comment by SparkSnail** [comment] 2019-09-27 10:30
Hi,
    For the fourth problem, it might caused by the subprocess module in python, maybe you could refer the [issue](https://github.com/jupyter/notebook/issues/4079) to find the solution in your machine.
    NNI is a toolkit of AutoML, used for neural architecture search and hyper-parameter tuning.

**Comment by Garfield2013** [comment] 2019-10-14 10:36
I gaved up on NNI... way to buggy for the average user...

**Comment by ultmaster** [comment] 2019-10-20 02:59
Sorry about that. Closing this issue.

**Closed by ultmaster** 2019-10-20 02:59 UTC
Labels: customer raised
