### ISSUE TITLE
It seems to only run on a single gpu, nni will always waiting when I use two gpus

### ISSUE THREAD

**Issue by Royzon** [microsoft/nni#1269] opened 2019-07-07 08:00 UTC
It seems to only run on a single gpu, nni will always waiting when I use two gpus.  and here are my changes in config.yml:
trial:
  command: CUDA_VISIBLE_DEVICES=5,6 python3 train_nni.py
  codeDir: .
  gpuNum: 2

**Comment by scarlett2018** [comment] 2019-07-08 02:47
@Royzon - may you remove the  `CUDA_VISIBLE_DEVICES=5,6` settings and let us know the result?

**Comment by Royzon** [comment] 2019-07-08 07:42
@scarlett2018 thanks for advice, It does not work well now even I delete the CUDA_VISIBLE_DEVICES=5,6.
And I am quite sure that my code will work without nni, also attach my multi-gpus related codes here:

parser.add_argument('--gpus', type=str, default='5,6', help='the gpus will be used, e.g "0,1,2,3"')

ctx = mx.cpu() if params['gpus'] is None else [mx.gpu(int(i)) for i in params['gpus'].split(',')]

mod = mxnet.mod.Module(
            symbol=sym,
            context=ctx)

**Comment by chicm-ms** [comment] 2019-07-08 08:08
@Royzon  Is it the same error as before after you removing ```CUDA_VISIBLE_DEVICES=5,6``` ? NNI automatically add CUDA_VISIBLE_DEVICES env var using nni scheduled device indices to your trial job.

I am not familiar with MXNET,  but would you please check if the mx.gpu(5)  really work when ```CUDA_VISIBLE_DEVICES=5,6``` is set?  It seems that the device indices could be ```0 and 1``` inside your job if you set ```CUDA_VISIBLE_DEVICES=5,6```

**Comment by Royzon** [comment] 2019-07-11 07:35
but it still can use only one and the id=1, even though I changed it as CUDA_VISIBLE_DEVICES=0,1.

**Comment by xingwangsfu** [comment] 2019-07-18 13:02
I can confirm this problem. I have 2 available gpus, whose indices are 0 and 2.  I tested on mnist example. First, I export CUDA_VISIBLE_DEVICES=0,2. Then,  I set trialConcurrency: 2 and gpuNum: 2.  Finally I checked the GPU usage with 'nvidia-smi -l'.  Only GPU 0 was working and took all the GPU memory while a small portion of GPU 2's memory was used and its usage was always 0.  I tested several tuners: Random and Evolution.

**Comment by chicm-ms** [comment] 2019-09-03 08:25
@xingwangsfu How did you export CUDA_VISIBLE_DEVICES=0,2 ?  CUDA_VISIBLE_DEVICES env var should not be set manually for your trial jobs since nni gpu scheduler automatically set CUDA_VISIBLE_DEVICES env var for your trial jobs. If it is set in trial job command line, it conflicts with nni gpu scheduler. 
If you would like to specify gpu devices for trial jobs,  you can use **gpuIndices** configuration ( https://nni.readthedocs.io/en/latest/Tutorial/ExperimentConfig.html)

**Comment by chicm-ms** [comment] 2019-09-03 09:14
@Royzon Is there any other process using your GPUs, if it is the case, you can set **useActiveGpu** to true in order to allow your trial jobs using the GPUs being used by other processes.

**Comment by ultmaster** [comment] 2019-10-20 04:00
@Royzon Any updates? thanks.

**Comment by chicm-ms** [comment] 2019-12-24 05:09
@Royzon 
Closing this issue for now since no feedback from you, if you still have the problem, you can reopen it.

**Closed by chicm-ms** 2019-12-24 05:09 UTC
Labels: customer raised, investigation, waiting customer confirm
