### ISSUE TITLE
error encountered when use NNI in multi process

### ISSUE THREAD

**Issue by tabVersion** [microsoft/nni#2743] opened 2020-07-28 09:05 UTC
**Environment**:
- NNI version: 1.7.0
- NNI mode (local|remote|pai): pai
- Client OS: ubuntu
- Server OS (for remote mode only):
- Python version: 3.6
- PyTorch/TensorFlow version: pyTorch 1.4
- Is conda/virtualenv/venv used?:
- Is running in Docker?: Yes

**Log message**:
 - nnimanager.log: 
 - dispatcher.log:
 - nnictl stdout and stderr:

  ```bash
  nni.get_next_parameters() must be called before nni.report_final_result()
   ```

**What issue meet, what's expected?**:

For example:
In yaml: Command: python3 A.py
In A.py: os.system('python3 B.py')
I use `nni.get_next_parameter()` in A.py before `os.system` and use `nni.report_final_result()` in B.py. And I got the error.

Hope NNI can expose `parameterID` when requiring new parameters and allow users to report results with the ID.

**How to reproduce it?**: 

**Additional information**:

**Comment by ultmaster** [comment] 2020-07-29 03:06
By design. Won't fix.

**Closed** 2020-07-29 03:37 UTC
