### ISSUE TITLE
Job endTime may be smaller than startTime

### ISSUE THREAD

**Issue by SparkSnail** [microsoft/nni#452] opened 2018-12-05 08:26 UTC
If some jobs runs very quick, jobs' endTime may be smaller than startTime in remote and pai mode.
![image](https://user-images.githubusercontent.com/22682999/49500101-d109a880-f8aa-11e8-9e3f-e220f917bf12.png)
![image](https://user-images.githubusercontent.com/22682999/49500145-f1d1fe00-f8aa-11e8-9b57-c3cb7f379cc9.png)

**Comment by chicm-ms** [comment] 2018-12-05 08:35
This problem is caused by that:  endTime is retrieved from training service system and startTime is retrieved from nnimanager system.  The two systems may have time differences.
This problem will be fixed later.

**Closed** 2019-07-03 09:15 UTC
Labels: priority/p2
