### ISSUE TITLE
Missing key: 'sshKeyPath'

### ISSUE THREAD

**Issue by forhonourlx** [microsoft/nni#1928] opened 2020-01-06 18:48 UTC
Hi, 
I am trying ssh remote mode on Ubuntu NNI1.3:
```
machineList:
  - ip: 192.168.1.102
    username: simon
    passwd: 1
    #port can be skip if using default ssh port 22
    port: 22
  - ip: 192.168.1.3
    username: simon
    passwd: 1
    port: 22
```
Got:
```
Missing key: 'sshKeyPath'
```
Could somebody help?
Thanks in advance.

**Comment by SparkSnail** [comment] 2020-01-07 02:18
Hi @forhonourlx , could you try using 
```
machineList:
  - ip: 192.168.1.102
    username: simon
    passwd: "1"
    #port can be skip if using default ssh port 22
    port: 22
  - ip: 192.168.1.3
    username: simon
    passwd: "1"
    port: 22
```
This problem might caused by the value type of passwd, the pure digital numbers in passwd might be recognized as `Number` type, since NNI only support `String` type in passwd field.

**Comment by forhonourlx** [comment] 2020-01-07 05:51
Hi @SparkSnail,
Thank you for your help, `passwd: "1"` works.
And another exception is raised, what is attribute 'last_line'?
```
$ nnictl create --config config_ssh.yml --port 8082
INFO: Starting restful server...
Traceback (most recent call last):
  File "/home/simon/anaconda3/lib/python3.6/site-packages/nni_annotation/code_generator.py", line 349, in parse
    transformer.visit(ast_tree)
  File "/home/simon/anaconda3/lib/python3.6/site-packages/nni_annotation/code_generator.py", line 280, in visit
    return self._visit_children(node)
  File "/home/simon/anaconda3/lib/python3.6/site-packages/nni_annotation/code_generator.py", line 330, in _visit_children
    self.generic_visit(node)
  File "/home/simon/anaconda3/lib/python3.6/ast.py", line 308, in generic_visit
    value = self.visit(value)
  File "/home/simon/anaconda3/lib/python3.6/site-packages/nni_annotation/code_generator.py", line 297, in visit
    return self._visit_children(node)
  File "/home/simon/anaconda3/lib/python3.6/site-packages/nni_annotation/code_generator.py", line 330, in _visit_children
    self.generic_visit(node)
  File "/home/simon/anaconda3/lib/python3.6/ast.py", line 308, in generic_visit
    value = self.visit(value)
  File "/home/simon/anaconda3/lib/python3.6/site-packages/nni_annotation/code_generator.py", line 293, in visit
    return replace_variable_node(node, annotation)
  File "/home/simon/anaconda3/lib/python3.6/site-packages/nni_annotation/code_generator.py", line 233, in replace_variable_node
    assert test_variable_equal(node.targets[0], name), 'Annotated variable has wrong name'
AssertionError: Annotated variable has wrong name

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/simon/anaconda3/lib/python3.6/site-packages/nni_annotation/__init__.py", line 109, in _expand_file_annotations
    annotated_code = code_generator.parse(src.read(), nas_mode)
  File "/home/simon/anaconda3/lib/python3.6/site-packages/nni_annotation/code_generator.py", line 351, in parse
    raise RuntimeError('%d: %s' % (ast_tree.last_line, exc.args[0]))
AttributeError: 'Module' object has no attribute 'last_line'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/simon/anaconda3/bin/nnictl", line 8, in <module>
    sys.exit(parse_args())
  File "/home/simon/anaconda3/lib/python3.6/site-packages/nni_cmd/nnictl.py", line 217, in parse_args
    args.func(args)
  File "/home/simon/anaconda3/lib/python3.6/site-packages/nni_cmd/launcher.py", line 509, in create_experiment
    launch_experiment(args, experiment_config, 'new', config_file_name)
  File "/home/simon/anaconda3/lib/python3.6/site-packages/nni_cmd/launcher.py", line 437, in launch_experiment
    code_dir = expand_annotations(experiment_config['trial']['codeDir'], path, nas_mode=nas_mode)
  File "/home/simon/anaconda3/lib/python3.6/site-packages/nni_annotation/__init__.py", line 94, in expand_annotations
    annotated |= _expand_file_annotations(src_path, dst_path, nas_mode)
  File "/home/simon/anaconda3/lib/python3.6/site-packages/nni_annotation/__init__.py", line 118, in _expand_file_annotations
    raise RuntimeError(src_path + ' ' + '\n'.join(str(arg) for arg in exc.args))
RuntimeError: /home/simon/Desktop/DeepRL-1.1/examples_ddppo.py 'Module' object has no attribute 'last_line'
```

**Comment by SparkSnail** [comment] 2020-01-07 06:18
Hi @forhonourlx , this error is raised by NNI annotation, are you using annotation in NNI?

**Comment by forhonourlx** [comment] 2020-01-07 06:21
Yes. I simply tried an annotation as following:
```
    '''@nni.variable(nni.choice(8, 16), name=num_workers)'''
    config.num_workers = 16#
```

**Comment by SparkSnail** [comment] 2020-01-07 06:31
Add @liuzhe-lz  for this issue, he is more familiar with annotation.

**Comment by liuzhe-lz** [comment] 2020-01-07 07:29
I'm not sure if annotation supports attribute. Please try assigning to a local variable first.
```
'''@nni.variable(nni.choice(8, 16), name=num_workers)'''
num_workers = 16
config.num_workers = num_workers
```
Looks strange, but I'm not familiar with current annotation module either...

**Comment by forhonourlx** [comment] 2020-01-07 07:42
Thank you both.
I will try or raise a new issue.

**Comment by forhonourlx** [comment] 2020-01-07 07:55
Hi @liuzhe-lz,
Fixing annotation name `config.num_workers` works.
Thank you for your help.

**Closed** 2020-01-17 06:48 UTC
Labels: answered, customer raised
