### ISSUE TITLE
nnictl experiment list --all should show experiment name as well

### ISSUE THREAD

**Issue by ksachdeva** [microsoft/nni#1628] opened 2019-10-18 15:16 UTC
**What would you like to be added**:

At present 
```bash
nnictl experiment list --all
```
shows all the previous experiments however they are listed by experiment ID.

It would be good to display the experiment name as well

**Why is this needed**:

Since experiment Id is auto generated it is difficult to remember to which experiment it belongs. 

**Without this feature, how does current nni work**：

I have to go in all the experiments to figure out which is the one that I need to look at.

**Components that may involve changes**:

**Brief description of your proposal if any**:

One straightforward approach is to add a column with experiment names. These experiment names do not need to unique. User should be able to combine experiment name & date to figure out which one he/she is interested in.

Other approach is to have another command that lists a table that shows the mapping between experiment names and auto generated Ids.

**Comment by ultmaster** [comment] 2019-10-20 02:32
Duplicate of #1615.

**Closed** 2019-11-11 01:22 UTC
Labels: customer raised, known issue
