### ISSUE TITLE
executorArray in ExecutorManager is always []??

### ISSUE THREAD

**Issue by ouyanghaley** [microsoft/nni#2430] opened 2020-05-14 03:07 UTC
the **executorArray**  is never added?
nowhere can I find the call of addNewShellExecutor in **remoteplatform**
so everytime we schedule an executor to a trial , the ssh will create a new connection??
is it a bug??

**Comment by squirrelsc** [comment] 2020-05-14 13:55
A new one will be added when there is no available reference, but if a trial is end, it will release a reference. The number of opened connections depends on concurrent trials, and it's set in experiment config.

The code is refactoring, and related logic is more clear in remoteMachineData.ts. It holds a map (executorMap) of trial to executor, and a whole list (executors) of opened connections for reusing and closing.
https://github.com/microsoft/nni/pull/2431/files

Feel free to let us know, if there is any question.

**Closed by squirrelsc** 2020-05-14 13:55 UTC

**Comment by ouyanghaley** [comment] 2020-05-15 02:01
well, I see this commit is not merged into master yet, and executorMap in the old remoteMachineData.ts has this problem~
what I want to say is that when we run many trials, the gpus on some machine is not used,  so I wonder if this is caused by too many ssh connection is created, and reach the maxnum of the machine ssh connection

**Comment by squirrelsc** [comment] 2020-05-15 02:22
There are various reasons causing this problem. For example, though there are free GPUs, but NNI experiment may reach limitation of concurrency, or there are no more trials to dispatch. Please share your config, observation and log, so we can have a look.

**Comment by ouyanghaley** [comment] 2020-05-22 03:54
thank you for your reply，since I do not have the test environment now, I'll show you config and other necessary data later when this problem comes out
by the way , I have another question, which is in remoteMachineTrainingService.ts, **the function of updateGpuRevervation will release set occupiednum of unkown status**, isn't this weird?? **since unkown status may mean trial is still runnning**

**Comment by squirrelsc** [comment] 2020-05-22 04:38
> thank you for your reply，since I do not have the test environment now, I'll show you config and other necessary data later when this problem comes out
> by the way , I have another question, which is in remoteMachineTrainingService.ts, **the function of updateGpuRevervation will release set occupiednum of unkown status**, isn't this weird?? **since unkown status may mean trial is still runnning**

Unknown is a weired state, and the trial may or may not run at this state. If regard this state as running, it may cause GPU resource leaking. So it's considered as not running.

**Comment by ouyanghaley** [comment] 2020-05-26 04:08
[5/26/2020, 2:58:45 AM] INFO [ '*******THU_PCL_NNI*******RM:{"port":22,"passwd":"123123","ip":"10.0.0.103","username":"root","occupiedGpuIndexMap":{}}, occupiedGpuIndexMap:{}' ]
[5/26/2020, 2:58:45 AM] INFO [ '*******THU_PCL_NNI*******RM:{"port":22,"passwd":"123123","ip":"10.0.0.198","username":"root","occupiedGpuIndexMap":{}}, occupiedGpuIndexMap:{}' ]
[5/26/2020, 2:58:45 AM] WARNING [ 'Scheduler: trialJob id M2cf9, no machine can be scheduled, return TMP_NO_AVAILABLE_GPU ' ]
[5/26/2020, 2:58:45 AM] INFO [ 'Right now no available GPU can be allocated for trial M2cf9, will try to schedule later' ]


look this log,  I run several times. and sometimes the machine gpu is not used, but still return no available gpu right now,why 
requiredgpu is 1

**Comment by squirrelsc** [comment] 2020-05-26 04:45
Is it consistently repro, or sometime happens? If it's consistent repro, please share your yml config. If it's not, run `nnictl stop`, and then check if there is Python process with `gpu_metrics_collector` keyword. Kill it and try again.

BTW, please make sure each machine run as one worker of an NNI instance.

**Comment by ouyanghaley** [comment] 2020-05-26 04:58
then check if there is Python process with gpu_metrics_collector keyword. Kill it and try again.---**almost this problem, do you know why cause this, and any way to prevent it ?**

**Comment by squirrelsc** [comment] 2020-05-26 08:24
It may be caused by gpu collector not killed correctly in some race condition. In next version, it's mitigated by allowing multiple instances of gpu collector on a machine. It may cause leaked python processes, but not happen on same problem. We will continue to improve it.
