### ISSUE TITLE
Improve output of model after apply_fixed_architecture

### ISSUE THREAD

**Issue by colorjam** [microsoft/nni#2352] opened 2020-04-20 10:52 UTC
Currently, print(model) show LayerChoice. Print the fixed modules would be better.

![image](https://user-images.githubusercontent.com/23700012/79743912-098f1280-8338-11ea-9574-c575a7b4fedb.png)

**Comment by ultmaster** [comment] 2020-04-21 07:28
Good suggestion. This issue has been already addressed in #2336, but the PR is still under review.

**Comment by ultmaster** [comment] 2020-04-21 07:31
Duplicate of #2316.

**Closed** 2020-04-21 12:21 UTC
Labels: NAS, enhancement, known issue
