### ISSUE TITLE
Dispatcher stream error, tuner may have crashed.

### ISSUE THREAD

**Issue by shovalf** [microsoft/nni#3853] opened 2021-06-21 06:13 UTC
**Describe the issue**:

The code worked a couple of months ago. Today it did not - I want it to do 200 trails but it always stops after 20 trails (meaning it succeeds to run 20 trails only) every time I run it and gives me the error 'Dispatcher stream error, tuner may have crashed'. I saw other issues and tried changing the versions of sklearn and scipy as said here https://github.com/microsoft/nni/issues/3405 but it didn't work for me. I can really use the help.

**Environment**:
- NNI version: 2.2
- Training service (local|remote|pai|aml|etc): remote
- Client OS: Linux
- Server OS (for remote mode only): nvidia
- Python version: 3.7.4
- PyTorch/TensorFlow version: pytorch 1.4.0
- Is conda/virtualenv/venv used?: conda
- Is running in Docker?: no

**Configuration**:
 - Experiment config (remember to remove secrets!): 

authorName: ****
experimentName: fine_tuning
trialConcurrency: 3   # max GPUs to use simultaneously.
maxExecDuration: 200h
maxTrialNum: 200
#choice: local, remote, pai
trainingServicePlatform: local
searchSpacePath: search_space.json
#choice: true, false
useAnnotation: false
tuner:
  #choice: TPE, Random, Anneal, Evolution, BatchTuner, MetisTuner
  #SMAC (SMAC should be installed through nnictl)
  builtinTunerName: TPE
  classArgs:
    #choice: maximize, minimize
    optimize_mode: maximize
trial:
  command: python nni_experiment.py
  codeDir: .
localConfig:
  maxTrialNumPerGpu: 4
  useActiveGpu: true

 - Search space:

**Log message**:

 - dispatcher.log:

[2021-06-20 15:21:21] INFO (hyperopt.utils/MainThread) Failed to load dill, try installing dill via "pip install dill" for enhanced pickling support.
[2021-06-20 15:21:21] INFO (hyperopt.fmin/MainThread) Failed to load dill, try installing dill via "pip install dill" for enhanced pickling support.
[2021-06-20 15:21:21] INFO (nni.runtime.msg_dispatcher_base/MainThread) Dispatcher started
[2021-06-20 15:21:21] INFO (hyperopt.tpe/Thread-1) tpe_transform took 0.009032 seconds
[2021-06-20 15:21:21] INFO (hyperopt.tpe/Thread-1) TPE using 0 trials
[2021-06-20 15:21:21] INFO (hyperopt.tpe/Thread-1) tpe_transform took 0.007161 seconds
[2021-06-20 15:21:21] INFO (hyperopt.tpe/Thread-1) TPE using 0 trials
[2021-06-20 15:21:21] INFO (hyperopt.tpe/Thread-1) tpe_transform took 0.006782 seconds
[2021-06-20 15:21:21] INFO (hyperopt.tpe/Thread-1) TPE using 0 trials
[2021-06-20 16:08:53] INFO (hyperopt.tpe/Thread-1) tpe_transform took 0.009080 seconds
[2021-06-20 16:08:53] INFO (hyperopt.tpe/Thread-1) TPE using 1/1 trials with best loss -0.579336
[2021-06-20 16:17:51] INFO (hyperopt.tpe/Thread-1) tpe_transform took 0.009668 seconds
[2021-06-20 16:17:51] INFO (hyperopt.tpe/Thread-1) TPE using 2/2 trials with best loss -0.581181
[2021-06-20 16:18:41] INFO (hyperopt.tpe/Thread-1) tpe_transform took 0.008405 seconds
[2021-06-20 16:18:41] INFO (hyperopt.tpe/Thread-1) TPE using 3/3 trials with best loss -0.581181
[2021-06-20 16:19:16] INFO (hyperopt.tpe/Thread-1) tpe_transform took 0.010412 seconds
[2021-06-20 16:19:16] INFO (hyperopt.tpe/Thread-1) TPE using 3/3 trials with best loss -0.581181
[2021-06-20 16:19:56] INFO (hyperopt.tpe/Thread-1) tpe_transform took 0.009555 seconds
[2021-06-20 16:19:56] INFO (hyperopt.tpe/Thread-1) TPE using 3/3 trials with best loss -0.581181
[2021-06-20 16:59:23] INFO (hyperopt.tpe/Thread-1) tpe_transform took 0.008884 seconds
[2021-06-20 16:59:23] INFO (hyperopt.tpe/Thread-1) TPE using 4/4 trials with best loss -0.630996
[2021-06-20 17:18:08] INFO (hyperopt.tpe/Thread-1) tpe_transform took 0.009511 seconds
[2021-06-20 17:18:08] INFO (hyperopt.tpe/Thread-1) TPE using 5/5 trials with best loss -0.630996
[2021-06-20 17:18:33] INFO (hyperopt.tpe/Thread-1) tpe_transform took 0.008375 seconds
[2021-06-20 17:18:33] INFO (hyperopt.tpe/Thread-1) TPE using 6/6 trials with best loss -0.630996
[2021-06-20 17:19:14] INFO (hyperopt.tpe/Thread-1) tpe_transform took 0.009090 seconds
[2021-06-20 17:19:14] INFO (hyperopt.tpe/Thread-1) TPE using 6/6 trials with best loss -0.630996
[2021-06-20 17:55:45] INFO (hyperopt.tpe/Thread-1) tpe_transform took 0.082595 seconds
[2021-06-20 17:55:45] INFO (hyperopt.tpe/Thread-1) TPE using 7/7 trials with best loss -0.630996
[2021-06-20 18:18:06] INFO (hyperopt.tpe/Thread-1) tpe_transform took 0.008675 seconds
[2021-06-20 18:18:06] INFO (hyperopt.tpe/Thread-1) TPE using 8/8 trials with best loss -0.630996
[2021-06-20 18:18:26] INFO (hyperopt.tpe/Thread-1) tpe_transform took 0.008308 seconds
[2021-06-20 18:18:26] INFO (hyperopt.tpe/Thread-1) TPE using 9/9 trials with best loss -0.630996
[2021-06-20 18:56:43] INFO (hyperopt.tpe/Thread-1) tpe_transform took 0.009833 seconds
[2021-06-20 18:56:43] INFO (hyperopt.tpe/Thread-1) TPE using 10/10 trials with best loss -0.630996
[2021-06-20 19:07:51] INFO (hyperopt.tpe/Thread-1) tpe_transform took 0.008876 seconds
[2021-06-20 19:07:51] INFO (hyperopt.tpe/Thread-1) TPE using 11/11 trials with best loss -0.630996
[2021-06-20 19:08:26] INFO (hyperopt.tpe/Thread-1) tpe_transform took 0.008206 seconds
[2021-06-20 19:08:26] INFO (hyperopt.tpe/Thread-1) TPE using 12/12 trials with best loss -0.630996
[2021-06-20 19:56:41] INFO (hyperopt.tpe/Thread-1) tpe_transform took 0.008921 seconds
[2021-06-20 19:56:41] INFO (hyperopt.tpe/Thread-1) TPE using 13/13 trials with best loss -0.630996
[2021-06-20 19:58:32] INFO (hyperopt.tpe/Thread-1) tpe_transform took 0.009233 seconds
[2021-06-20 19:58:32] INFO (hyperopt.tpe/Thread-1) TPE using 14/14 trials with best loss -0.630996
[2021-06-20 20:04:03] INFO (hyperopt.tpe/Thread-1) tpe_transform took 0.008904 seconds
[2021-06-20 20:04:03] INFO (hyperopt.tpe/Thread-1) TPE using 15/15 trials with best loss -0.630996
[2021-06-20 20:04:39] INFO (hyperopt.tpe/Thread-1) tpe_transform took 0.009141 seconds
[2021-06-20 20:04:39] INFO (hyperopt.tpe/Thread-1) TPE using 15/15 trials with best loss -0.630996
[2021-06-20 20:05:19] INFO (hyperopt.tpe/Thread-1) tpe_transform took 0.010034 seconds
[2021-06-20 20:05:19] INFO (hyperopt.tpe/Thread-1) TPE using 15/15 trials with best loss -0.630996
[2021-06-20 20:45:46] INFO (hyperopt.tpe/Thread-1) tpe_transform took 0.007759 seconds
[2021-06-20 20:45:46] INFO (hyperopt.tpe/Thread-1) TPE using 16/16 trials with best loss -0.632388
[2021-06-20 20:50:12] INFO (hyperopt.tpe/Thread-1) tpe_transform took 0.008982 seconds
[2021-06-20 20:50:12] INFO (hyperopt.tpe/Thread-1) TPE using 17/17 trials with best loss -0.632388
[2021-06-20 20:54:59] INFO (hyperopt.tpe/Thread-1) tpe_transform took 0.009157 seconds
[2021-06-20 20:54:59] INFO (hyperopt.tpe/Thread-1) TPE using 18/18 trials with best loss -0.632388
[2021-06-20 21:34:35] INFO (hyperopt.tpe/Thread-1) tpe_transform took 0.009719 seconds
[2021-06-20 21:34:35] INFO (hyperopt.tpe/Thread-1) TPE using 19/19 trials with best loss -0.632388
[2021-06-20 21:45:59] INFO (hyperopt.tpe/Thread-1) tpe_transform took 0.009353 seconds
[2021-06-20 21:45:59] INFO (hyperopt.tpe/Thread-1) TPE using 20/20 trials with best loss -0.632388
[2021-06-20 21:45:59] ERROR (nni.runtime.msg_dispatcher_base/Thread-1) 
Traceback (most recent call last):
  File "/home/dsi/aviv/anaconda3/envs/gcn3/lib/python3.7/site-packages/nni/runtime/msg_dispatcher_base.py", line 88, in command_queue_worker
    self.process_command(command, data)
  File "/home/dsi/aviv/anaconda3/envs/gcn3/lib/python3.7/site-packages/nni/runtime/msg_dispatcher_base.py", line 147, in process_command
    command_handlers[command](data)
  File "/home/dsi/aviv/anaconda3/envs/gcn3/lib/python3.7/site-packages/nni/runtime/msg_dispatcher.py", line 101, in handle_request_trial_jobs
    params_list = self.tuner.generate_multiple_parameters(ids, st_callback=self.send_trial_callback)
  File "/home/dsi/aviv/anaconda3/envs/gcn3/lib/python3.7/site-packages/nni/tuner.py", line 132, in generate_multiple_parameters
    res = self.generate_parameters(parameter_id, **kwargs)
  File "/home/dsi/aviv/anaconda3/envs/gcn3/lib/python3.7/site-packages/nni/algorithms/hpo/hyperopt_tuner.py", line 278, in generate_parameters
    total_params = self.get_suggestion(random_search=False)
  File "/home/dsi/aviv/anaconda3/envs/gcn3/lib/python3.7/site-packages/nni/algorithms/hpo/hyperopt_tuner.py", line 455, in get_suggestion
    new_trials = algorithm(new_ids, rval.domain, trials, random_state)
  File "/home/dsi/aviv/anaconda3/envs/gcn3/lib/python3.7/site-packages/hyperopt/tpe.py", line 900, in suggest
    print_node_on_error=False)
  File "/home/dsi/aviv/anaconda3/envs/gcn3/lib/python3.7/site-packages/hyperopt/pyll/base.py", line 913, in rec_eval
    rval = scope._impls[node.name](*args, **kwargs)
  File "/home/dsi/aviv/anaconda3/envs/gcn3/lib/python3.7/site-packages/hyperopt/tpe.py", line 465, in adaptive_parzen_normal
    assert prior_sigma > 0
AssertionError
[2021-06-20 21:46:01] INFO (nni.runtime.msg_dispatcher_base/MainThread) Dispatcher exiting...
[2021-06-20 21:46:04] INFO (nni.runtime.msg_dispatcher_base/MainThread) Dispatcher terminiated

 - nnictl stdout and stderr:

- nnimanager.log:
[nni log.txt](https://github.com/microsoft/nni/files/6684428/nni.log.txt)

**Comment by liuzhe-lz** [comment] 2021-06-22 07:54
What's your search space?

**Comment by shovalf** [comment] 2021-06-22 08:48
[search_space.txt](https://github.com/microsoft/nni/files/6692731/search_space.txt)

**Comment by liuzhe-lz** [comment] 2021-06-25 04:17
The bounds of "uniform" must be sorted. It should be `[1e-5, 1e-2]` and `[1e-4, 1e-2]`.

**Comment by liuzhe-lz** [comment] 2021-06-25 04:21
duplicate of #1496

**Closed by liuzhe-lz** 2021-06-25 04:21 UTC
Labels: HPO, customer raised, support
