### ISSUE TITLE
TypeError: __new__() missing 1 required positional argument: 'task'

### ISSUE THREAD

**Issue by zzfer490** [microsoft/nni#5483] opened 2023-03-28 01:18 UTC
**Describe the issue**: Hello, developers. I'm a newbie just getting started learning nas. When I run the tutorial file in the notebook, I get an error, I hope you can help me to solve this problem：

 File "search_2.py", line 59, in <module>
    max_epochs=5)
  File "D:\anaconda3\envs\venv_copy\lib\site-packages\nni\nas\evaluator\pytorch\lightning.py", line 372, in __init__
    weight_decay=weight_decay, optimizer=optimizer, export_onnx=export_onnx)
  File "D:\anaconda3\envs\venv_copy\lib\site-packages\nni\common\serializer.py", line 473, in new_init        
    **{kw: _argument_processor(arg) for kw, arg in kwargs.items()}
  File "D:\anaconda3\envs\venv_copy\lib\site-packages\nni\nas\evaluator\pytorch\lightning.py", line 310, in __init__
    export_onnx=export_onnx)
  File "D:\anaconda3\envs\venv_copy\lib\site-packages\nni\nas\evaluator\pytorch\lightning.py", line 224, in __init__
    self.metrics = nn.ModuleDict({name: cls() for name, cls in metrics.items()})
  File "D:\anaconda3\envs\venv_copy\lib\site-packages\nni\nas\evaluator\pytorch\lightning.py", line 224, in <dictcomp>
    self.metrics = nn.ModuleDict({name: cls() for name, cls in metrics.items()})
TypeError: __new__() missing 1 required positional argument: 'task'

here is the demo code of Retiarii_example_multi-trial_NAS ，When calling pl.Classification() the error is reported.

```python
@model_wrapper
class Net(nn.Module):
    def __init__(self):
        super().__init__()
        self.conv1 = nn.LayerChoice([nn.Conv2d(3, 6, 3, padding=1), nn.Conv2d(3, 6, 5, padding=2)])# input[3,32,32] output[6,32,32]
        self.pool = nn.MaxPool2d(2, 2)  #output[6,16,16]
        self.conv2 = nn.LayerChoice([nn.Conv2d(6, 16, 3, padding=1), nn.Conv2d(6, 16, 5, padding=2)])  #output[16,16,16]
        self.conv3 = nn.Conv2d(16, 16, 1)  #output[16,16,16]
        self.skipconnect = nn.InputChoice(n_candidates=2)
        self.bn = nn.BatchNorm2d(16)
        self.gap = nn.AdaptiveAvgPool2d(4)  #output[16,4,4]
        self.fc1 = nn.Linear(16 * 4 * 4, 120)
        self.fc2 = nn.Linear(120, 84)
        self.fc3 = nn.Linear(84, 10)

    def forward(self, x):
        bs = x.size(0)
        x = self.pool(F.relu(self.conv1(x)))
        x0 = F.relu(self.conv2(x))
        x1 = F.relu(self.conv3(x0))
        x1 = self.skipconnect([x1, x1+x0])
        x = self.pool(self.bn(x1))
        x = self.gap(x).view(bs, -1)
        x = F.relu(self.fc1(x))
        x = F.relu(self.fc2(x))
        x = self.fc3(x)
        return x

model = Net()
simple_strategy = strategy.Random() # choice: Random, GridSearch, RegularizedEvolution, TPEStrategy
transform = transforms.Compose([transforms.ToTensor(), transforms.Normalize((0.5, 0.5, 0.5), (0.5, 0.5, 0.5))])
train_dataset = serialize(CIFAR10, root="./data_cifar10", train=True, download=True, transform=transform)
test_dataset = serialize(CIFAR10, root="./data_cifar10", train=False, download=True, transform=transform)
trainer = pl.Classification(train_dataloader=pl.DataLoader(train_dataset, batch_size=16),
                                val_dataloaders=pl.DataLoader(test_dataset, batch_size=16),
                                max_epochs=5, gpus=[0])

if __name__ == '__main__':
    exp = RetiariiExperiment(model, trainer, [], simple_strategy)
    exp_config = RetiariiExeConfig('local')
    exp_config.experiment_name = 'search darts example'
    exp_config.trial_concurrency = 1
    exp_config.max_trial_number = 10
    exp_config.trial_gpu_number = 1
    exp_config.max_experiment_duration = '10m'
    exp_config.execution_engine = 'base'
    exp_config.training_service.use_active_gpu = True
    exp.run(exp_config, 8745)
    print('Final model:')
    for model_code in exp.export_top_models():
        print(model_code)
 
    exp.stop()
``` 

**Environment**:
- NNI version:2.10
- Training service (local|remote|pai|aml|etc):local
- Client OS:
- Server OS (for remote mode only):
- Python version:3.7.11
- PyTorch/TensorFlow version:pytorch 1.11
- Is conda/virtualenv/venv used?: yes
- Is running in Docker?: no

**Comment by zzfer490** [comment] 2023-03-28 02:32
When I try to use other code, whenever I use the Classification classifier, it reports the error:TypeError: __new__() missing 1 required positional argument: 'task'

**Comment by matluster** [comment] 2023-03-29 02:17
Duplicate of #5329

**Comment by zzfer490** [comment] 2023-03-29 02:35
thanks，it works

**Closed** 2023-03-29 02:38 UTC
