### ISSUE TITLE
Automatic Model Compression Example 

### ISSUE THREAD

**Issue by suiguoxin** [microsoft/nni#2350] opened 2020-04-20 07:40 UTC
I tried to run the automatic model compression example provided in https://github.com/microsoft/nni/blob/master/docs/en_US/Compressor/AutoCompression.md. 
Some problems:
- format error in search_space.json (line 20, line 37)
- what is nni.get_parameters () ? (*.py, line 3)
- could you pls provide the full example folder ? (with run_prune.sh, ...etc)

**Comment by QuanluZhang** [comment] 2020-04-22 04:55
@suiguoxin Currently, this doc is only for guidance, we have not provided the complete example code.

Making model compression completely automatic is an ongoing work item, we will release full fledged version of this feature soon.

**Comment by scarlett2018** [comment] 2020-04-23 03:33
@QuanluZhang - the issue is assigned to @suiguoxin for complete this example?

**Closed** 2021-03-25 03:40 UTC
Labels: example, model compression, nnidev
