### ISSUE TITLE
install nnimanager on windows

### ISSUE THREAD

**Issue by leckie-chn** [Microsoft/nni#970] opened 2019-04-10 03:01 UTC
@demianzhang
## install log

yarn install v1.15.2

[1/5] Validating package.json...

[2/5] Resolving packages...

[3/5] Fetching packages...

[4/5] Linking dependencies...

warning " > express-joi-validator@2.0.0" has unmet peer dependency "joi@6.x.x".

[5/5] Building fresh packages...

**error C:\Users\yann\Desktop\code\nni\src\nni_manager\node_modules\sqlite3: Command failed.**

Exit code: 1

Command: node-pre-gyp install --fallback-to-build

Arguments:

Directory: C:\Users\yann\Desktop\code\nni\src\nni_manager\node_modules\sqlite3

Output:

**'node-pre-gyp' is not recognized as an internal or external command,**

operable program or batch file.

info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

yarn run v1.15.2

$ tsc

Done in 4.25s.

yarn install v1.15.2

[1/4] Resolving packages...

success Already up-to-date.

Done in 0.66s.

yarn run v1.15.2

$ react-scripts-ts-antd build

**'react-scripts-ts-antd' is not recognized as an internal or external command,**

operable program or batch file.

error Command failed with exit code 1.

info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by leckie-chn** [comment] 2019-04-10 03:10
can be solved by manually install `node-gyp` & `react-scripts-ts-antd` with `npm install -g`. While still requires better solution

**Comment by demianzhang** [comment] 2019-04-10 03:18
Could you offer more details of python and other environment? I want to reproduce the same error, however the conda and local python installing did not show this error.

**Comment by leckie-chn** [comment] 2019-04-10 08:46
also, before installing, users need to run `Set-ExecutionPolicy -ExecutionPolicy Unrestricted` in powershell

**Comment by leelaylay** [comment] 2019-04-11 02:44
I can't find `tar` command in Windows 10 Build 16299 . After I talked with @demianzhang, I found that `tar` was added to Windows toolchain since Windows Insider Build 17063.

Refer: https://docs.microsoft.com/en-us/virtualization/community/team-blog/2017/20171219-tar-and-curl-come-to-windows

**Comment by demianzhang** [comment] 2019-04-11 08:03
Firstly, You can add "node-pre-gyp":"^0.12.0" before "sqlite3": "^4.0.2" in nni/src/nni_manager/package.json "dependencies" to install this package. In my environment I have not  installed node-pre-gyp, but no error.

Secondly, you can uninstall nni or clone a new windows local mode nni to install. Because of the information of "success Already up-to-date.", I can not get the detail information of 'react-scripts-ts-antd' when you did not uninstall the nni completely. Thanks.

**Comment by demianzhang** [comment] 2019-04-15 08:36
Fixed with new clone.

**Closed** 2019-05-06 03:50 UTC
