### ISSUE TITLE
how to extract the final generated model from the search space?

### ISSUE THREAD

**Issue by marsggbo** [microsoft/nni#2150] opened 2020-03-15 02:19 UTC
I used ENAS to search for models on my own datasets, and the real size of the final generated model is 13 M. The way of calculating the real size of the model refers to issue #1947.  

My GPU is Titan X (Pascal), if I set the image size 112x112, the maximum batch size is 12. However, the batch size for [Nasnetamobile ](https://github.com/Cadene/pretrained-models.pytorch#nasnet)(size=16M) can be set 64. 

So I wonder how to extract the final generated model from the search space to make full use of GPU?

**Comment by ultmaster** [comment] 2020-03-15 03:45
Final generated model can be extracted by replacing the module LayerChoice with the exact selected module. Currently you have to implement this on your own, but this will be likely supported in next (or next-next) release.

I don't fully understand paragraph 1 and 2. Your intention is not clear to me. First, as you may know, the parameter size is completely not related to your image size, or batch size. I wonder why you report them to me. Second of all, if your final intention is to fully leverage the GPU resource, you should be looking elsewhere, because deleting unused modules from LayerChoice is not going to help a lot on that.

**Comment by marsggbo** [comment] 2020-03-15 03:55
Thanks for your reply. The reason why I report the above data is that I don't quite understand why the final generated model is smaller than Nasnetamobile, but the max batch size is also much smaller?

**Comment by ultmaster** [comment] 2020-03-15 04:01
I'm suspecting that this is caused by the structural/implementation (e.g., inplace op) difference between ENAS and NasNet. If you still have concern about preserving the unused weights in your model, you should at least try the elimination method I proposed above.

**Comment by marsggbo** [comment] 2020-03-17 08:58
I think the reason why retraining the generated model using nni requires much more GPU memory than the normal model is that the parameters of the unselected paths are also stored in GPU even though they do not need to be calculated. Can we freeze these unselected paths' weights to alleviate the above problem?  If so, is there any recommended simple way to freeze those parameters?

**Comment by ultmaster** [comment] 2020-03-17 09:07
Yes. If that's what you want, as explained in my previous reply, you can substitute the layer choice with selected layer. I'll demonstrate a code snippet here to make it clear to you.

```python
fixed_arc = json.load(...)
retrieved_modules = dict()
for name, m in model.named_modules():
    if isinstance(m, LayerChoice):
        # store the choices for substitution
        retrieved_modules[name] = m.choices[fixed_arc[m.key].index(True)]

# substitute
for name, m in retrieved_modules.items():
    module = model
    for k in name.split(".")[:-1]:
        module = getattr(module, k)
    setattr(module, name.split(".")[-1], retrieved_modules[name])
```

This is just a high-level idea. I didn't test it and you might need to adjust it to make it work in your code.

**Comment by kvartet** [comment] 2020-12-07 04:15
I’m closing this issue as it has no updates from customer for 3 months, please feel free to reopen if you are still seeing it an active issue.

**Closed by kvartet** 2020-12-07 04:15 UTC
Labels: FAQ, NAS, customer raised, question
