### ISSUE TITLE
Crashes after the first trial on macOS & Ubuntu with AttributeError: module 'bson' has no attribute 'BSON'

### ISSUE THREAD

**Issue by ksachdeva** [microsoft/nni#1627] opened 2019-10-18 13:09 UTC
**Short summary about the issue/question**:

The nni server stops (port still occupied) after the first trial in an experiment on macOS
The nni server crashes after the first trial in an experiment on Ubuntu 18

**Brief what process you are following**: 

This Example - https://github.com/microsoft/nni/tree/master/examples/trials/mnist

```bash
# Below commands are executed in a virtualenv 
# Tried two versions of python 3.7.4 and 3.6.9 but same issue
pip install tensorflow==1.15.0
pip install nni
```

**How to reproduce it**: 

**nni Environment**:
- nni version: 1.0
- nni mode(local|pai|remote): local
- OS: macOS, Ubuntu 18.04
- python version:  3.7.4
- is conda or virtualenv used?: virtualenv 
- is running in docker?: no

**need to update document(yes/no)**:

**Anything else we need to know**:

Attached is the log from one experiment on macOS (behavior is same on Ubuntu 18)

```bash
[10/17/2019, 09:06:39 PM] INFO (nni.msg_dispatcher_base/MainThread) Start dispatcher
[10/17/2019, 09:06:39 PM] INFO (hyperopt.tpe/Thread-1) tpe_transform took 0.002303 seconds
[10/17/2019, 09:06:39 PM] INFO (hyperopt.tpe/Thread-1) TPE using 0 trials
[10/17/2019, 09:08:54 PM] PRINT --------------------------------------------------------------------------------
[10/17/2019, 09:08:54 PM] PRINT CANT ENCODE
[10/17/2019, 09:08:54 PM] PRINT --------------------------------------------------------------------------------
[10/17/2019, 09:08:54 PM] ERROR (nni.msg_dispatcher_base/Thread-1) module 'bson' has no attribute 'BSON'
Traceback (most recent call last):
  File "/Users/ksachdeva/Desktop/Dev/exp/nniexp/env/lib/python3.7/site-packages/nni/msg_dispatcher_base.py", line 102, in command_queue_worker
    self.process_command(command, data)
  File "/Users/ksachdeva/Desktop/Dev/exp/nniexp/env/lib/python3.7/site-packages/nni/msg_dispatcher_base.py", line 160, in process_command
    command_handlers[command](data)
  File "/Users/ksachdeva/Desktop/Dev/exp/nniexp/env/lib/python3.7/site-packages/nni/msg_dispatcher.py", line 138, in handle_report_metric_data
    self._handle_final_metric_data(data)
  File "/Users/ksachdeva/Desktop/Dev/exp/nniexp/env/lib/python3.7/site-packages/nni/msg_dispatcher.py", line 182, in _handle_final_metric_data
    self.tuner.receive_trial_result(id_, _trial_params[id_], value)
  File "/Users/ksachdeva/Desktop/Dev/exp/nniexp/env/lib/python3.7/site-packages/nni/hyperopt_tuner/hyperopt_tuner.py", line 384, in receive_trial_result
    trials.insert_trial_docs([trial])
  File "/Users/ksachdeva/Desktop/Dev/exp/nniexp/env/lib/python3.7/site-packages/hyperopt/base.py", line 435, in insert_trial_docs
    for doc in docs]
  File "/Users/ksachdeva/Desktop/Dev/exp/nniexp/env/lib/python3.7/site-packages/hyperopt/base.py", line 435, in <listcomp>
    for doc in docs]
  File "/Users/ksachdeva/Desktop/Dev/exp/nniexp/env/lib/python3.7/site-packages/hyperopt/base.py", line 399, in assert_valid_trial
    bson.BSON.encode(trial)
AttributeError: module 'bson' has no attribute 'BSON'
[10/17/2019, 09:08:58 PM] INFO (nni.msg_dispatcher_base/MainThread) Dispatcher exiting...
[10/17/2019, 09:08:58 PM] INFO (nni.msg_dispatcher_base/MainThread) Terminated by NNI manager
```

**Comment by ksachdeva** [comment] 2019-10-18 13:29
I managed to resolve it by installing pymongo as well. Not sure what is the connection here but here is the workaround.

```bash
pip install pymongo
```

**Comment by ultmaster** [comment] 2019-10-20 02:34
Try to run `pip install hyperopt==0.1.2`. This issue is likely to caused by a recent hyperopt release.

**Comment by scarlett2018** [comment] 2020-04-15 06:34
> Try to run `pip install hyperopt==0.1.2`. This issue is likely to caused by a recent hyperopt release.

Hi @ksachdeva - had you try the above suggestion? does it work?

**Comment by scarlett2018** [comment] 2020-08-03 03:13
closing the issue as it has been 4 months without update. @ksachdeva - feel free to reopen the issue if it is still a problem on your side.

**Closed by scarlett2018** 2020-08-03 03:13 UTC
Labels: HPO, customer raised, example, get start, support, waiting customer confirm
