### ISSUE TITLE
Trial search keywords get cleared when search type is changed

### ISSUE THREAD

**Issue by ultmaster** [microsoft/nni#1990] opened 2020-02-03 07:35 UTC
For example, when search type is changed from ID to params, keywords that has already been typed get cleared.

**Comment by scarlett2018** [comment] 2020-04-13 03:19
Lijiao, @yangou1988 @ultmaster to figure out what's the common behavior for this kind of Web UI control.

**Comment by kvartet** [comment] 2021-06-15 10:30
@Lijiaoa - would you mind testing this issue existing now?

**Comment by Lijiaoa** [comment] 2021-06-16 10:18
It is by design... Also, we refactor the search ([the design](https://www.figma.com/file/HX8Og03m2rwNU1TS6rMTF1/0416-Fluent-Web-NNI-Filter?node-id=40047%3A6959)) on nni `v2.3`. It had fixed this question.

**Comment by kvartet** [comment] 2021-06-17 02:32
> It is by design... Also, we refactor the search ([the design](https://www.figma.com/file/HX8Og03m2rwNU1TS6rMTF1/0416-Fluent-Web-NNI-Filter?node-id=40047%3A6959)) on nni `v2.3`. It had fixed this question.

as it has been fixed, I will close this issue

**Closed by kvartet** 2021-06-17 02:32 UTC
Labels: bug, nnidev
